.github/workflows/preview.yml

解决第一次 push 时 PR 还没有创建拿不到 `pr.number` 的问题。
afc163/surge-preview#13

chore: run PR preview on pull_request

---

packages/table/src/Form/index.tsx
tests/table/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/index.test.tsx.snap

```tsx
<ProFormField name={key || dataIndex} />
useDeepCompareEffect(() => {
const tempMap = {};
counter.proColumns.forEach((item) => {
// 以key为主,理论上key唯一
tempMap[genColumnKey((item.key || item.dataIndex) as string, item.index)] = item.valueType;
});
valueTypeRef.current = tempMap;
}, [counter.proColumns]);
```
理论上column key是唯一的,所有优先以column key为主,如果没有key则已dataIndex为主,也就是更改`<ProFormField name={key || dataIndex} />`以达到valueTypeRef与values字段的统一,从而达到在`conversionSubmitValue`进行`Moment -> string`的表现中正确.
close #375  close #349

🐛 fix(compiler): 修复ProTable column key表现异常

---

packages/table/src/Form/index.tsx

```tsx
const columns = [
{
title: '创建时间',
dataIndex: 'createdAt',
valueType: () => 'dateTime',
},
];
```
如果`valueType`是函数并且返回`date`、`time`、`dateTime`、`dateRange`、`dateTimeRange`的话, 依然会出现`conversionSubmitValue`日期不能正常从`moment -> string | number`.

🐛 fix(table): 修复valueType函数返回date等日期类型格式化异常

---

packages/layout/src/SiderMenu/SiderMenu.tsx
packages/layout/src/SiderMenu/index.tsx

close https://github.com/ant-design/pro-components/issues/136
close https://github.com/ant-design/ant-design-pro/issues/7114

🐛 fix(layout): fix splitMenus error in mobile mode

---

packages/table/src/component/ColumnSetting/index.tsx

在table初始化时，缓存初始化设置的columnsStateMap。
在操作列设置的重置按钮时，设置成初始化的列展示字段
close https://github.com/ant-design/pro-components/issues/515

feat(Table): Fix column reset to default column display

---

packages/table/src/Table.tsx
tests/table/index.test.tsx

当前的写法一旦 action.loading 为 true 时，props 中传入的 loading 会失效。
改造为：props.loading 只要传入，优先选择 props.loading 的值。

fix(table): 将 table 的loading 属性改为全受控

---

packages/card/src/card.md
packages/card/src/demos/group.tsx
packages/card/src/index.tsx
packages/card/src/style/index.less
packages/table/src/table.md
tests/card/__snapshots__/demo.test.ts.snap
tests/card/index.test.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/skeleton/__snapshots__/demo.test.ts.snap

feat(card): 添加卡片组展开

---

packages/table/src/useFetchData.tsx

This bug was fixed by #693 but reintroduced by #706.
The second `if` is still necessary because there is an `await` before it.

fix(table): should do nothing when component unmounted before getData resolved, close #692

---

packages/form/src/demos/light-filter-collapse.tsx
packages/form/src/layouts/LightFilter/index.less
packages/form/src/layouts/LightFilter/index.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/form/lightFilter.test.tsx
tests/list/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/demo.test.ts.snap

feat: add effective style to LightFilter when collapse

---

.codecov.yml
packages/layout/src/SettingDrawer/BlockCheckbox.tsx
packages/layout/src/SettingDrawer/index.less
packages/layout/src/SettingDrawer/index.tsx
tests/layout/__snapshots__/demo.test.ts.snap
tests/layout/__snapshots__/settingDrawer.test.tsx.snap

对比一下效果
| svg | css 伪类 :new: |
| --- | --- |
| <img width="292" alt="截屏2020-10-22 下午1 23 49" src="https://user-images.githubusercontent.com/507615/96828747-c3437900-146a-11eb-8771-e7a1e925514d.png"> | <img width="223" alt="image" src="https://user-images.githubusercontent.com/507615/96828685-ad35b880-146a-11eb-90a7-1bed132cc6c0.png"> |

refactor(layout): SettingDrawer card style

---

packages/table/src/component/ListToolBar/index.tsx
tests/list/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/demo.test.ts.snap

fix(pro-table):  table 工具栏：options为false时，不显示父级节点

---

packages/table/src/table.md

现在的文档好像没更新，`actionRef`返回的函数已经没有`fetchMore`了，改成`reloadAndRest`

fix(table.md): 修改ProTable文档中参数actionRef返回的函数

---

packages/layout/src/SettingDrawer/ThemeColor.less
packages/layout/src/SettingDrawer/ThemeColor.tsx

在 ThemeColor.tsx 文件的 45 行的 genThemeToString() 方法是根据 color 获取到 key 值，而此时传入 colorList 中的 key 与方法需要的参数信息不一致，导致 genThemeToString(key) 一直返回 undefined 因此导致 Tooltip 无提示内容（50-54行）。
45行修改后在其后添加一个默认的 key 是为了在自定义主题色（不存在系统预设列表中）时也可以显示 Tooltip 内容

fix(SettingDrawer): 修复主题色 Tooltip 无提示信息问题

---

packages/field/src/components/DatePicker/index.tsx
packages/field/src/components/RangePicker/index.tsx
packages/field/src/components/Select/LightSelect/index.tsx
packages/field/src/components/TimePicker/index.tsx
packages/field/src/index.tsx
packages/form/src/BaseForm/LightWrapper/index.tsx
packages/form/src/BaseForm/index.tsx
packages/form/src/demos/light-filter.tsx
packages/form/src/form.md
packages/form/src/interface.d.ts
packages/utils/src/components/FieldLabel/index.less
packages/utils/src/components/FieldLabel/index.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/form/lightFilter.test.tsx
tests/list/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/demo.test.ts.snap

support allowClear for hide clear icon in LightFilter

feat: LightFilter support allowClear

---

packages/form/src/BaseForm/createField.tsx
packages/form/src/BaseForm/index.tsx
packages/form/src/components/Captcha/index.tsx
packages/form/src/components/Checkbox/index.tsx
packages/form/src/components/DatePicker/DatePicker.tsx
packages/form/src/components/DatePicker/MonthPicker.tsx
packages/form/src/components/DatePicker/QuarterPicker.tsx
packages/form/src/components/DatePicker/WeekPicker.tsx
packages/form/src/components/DatePicker/YearPicker.tsx
packages/form/src/components/DateRangePicker/index.tsx
packages/form/src/components/DateTimePicker/index.tsx
packages/form/src/components/DateTimeRangePicker/index.tsx
packages/form/src/components/Digit/index.tsx
packages/form/src/components/Field/index.tsx
packages/form/src/components/FieldSet/index.tsx
packages/form/src/components/Radio/index.tsx
packages/form/src/components/Rate/index.tsx
packages/form/src/components/Select/index.tsx
packages/form/src/components/Slider/index.tsx
packages/form/src/components/Switch/index.tsx
packages/form/src/components/Text/index.tsx
packages/form/src/components/TextArea/index.tsx
packages/form/src/components/TimePicker/index.tsx
packages/form/src/components/UploadButton/index.tsx
packages/form/src/components/UploadDragger/index.tsx
packages/table/src/Form/index.tsx

close https://github.com/ant-design/pro-components/issues/1007

🐛 fix(table): No more transparent formitem

---

packages/card/src/index.tsx

缺失类型，在做 `direction={screens.md ? 'row' : 'column'}` 这样的格式时会类型错误

feat(card): add direction type

---

packages/table/src/table.md

labelWidth是可以传'auto'这个属性的。而且默认值是80。
这些和文档都有出入。

📝 docs: fix doc optional value

---

packages/form/src/layouts/QueryFilter/index.tsx
packages/table/src/Table.tsx
packages/table/src/component/ListToolBar/HeaderMenu.tsx
packages/table/src/demos/batchOption.tsx
packages/table/src/demos/dataSource.tsx
packages/table/src/demos/listToolBar.tsx
packages/table/src/demos/no-title.tsx
packages/table/src/demos/split.tsx
packages/table/src/table.md
tests/form/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/column.test.tsx.snap
tests/table/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/index.test.tsx.snap
tests/table/listtoolbar.test.tsx

1. 增加 DataSource 和 左右结构 的 protable 例子。
2. 修复表格layout 和form 在竖直状态下的padding 问题。
3. ListToolBar menu 增加 tab 类型，增加相应示例
4. 批量工具栏添加全选，反选示例。
close #1062

feat: add table demos and fix form layout styles

---

packages/field/src/index.tsx
packages/form/src/BaseForm/index.tsx
packages/form/src/layouts/QueryFilter/index.tsx
packages/table/src/Form/index.tsx
packages/table/src/Table.tsx
packages/table/src/demos/linkage_form.tsx
packages/table/src/demos/single-test.tsx
packages/utils/src/components/LabelIconTip/index.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/form/stepFormTest.test.tsx
tests/setupTests.js
tests/table/__snapshots__/column.test.tsx.snap
tests/table/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/index.test.tsx.snap
tests/table/column.test.tsx
tests/table/index.test.tsx
tests/table/search.test.tsx
tests/util.ts

close https://github.com/ant-design/pro-components/issues/1055

⚡️ feat(form): optimize query filter performance

---

packages/table/src/Form/index.tsx

重置的时候也支持search.transform
close https://github.com/ant-design/pro-components/issues/1092

💥 feat(table): onReset support search. transform

---

packages/table/src/Form/index.tsx
packages/table/src/demos/linkage_form.tsx
packages/table/src/utils.tsx

feat(table): 在columns中的fieldPorps对象中添加colSize,对应QueryFilter组件的colSize属性,以自定义查询表单项的宽度

feat(table):  add "colSize" in fieldProps within proTable's columns to customize query form item width

---

packages/layout/src/SiderMenu/BaseMenu.tsx
packages/layout/src/defaultSettings.ts
packages/layout/src/demos/MenuGroup.tsx
tests/layout/__snapshots__/demo.test.ts.snap

增加了 menu.type 的设置
- 默认值为原来的子菜单模式：`sub`
- 设置为 `group` 时，渲染为新增的 `Menu.ItemGroup`
麻烦提供下修改建议 @chenshuai2144 
close https://github.com/ant-design/pro-components/issues/1219

feat(layout): support menu type group

---

packages/provider/src/index.tsx

fix(locale): correct spelling "js-JP" to "ja-JP"

---

packages/table/src/component/ColumnSetting/index.less

280 px = antd 的 264px + padding-top 8px + padding-bottom 8px
close https://github.com/ant-design/pro-components/issues/1376

🐛 fix(table): settings max height (#1376)

---

packages/field/src/components/Money/index.tsx
packages/field/src/index.tsx
packages/utils/src/typing.ts
tests/field/__snapshots__/field.test.tsx.snap
tests/field/field.test.tsx

close https://github.com/ant-design/pro-components/issues/1544
```
valueType: {
type:"money",
moneySymbol:""
}
```

fix(filed): moneySymbol support config

---

packages/form/src/layouts/QueryFilter/index.tsx
packages/table/src/components/Form/index.tsx
packages/table/src/demos/single-test.tsx
tests/form/queryFilter.test.tsx
tests/table/__snapshots__/demo.test.ts.snap

close https://github.com/ant-design/pro-components/issues/1521

fix(form): fix defaultColsNumber no work error

---

packages/form/src/components/Submitter/index.tsx
packages/table/src/components/ColumnSetting/index.tsx
packages/table/src/demos/columnsStateMap.tsx
packages/table/src/typing.ts
tests/table/columnSetting.test.tsx

close https://github.com/ant-design/pro-components/issues/1628

feat(table): support hideInSetting props

---

packages/card/src/card.md
packages/card/src/demos/divider.tsx
packages/form/src/components/FieldSet/index.md
packages/layout/src/components/PageContainer/demos/basic.tsx
packages/layout/src/components/PageContainer/demos/fixHeader.tsx
packages/layout/src/components/PageContainer/demos/hideBreadMenu.tsx
packages/layout/src/components/PageContainer/demos/loading.tsx
packages/layout/src/components/PageContainer/index.md
packages/table/src/components/EditableTable/demos/basic.tsx
packages/table/src/components/EditableTable/demos/custom.tsx
packages/table/src/components/EditableTable/demos/real-time-editing.tsx
packages/table/src/components/EditableTable/index.md
packages/table/src/demos/ListToolBar/basic.tsx
packages/table/src/demos/ListToolBar/menu.tsx
packages/table/src/demos/ListToolBar/multipleLine.tsx
packages/table/src/demos/ListToolBar/no-title.tsx
packages/table/src/demos/ListToolBar/tabs.tsx
packages/table/src/table.md

1. 将 title 从 demo 文件迁移到  code 标签中
2. 修复 ProForm 的width 相关文档

fix: migrate title from demo to code tag & fix proform width doc

---

packages/utils/src/transformKeySubmitValue/index.ts
tests/utils/index.test.tsx

当ProFormSelect 为labelInValue模式时，transformKeySubmitValue 会去遍历React Element， 这里判断一下ReactElement 不去递归

fix: allow `labelInValue` value in form values

---

packages/table/src/components/Form/index.tsx

修复当ProTable配置type="form"时控制台报警告React does not recognize the `ignoreRules` prop on a DOM element的问题

stop passing prop ignoreRules to Form

---

packages/form/src/BaseForm/LightWrapper/index.tsx

https://github.com/ant-design/pro-components/issues/1685
现象描述：我在使用ProFormText 设置属性validateTrigger={['onBlur']} 没有生效
文件路径 BaseForm\LightWrapper\index.tsx

fix ProFormText onBlur not work

---

packages/table/src/components/ColumnSetting/index.tsx

fix(table): fix column dragger problem

---

packages/list/src/Item.tsx
packages/list/src/ListView.tsx
packages/table/src/components/Form/index.tsx
tests/list/__snapshots__/demo.test.ts.snap
tests/list/index.test.tsx

✨ feat(list): support expandIcon(#1710)

---

packages/table/src/Table.tsx

修复当Pro-table 设置search={{filterType:'light'}} options={false}且未设置headerTitle及toolbar时搜索表单不渲染的问题

fix(table): LightFilter dosn't render if options={false}

---

packages/table/src/utils.tsx
tests/table/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/editor-table.test.tsx.snap
tests/table/__snapshots__/index.test.tsx.snap

issue：ProTable Column 中未进行缩略的内容不需要展示 Tooltip #1906

feat(table): remove unnecessary tooltip

---

packages/table/src/useFetchData.tsx

fix #1923 
Remove manualRequestRef.current from useDebounceFn deps, because it may trigger an extra fetchList call.

fix(table): manualRequest may not working.

---

packages/layout/src/components/SettingDrawer/index.tsx
packages/layout/src/demos/base.tsx
packages/layout/src/layout.md

本来打算写测试用例的，但是现在配置了
```json
testURL: 'http://localhost?navTheme=realDark&layout=mix&primaryColor=daybreak&splitMenus=false&fixedHeader=true'
```
尝试了在用例里重置 URL `window.location.href = 'http://localhost'`，报错：
```shell
Error: Not implemented: navigation (except hash changes)
```
一番折腾后发现应该用不着 mock 整个 navigation，mock `useUrlSearchParams` 用到的 [API](https://github.com/rudyhuynh/use-url-search-params/blob/master/src/mockWindow.js) 应该就行了，如果需要的话我再补齐测试用例。

feat(layout): SettingDrawer support disableUrlParams

---

packages/utils/src/components/InlineErrorFormItem/index.tsx
packages/utils/src/useEditableArray/index.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/editor-table.test.tsx.snap

close https://github.com/ant-design/pro-components/issues/2128

fix(table): EditableProTable no tonumber keys

---

packages/field/src/components/Select/index.tsx

fix(select): 修复 Select 默认的 filterOption 没有忽略大小写

---

packages/layout/src/components/PageContainer/demos/basic.tsx
packages/layout/src/components/PageContainer/index.md
tests/layout/__snapshots__/demo.test.ts.snap

mofiy PageContainer basic demo and docs。 add  `editable-card`
``` tsx
tabList={[
{
tab: '基本信息',
key: 'base',
closable: false,
},
{
tab: '详细信息',
key: 'info',
},
]}
tabProps={{
type: 'editable-card',
hideAdd: true,
onEdit: (e, action) => console.log(e, action),
}}
```
tabProps | [Tabs 的相关属性](https://ant.design/components/tabs-cn/#Tabs),只有卡片样式的页签支持新增和关闭选项。使用 closable={false} 禁止关闭。

docs(compiler): add some docs for PageContainer basic demo and docs

---

packages/form/src/components/ModalForm/demos/modal-form-reset.tsx
packages/form/src/components/ModalForm/index.en-US.md
packages/form/src/components/ModalForm/index.md
tests/form/__snapshots__/demo.test.ts.snap

1. 添加了 重置 表单的 Demo
2. `自定义 Drawer 表单按钮` 标题修改为 `自定义 Modal 表单按钮`，因为例子用的 Modal Form，保持下统一
3. `自定义 Modal 表单按钮`这个 Demo 中的`自定义footer的按钮`，和另外几个例子中 英文单词带空格保持下统一
4. 英文版的文档中没有引入`自定义 Modal 表单按钮`的 Demo，补充了一下，顺便都加上了 `title`

docs: add modalForm reset demos.

---

packages/table/src/components/ColumnSetting/index.tsx

修复为 column 配置 className 时覆盖了 `.ant-pro-table-column-setting-*` 相关类名

fix(table): omit className in treeData

---

packages/field/src/components/ColorPicker/index.tsx
packages/field/src/components/Select/index.tsx
packages/form/src/layouts/QueryFilter/index.tsx
packages/table/src/components/Form/FormRender.tsx
packages/table/src/table.en-US.md
packages/table/src/table.md

```diff
<ProTable<TableListItem, Record<string, any>, 'link' | 'tags'>
+    search={{
+        className="shadow-md rounded-lg",
+    }}
columns={columns}
request={() => {
return Promise.resolve({
total: 200,
data: tableListDataSource,
success: true,
});
}}
rowKey="key"
headerTitle="自定义 valueType"
/>
```
🤚 **Don't want to use less.**
```less
.xxxx {
:global .ant-pro-table-search {
border-radius: 8px;
}
}
```

feat(table): search form support className

---

packages/field/src/components/Text/index.tsx
packages/field/src/components/TextArea/index.tsx

对于 Text 和 TextArea，应该只有 `undefined` 和 `null` 被视为空值，fixed #2240。

fix: render empty text when 'text === 0'

---

packages/field/src/components/Select/index.tsx
packages/utils/src/components/InlineErrorFormItem/index.tsx
tests/utils/index.test.tsx

- 现在只有在表单域错误时才会展示popover
- 整理了一下相关测试用例
Closes #2361

fix(utils): 优化 inline-error-form-item 的 popover 展示逻辑

---

packages/form/src/components/Radio/index.tsx

RadioGroup 没有将剩余的属性透传，导致 request、valueEnum 等属性不起作用。

fix(form): RadioGroup do not pass rest props

---

packages/field/src/components/Select/index.tsx

Select 搜索时会高亮匹配的文本，搜索时是不区分大小写的，但是高亮却会区分大小写，导致不一致。
修改前：
修改后：

fix(form): ignore case when highlighting options

---

packages/field/src/components/Select/SearchSelect/index.tsx

1. 使用 Select 的都是用 options 和 valueEnum 来配置选项的，antd 默认是根据 value 搜索的，但是真实场景中绝大部分情况下都是根据 label 来搜索的，所以将 optionFilterProp 设置为 label
2. Select 对匹配项做了高亮处理，所以回填到输入框的值也是高亮的，将 optionFilterProp 设置为 label 可以解决这个问题，而且我觉得也是比较合理的

设置 Select 的 optionLabelProp 和 optionFilterProp 的默认值为 label

---

packages/table/src/Table.tsx
packages/table/src/utils/index.ts
tests/table/filter.test.tsx

修复 ProTable 的默认排序和默认筛选值功能（#1179），用了一种似乎比较笨的方法，即 `useEffect(() => { ... }, [])` 中解析 `proColumns` 内的 default 数据，再调用 `setProSort` 和 `setProFilter`
测试发现功能可用，可作为临时的解决方案，但不知是否合理。。。
（本菜鸟想不出啥好的解决方案，希望各位大大能做后续优化）

fix(table): defaultSortOrder and defaultFilteredValue

---

packages/field/src/components/IndexColumn/index.less

Fixed index and  indexBorder column setting center invalid.
```diff
{
title: 'index',
dataIndex: 'index',
+   valueType: 'indexBorder',
+   align: 'center'
}
```

fix(field): fix index column align center

---

packages/form/src/components/FieldSet/demos/components-other.tsx
packages/form/src/components/UploadButton/index.tsx
tests/form/__snapshots__/demo.test.ts.snap

close https://github.com/ant-design/pro-components/issues/2463

fix(form): fix ProFormUploadButton  listType=picture-card style error

---

packages/form/src/components/QueryFilter/index.en-US.md
packages/form/src/form.en-US.md
packages/table/src/table.en-US.md

just fixed broken table in markdown file
**AS-IS**
| Parameters | Description | Type | Default |
| --- | --- | --- | --- | --- |
| onFinish | Callback event after form is submitted and data validation is successful, same as antd 4 `Form` component API | `(values)=>Promise<void>` | - |
| onReset | Callback for clicking the reset button | `(e)=>void` | - |
| submitter | Submitter button-related configuration | `boolean` \| `SubmitterProps` | `true` |
| dateFormatter | AutoFormat data, mainly moment forms, supports string and number modes | `string\| number \|false` | string |
| syncToUrl | sync parameters to url,url only supports string, better read [documentation](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) before using | `true` \| `(values,type)=>values` | - |
| …

just fixed broken table in markdown file

---

packages/card/package.json
packages/descriptions/package.json
packages/field/package.json
packages/form/package.json
packages/layout/package.json
packages/list/package.json
packages/provider/package.json
packages/skeleton/package.json
packages/table/package.json
packages/utils/package.json

1. 重新整理了一下 peerDependencies，现在各个包依赖的 react 版本时 16.x，如果用户安装的是 17.x，就会报下面的警告：
更改后兼容 17.x，同时也和 ant-design 保持一致。
2. pro-layout 没有使用 react-dom，所以去掉了，pro-form、pro-table、pro-utils 使用 react-dom，所以加上了 react-dom。

chore: update peerDependencies

---

packages/field/src/components/Select/SearchSelect/index.tsx
packages/field/src/components/Select/index.tsx
packages/field/src/demos/search-value.tsx
packages/field/src/field.md
packages/utils/src/components/FieldLabel/index.less
tests/field/__snapshots__/demo.test.ts.snap

close https://github.com/ant-design/pro-components/issues/2530

fix(form) : fix searchValue no work error

---

packages/utils/src/components/InlineErrorFormItem/index.tsx
tests/utils/index.test.tsx

最近用了 editable table，发现这个 popover 展示逻辑还是有问题，修正一下

fix(utils): 修复 InlineErrorFormItem 的 Popover 问题

---

packages/form/src/components/Checkbox/index.tsx
packages/form/src/components/Radio/index.tsx
packages/form/src/components/Select/index.tsx
packages/form/src/components/TimePicker/index.tsx

修复 `Checkbox` `Radio` `Select` `TimePicker` 的 `formItemProps`  类型问题

fix(form): fix formItemProps type

---

packages/form/src/components/UploadButton/index.tsx

Although listtype is provided in proformdraggerprops, if you want to set the hidden button, you need to set listtype in fieldprops additionally. This should be avoided

fix(form): ispicturecard judgment logic

---

packages/form/src/layouts/LightFilter/index.tsx

- 更多筛选里面的清除按钮，应只清除更多筛选里面的表单项。
- 清除按钮点击后，立即触发一次 onChange 回调

fix(form): should only clear collapsed fields when clear button in the more dropdown clicked

---

packages/form/src/components/List/index.tsx

fix: #2714 
`ProFormDependency`在嵌套的`ProFormList`里表现异常

fix(form): nested-list causes Dependency error

---

packages/field/src/components/Select/index.less
packages/field/src/components/Select/index.tsx

feat(form): select option height light support less(#2667)

---

packages/form/src/components/SchemaForm/index.tsx

修改了title function， 使其和文档、table columns定义一致
提交后的title ， 跟table columns 比，缺少默认使用 `<LabelIconTip label={title} tooltip={item.tooltip || item.tip} />`
这个最好是，直接调用table里的  `renderColumnsTitle`  方法， 但这样包之间就多了依赖，也可以把`renderColumnsTitle` 放到`pro-utils`。 我对代码还是不太熟悉， 只能提一下自己看到的。

fix(form):  fix SchemaForm title function

---

packages/card/src/type.ts

feat(card): card support ref(#2831)

---

packages/form/src/components/ColorPicker/index.tsx
packages/form/src/components/Digit/index.tsx

我想在 Color 组件和 Digit 组件基础上做一些封装，发现他们的  Props  都没有导出，于是修复。

chore: 增加组件 props 导出

---

packages/field/src/components/Select/SearchSelect/index.tsx

支持 autoClearSearchValue ，是否在选中项后清空搜索框，只在 mode 为 multiple 或 tags 时有效
让其保持与antd的行为一致

fix(form):  fix autoClearSearchValue not work

---

packages/form/src/components/SchemaForm/index.tsx

给 `ProFormPropsType` 添加  `ModalFormProps` 类型，用于支持 `BetaSchemaForm` 组件属性 `layoutType="ModalForm"` 的情况

fix(form): ProFormPropsType error type

---

packages/field/src/components/Select/index.tsx
packages/form/src/components/FieldSet/demos/search-select.tsx
packages/table/package.json
tests/form/__snapshots__/demo.test.ts.snap
tests/form/base.test.tsx

close https://github.com/ant-design/pro-components/issues/3082

fix(form): fix reg inclubes “(” error

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx
packages/layout/src/layout.en-US.md
packages/layout/src/layout.md

背景：
默认生成的菜单不会处理带参数的path，需通过 menuItemRender 进行自定义。处理参数需要用到 route 和 location，期望通过 props进行获取。

feat(layout): 给 menuItemRender 添加参数

---

packages/utils/src/components/LabelIconTip/index.less

修复 column 配置了 tooltip 时，align 无效的问题

fix(table): fix table align with tooltip

---

packages/descriptions/src/descriptions.en-US.md
packages/descriptions/src/descriptions.md
packages/table/src/Table.tsx
packages/table/src/components/EditableTable/index.en-US.md
packages/table/src/components/EditableTable/index.md
packages/utils/src/useEditableArray/index.tsx

- feat(table): table support editable.formProps
- update api doc
close https://github.com/ant-design/pro-components/issues/3359

 feat(table): table support editable.formProps

---

packages/utils/src/typing.ts

问题：
在ProTable->ProColumns中的fieldProps属性支持多个input支持的属性，但缺失类型描述，导致开发时IDE无法智能提示，降低效率。
问题解决：
增加相关属性类型描述

feat(table): 增加在ProTable中的ProColumns中fieldProps支持的属性类型描述

---

packages/descriptions/src/useFetchData.tsx
packages/table/src/typing.ts

接口返回中有可能不包括 `data`，同时又没自定义 requestInterceptors 时，`data` 应和 ProTable 中的逻辑一致：非必需属性。

fix(descriptions): RequestData 类型优化

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx
packages/layout/src/defaultSettings.ts
packages/layout/src/demos/AlwaysDefaultOpenAllMenu.tsx
packages/layout/src/layout.md
tests/layout/defaultSettings.ts
tests/layout/index.test.tsx

* 解决ProLayout侧边栏菜单折叠按钮切换之后，会收起所有子菜单，此时defaultOpenAll相当于失效了，菜单较多时，用户需要手动一个个展开很不方便
* 在保持默认行为不变的情况下，增加ignoreFlatMenu配置，控制defaultOpenAll折叠后继续生效

fix(layout): 解决侧边栏菜单折叠按钮切换之后，defaultOpenAll失效

---

packages/form/src/components/ModalForm/demos/modal-form-reset.tsx

the first ModalForm use incorrect formRef to cause reset form failed.

fix(form): fix incorrect formRef in demo code

---

packages/layout/src/components/PageContainer/index.md

fix(ProLayout): headerContentRender example function.
- 问题页面链接(该页面最底部位置)：https://procomponents.ant.design/components/page-container/#api
- 问题页面位置：PageContainer - 页容器 --> ProBreadcrumb -->  示例代码
- 问题描述：箭头函数少了一个左括号

fix(ProLayout): headerContentRender example function.

---

packages/table/src/components/DragSortTable/index.tsx
packages/table/src/demos/drag-sort-table.tsx
packages/table/src/table.md
packages/table/src/utils/useDragSort.tsx
tests/table/__snapshots__/demo.test.ts.snap

Dragsorttable should be sorted based on the rowkey attribute as the unique value. If it is based on index, the data source has to add this attribute before passing in data, which will be very cumbersome。
DragSortTable 应该是基于rowKey属性作为唯一值进行排序的，如果基于index，那么数据源不得不在传入数据之前添加该属性，这样会显得很繁琐。

feat(table): Dragsorttable should be sorted based on the rowkey

---

packages/form/src/components/List/index.tsx

close https://github.com/ant-design/pro-components/issues/3628

fix(form): fix form list preserve problem

---

packages/form/src/layouts/StepsForm/index.tsx
tests/form/__snapshots__/demo.test.ts.snap

在我们项目中出现 onFinish 回调里始终只能拿到初始 state 的 bug，经排查发现是 useCallback 打包后丢失了 props 依赖，导致组件拿到的只是首个 onFinish，猜测是打包工具某一环的策略导致的。
_不过 props 也不应该成为直接依赖，否则和写不写应该都一样吧，另一个项目却没此问题 。_

fix(form): 完善 StepsForm 的 useCallback 依赖，修复可能导致的打包丢失依赖问题

---

packages/utils/src/useEditableArray/index.tsx

**初始**
**编辑中**
**取消编辑，再次点开编辑**
虽然使用者可以主动传入form实例手动重置。但是理想情况，应该组件可以自动表单全部重置，或者全部不重置。现改成可全部重置

fix(table): 取消编辑行后表单未能全部重置

---

.umirc.js

Improve docs resolve config to avoid generate duplicated routes, finally make the search results broken.
Close #3968

chore: avoid resolve docs repeatedly

---

packages/field/src/components/Select/index.tsx

原参数名为：keyWords
变更来源：https://github.com/ant-design/pro-components/commit/887e6541dae8e614789e651c74b32abc875e83e7#diff-904c0f9f1e7c6adc95255c00b992b0756aac8320941d6af71d55b9e1346bc922L304

还原 select request 方法参数 keyWord 为 keyWords

---

packages/layout/src/layout.md

我在开发过程中，使用到了ProLayout，期望对其中的Breadcrumb组件分隔符做个性化设置，但没有在ProComponents文档中看到类似Ant Design文档中Breadcrumb组件的separator配置项
经过查看，BasicLayout.d.ts中已经存在了对Breadcrumb组件的breadcrumbProps设置，但文档中没有体现出来

feat: pro-layout已支持传入props到breadcrumbProps，但文档中没有体现

---

packages/table/src/components/ColumnSetting/index.tsx

修改ColumnSetting中selectedKeys变量的命名错误，并修改注释

refactor: 💡 修改ColumnSetting中selectedKeys变量的命名错误，并修改注释

---

packages/layout/src/layout.en-US.md

- En-US docs for Layout has some issues.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/11713395/143482043-d55d5327-2446-4b11-826b-015a4e0f3ca9.png)|![image](https://user-images.githubusercontent.com/11713395/143483720-97e523b3-ccaf-4236-89b3-a01744bbd978.png)|
|![image](https://user-images.githubusercontent.com/11713395/143482094-306c28b0-dbba-4964-84ad-338076257806.png)|![image](https://user-images.githubusercontent.com/11713395/143483933-1a019667-65c2-49f1-896b-d80c27210481.png)|
|![image](https://user-images.githubusercontent.com/11713395/143483623-12195845-2f51-4af4-992b-18e18092d52a.png)|![image](https://user-images.githubusercontent.com/11713395/143484018-2c7c9a46-2fc1-469a-924a-2e5863dab5e7.png)| …

fix:docs: en-US docs for Layout section

---

docs/playground/curd.playground.md
docs/playground/pro-descriptions.playground.md
docs/playground/pro-form.playground.md
docs/playground/pro-layout.playground.md
docs/playground/pro-table.playground.md

Fix the following error when building docs with ssr mode:
```bash
Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems
```

docs: correct nav path for playground

---

packages/layout/src/WrapContent.tsx
packages/layout/src/demos/top-breadcrumb.tsx
packages/layout/src/layout.en-US.md
packages/layout/src/layout.md
packages/utils/src/useEditableArray/index.tsx

给一个时机关闭默认错误边界，现在有一个使用 [sentry](https://docs.sentry.io/platforms/javascript/guides/react/components/errorboundary/) 的场景，sentry 错误边界作为父组件存在，error event 会被默认错误边界拦截
```jsx
import React from "react";
import * as Sentry from "@sentry/react";
<Sentry.ErrorBoundary fallback={<p>An error has occurred</p>}>
<ProLayout />
</Sentry.ErrorBoundary>;
```

feat: disable default error boundary

---

packages/layout/src/components/PageContainer/index.tsx

thus, the add icon is shown when tabProps: {type: 'editable-card'} and tablist is empty

fix(layout):should show tabs when tablist is an empty array

---

packages/form/src/layouts/LightFilter/index.tsx

fix(form): 重新给LightFilter内的表单项指定属性不生效🐛[BUG] #4366

---

packages/table/src/table.en-US.md
packages/table/src/table.md

ProTable component documentation typo

fix: ProTable documentation typo 

---

packages/form/src/components/DateRangePicker/index.tsx

fix(form): DateRangePicker in LightFilter format is always set to YYYY-MM-DD

---

packages/field/src/components/Select/index.tsx

fix field select issue that number 0 as option value not render its label while options from request method. BTW, save value as map key to avoid number type convert to string as object key.

fix(form): render option failed while key is number 0.

---

packages/utils/src/parseValueToMoment/index.ts

moment传入时间戳（Number）情况下，即使传入format也要忽略第二个参数
> moment解析时间戳如果传入第二个参数，有的成功有的失败
比如文档Demo就出现了如下情况：

fix(utils): timestamp in moment no need pass second param

---

packages/table/src/utils/index.ts

修复 ProTable 的 reload 方法在传入 resetPageIndex 参数时无效的问题。

fix(table): fix the param resetPageIndex is invalid in ProTable's method reload.

---

packages/utils/src/components/InlineErrorFormItem/index.tsx

The className 'ant-form-item-with-help' is hardcode here, when use the prefixCls in ConfigProvider, will let the form can not show the error message.

fix: support using prefixCls from ConfigProvider in <InlineErrorFormItem />

---

packages/field/src/components/Text/index.tsx

fixes: #4413 and optimize code

fix(field): 🐛 Cannot read properties of undefined (reading 'autoFocus'

---

packages/form/src/components/ModalForm/demos/drawer-form.tsx
packages/form/src/layouts/DrawerForm/index.tsx
tests/form/drawerForm.test.tsx

fixes: #4418
DrawerForm中设置destroyOnClose=true时，无法获取表单实例，因为visible === false不渲染表单

fix(form): 🐛 DrawerForm cannot get form instance by formRef

---

packages/form/src/components/TimePicker/index.tsx

close https://github.com/ant-design/pro-components/issues/4425

fix(form): fix datePick typing error

---

packages/form/package.json
packages/form/src/components/SchemaForm/index.tsx

在`SchemaForm`中使用`dependency`如果忘记设置/不设置正确`fieldProps.name`会直接crash。
这边添加warning且不展示没有设置name的组件

fix(form): SchemaForm dependency add warning message

---

packages/field/src/index.tsx
packages/form/src/BaseForm/createField.tsx
packages/form/src/components/UploadDragger/index.tsx
packages/provider/src/index.tsx
packages/table/src/components/EditableTable/demos/basic.tsx
packages/utils/src/typing.ts
tests/field/field.test.tsx
tests/table/__snapshots__/demo.test.ts.snap

fix: #4487
当设置readonly为true时
保持原来的逻辑
优先从fieldProps?.value获取值，保证在只读的表单操作里依然能展示最新的值
现实现方式调整了判断readonly===true设置mode=true的位置

fix(form):  readonly form will not render the latest value

---

packages/card/src/components/CheckCard/demos/avatar.tsx
packages/card/src/components/CheckCard/demos/basic.tsx
packages/card/src/components/CheckCard/demos/compose.tsx
packages/card/src/components/CheckCard/demos/custom.tsx
packages/card/src/components/CheckCard/demos/defaultChecked.tsx
packages/card/src/components/CheckCard/demos/description.tsx
packages/card/src/components/CheckCard/demos/disabled.tsx
packages/card/src/components/CheckCard/demos/extra.tsx
packages/card/src/components/CheckCard/demos/form.tsx
packages/card/src/components/CheckCard/demos/grid.tsx
packages/card/src/components/CheckCard/demos/group.tsx
packages/card/src/components/CheckCard/demos/image.tsx
packages/card/src/components/CheckCard/demos/list.tsx
packages/card/src/components/CheckCard/demos/loading.tsx
packages/card/src/components/CheckCard/demos/multiple.tsx
packages/card/src/components/CheckCard/demos/single.tsx
packages/card/src/components/CheckCard/demos/size.tsx
packages/card/src/components/CheckCard/demos/title.tsx

移除无用的 uuid frontmatter，早期海兔的遗留产物，用不到了；另外发现 pro-components 的 precommit 会强行把注释格式化成 `/** balabala */` 的单行形式，这样会导致 demo 源码中的 frontmatter 失效，这个 PR 先 `--no-verify` 绕过了， @chenshuai2144 看看怎么处理比较好

chore(card): remove useless frontmatter from demos

---

packages/form/src/components/List/index.less

fix: ProFormList should show label when  form layout is horizontal

---

packages/form/src/components/Dependency/index.tsx
packages/utils/src/transformKeySubmitValue/index.ts
tests/utils/index.test.tsx

如果监听的内容为数组，比如ProFormCascader组件，监听的内容会从数组转成对象。["A", "B"] -> {0: "A", 1: "B"}

fix(form): dependency transform from Array to Object

---

packages/form/src/components/List/index.less

当ProForm外层统一设置`<ConfigProvider getPopupContainer={(e)=>e.parentElement()}></ConfigProvider> `，鼠标hover后，多了一个div，导致`&-action-icon:last-child {margin-right: 0;}`失效，出现按钮抖动

fix(form): proformlist style bug

---

packages/table/src/components/EditableTable/index.en-US.md
packages/table/src/components/EditableTable/index.md

docs(EditableTable):  Fix the description of EditableTable `position`.

---

packages/form/src/layouts/QueryFilter/index.tsx

原有的设计，强依赖了span的属性顺序，如果顺序不对，比如：
`{
xxl: 8,
xs: 1,
sm: 2,
md: 3,
lg: 4,
xl: 6,
}`
就会一直使用xxl的值

fix: 修复queryFilter响应式会受span的属性顺序问题

---

packages/layout/src/components/PageContainer/index.tsx

说明：
1. 合并 ProLayout 和 PageContainer 的 waterMarkProps，已达到复用某些 props 的目的，~~而不是直接用 PageContainer 替换 ProLayout 的 waterMarkProps~~
2. 优先级：PageContainer > ProLayout

fix(PageContainer): fix the logic of `WaterMark` props

---

packages/form/src/layouts/LoginForm/index.tsx

修复`<LoginForm submitter={{}} ...>`导致LoginForm的submitter默认设置无效。
LoginForm的proFormProps.submitter已经在前面与submitter的默认设置合并了，这里`{...proFormProps}`会把合并好的submitter完全覆盖掉，失去LoginForm默认行为的意义。

fix(form): submitter default config overwritten by proFormProps.submitter

---

packages/form/src/BaseForm/createField.tsx
packages/form/src/components/SchemaForm/valueType/field.tsx

没有更好的办法减少renderFormItem执行的次数了
删掉之前支持renderFormItem返回false|null|undefined不渲染表单的代码
优化dom判断

fix:(form)  remove unused code of renderFormItem

---

packages/form/src/components/List/index.tsx

说明：
需求：在使用嵌套 ProFormList 时，拿到 `子List` 对应的是哪个 `父List`。
通过 name 属性，可以拿到对应 form 字段的值。

feat(form): add `name` prop to `itemRender`

---

packages/form/package.json
packages/form/src/layouts/DrawerForm/index.tsx
packages/form/src/layouts/ModalForm/index.tsx
tests/form/drawerForm.test.tsx
tests/form/modalForm.test.tsx

fix #4763
简化整体实现
让Modal和Drawer 处理 forceRender 和 destoryOnClose 即可，不用麻烦自己，怎么简单怎么来

fix(form):  improve ModalForm and DrawerForm performance

---

packages/form/src/components/SchemaForm/demos/customization-value-type.tsx
packages/utils/src/index.tsx
packages/utils/src/types/index.ts
packages/utils/src/typing.ts

改进类型提示，支持外部使用如下代码添加新的valueType支持，用于用户使用valueTypeMap导致类型不匹配等问题
```typescript
declare module '@ant-design/pro-utils' {
interface ProFieldValueTypeWithFieldProps {
newType: Record<string, any>
}
}
```

feat(form): improve type and support external override type

---

packages/layout/src/components/GlobalHeader/index.less
packages/layout/src/components/GlobalHeader/index.tsx

UI(layout): 完善 GlobalHeader RTL 支持

---

packages/form/src/layouts/DrawerForm/index.tsx
packages/form/src/layouts/ModalForm/index.tsx
tests/form/drawerForm.test.tsx
tests/form/modalForm.test.tsx

fix: #4832
fix: #4823
造成了 breaking change，还是不要默认设置为好，和antd保持一致
https://github.com/ant-design/pro-components/pull/4773#issuecomment-1059988527 老代码适配应当由用户升级版本后自行调整代码做适配

fix: ModalForm and DrawerForm remove default value of forceRender

---

packages/table/src/Table.tsx
packages/table/src/components/EditableTable/index.tsx
packages/table/src/utils/cellRenderToFromItem.tsx
packages/table/src/utils/columnRender.tsx
tests/table/editor-table.test.tsx

fix (Form): passing `formItemProps` and `fieldProps` as functions did not work when using `EditableTable` in `Form`

---

packages/table/src/Table.tsx
packages/utils/src/index.tsx
packages/utils/src/useEditableArray/index.tsx
tests/table/editor-table.test.tsx

说明：
当前版本存在的问题：newRecordType 必须是 dataSource，parentKey 才会生效
```ts
actionRef.current?.addEditRecord(
{
id: (Math.random() * 1000000).toFixed(0),
},
// 此处，newRecordType 必须是 dataSource，parentKey 才会生效
{ parentKey: record.id, position: 'top', newRecordType: 'dataSource' },
)
```
该 PR 为 newRecordType 为 `'cache'`（默认值），增加了 parentKey 支持，可以插入到指定节点下

feat(ProTable): `newRecordType: cache` support parentKey

---

packages/form/src/components/SchemaForm/demos/dynamic-rerender.tsx
packages/form/src/components/SchemaForm/index.en-US.md
packages/form/src/components/SchemaForm/index.md

fix: #4867
我现在知道为什么要renderFormItem返回false，null，undefined时不渲染列了，实现的时候应该还没有valueType: dependency所以这种方式实现动态渲染列的，不过很明显不是一种好的方案，renderFormItem现在每次render都需要执行两次才能实现这个方案
现在先把示例和文档先改了，等之后SchemaForm正式版的时候应该把这个砍了，用dependency去控制重渲染，或者hideInForm接受一个函数返回一个formInstance控制是否渲染

docs: Update the recommended way of dynamic rendering

---

packages/utils/src/useEditableArray/index.tsx
tests/table/editor-table.test.tsx

修复：
- 新添加一行数据，newRecordType 为 `cache`（默认值）时，保存后新生成数据层级错误问题
- 修复 newRecordType 为 `cache`（默认值）时，editable 的 onSave 拿不到 newLineConfig 参数的问题

fix(ProTable): fix actionSaveRef logic when add new line

---

packages/table/src/Table.tsx
packages/table/src/utils/cellRenderToFromItem.tsx
packages/table/src/utils/columnRender.tsx
packages/table/src/utils/genProColumnToColumn.tsx
tests/table/editor-table.test.tsx

fix: #4854
更好的解决方案应该需要在Antd Table执行render时提供是否为sub-column及传递namepath过来
现在的解决方案对每个子项做了一个遍历缓存子列此时的name path位置，不是很棒的解决方案

fix(table): Incorrect value of sub-column when using EditableTable in Form

---

packages/table/src/components/ColumnSetting/index.tsx
packages/table/src/components/ToolBar/index.tsx
packages/table/src/demos/columns-setting-custom-icon.tsx
tests/table/columnSetting.test.tsx

The idea behind this PR is be able to to control "icon" of column setting - and not only the tooltip massage. 
In am planning to check settings section to make it more flexible and eg. to allow user change order of table settings displayed

feat(table): customize columnSetting icon

---

packages/form/src/layouts/QueryFilter/index.tsx
packages/layout/src/components/SettingDrawer/index.tsx
tests/form/queryFilter.test.tsx

此为缺少收起按钮
此为没收起完整
具体是判断表单首项是否占满整行，以及用每个表单项的colSize来判断是否超出区域
fix:#2642

🐛 fix(form): fix 表单在colSize!==1下展示异常

---

packages/field/src/components/DigitRange/index.tsx
packages/form/src/components/FieldSet/index.md
tests/field/field.test.tsx

```tsx
placeholder={['Min', 'Max']}
```

fix(digitRange): fix array placeholder

---

packages/form/src/index.tsx

the master branch missed the export of ProFormTreeSelect and may lead to not found error while using ProFormTreeSelect.

fix(form): add missed ProFormTreeSelect to the form export

---

packages/table/package.json

Fixes #5273 by up-pinning @babel/runtime to 7.18.0
修复 pro-table #5273 中的问题，限制@babel/runtime 到 7.18.0 及以上

fix(table): #5273 for pro-table

---

packages/utils/src/useEditableArray/index.tsx
tests/table/editor-table.test.tsx

I had issues creating nested child rows in `EditableProTable` using `RecordCreator`. My experience was similar to #3342, #3914, #3881, and #4246.
Specifically, I saw a console error message thrown by [addEditRecord](https://github.com/ant-design/pro-components/blob/b076d289bee24bc0812831c51a7c7d2f3951b7b5/packages/utils/src/useEditableArray/index.tsx#L633).
```
can't find record by key xxxxx
```
After some investigation, it occurs to me that `dataSourceKeyIndexMapRef` does not contain keys from nested child rows. This PR fixes the issue and allows me to add nested child rows in `EditableProTable`.

fix(table): useEditableArray fix child record traversal

---

packages/form/src/layouts/LoginForm/index.tsx
packages/form/src/layouts/LoginFormPage/index.tsx
tests/form/loginForm.test.tsx

close https://github.com/ant-design/pro-components/issues/5308

fix(form): fix loginForm no support submitButtonProps error

---

packages/form/src/BaseForm/BaseForm.tsx

validateFieldsReturnFormatValue 应该总是返回对象
```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'start_date')
_callee$
.bi-v3/src/pages/currency/get/index.tsx:117:22
114 |   title: '获取总数',
115 |   dataIndex: 'total_num',
116 | },
> 117 | ...dates(params.start_date, params.end_date).map((date) => ({
|                ^  118 |   title: date,
119 |   dataIndex: date,
120 | })),
View compiled
```
```
const onFinish = async () => {
actionRef.current?.reset?.()
const params = await formRef.current?.validateFieldsReturnFormatValue?.()
setColumns([
{
title: '获取途径',
dataIndex: 'key',
},
{
title: '获取总数',
dataIndex: 'total_num',
},
...dates(params.start_date, params.end_date).map((date) => ({
title: date,
dataIndex: date,
})),
])
run(params)
}
```

fix(form): validateFieldsReturnFormatValue 可能为undefined

---

packages/form/src/BaseForm/BaseForm.tsx
tests/form/base.test.tsx

目前设置 syncToUrl 为true时, 在页面回显时,不会使用url上的参数来拉去页面数据, 不满足分享url的需求, 加入一个prop, 用于满足该场景

feat(form): add syncToUrlAsImportant prop

---

packages/table/src/Table.tsx
packages/table/src/table.en-US.md
packages/table/src/table.md

revalidateOnFocus 这个属性在 @ant-design/pro-table@2.75.0 的默认值根本没有被置为 false。今天升级了版本直接被拉去祭天了

fix(table): default close revalidateOnFocus

---

packages/form/src/components/QueryFilter/index.en-US.md
packages/form/src/components/QueryFilter/index.md
packages/form/src/layouts/QueryFilter/index.tsx

Props:
```jsx
<QueryFilter preserve={ false } />
```
Before:
After:

 fix(form): fix col not hidden when QueryFilter preserve is set to false

---

packages/provider/src/locale/pt_BR.tsx

fix the translation of the word `items` to `itens`, in Portuguese BR, it is only allowed to use the letter `m` before the consonants `p` and `b`.

fix(provide): Translation of the `items` (PT-Br)

---

docs/schema.md
packages/form/src/form.md

当进入架构设计  => 通用配置总览 => 滚动到远程数据及以下时 代码片段会被执行，而丢失了import React from 'react', 会找不到react.createElement, 报错： `react_devtools_backend.js:4026 TypeError: Cannot read properties of undefined (reading 'createElement')
`

docs: 修复文档内ts代码被误执行，导致页面白屏

---

packages/table/src/components/EditableTable/index.tsx

在 360 浏览器不支持 at 语法， 导致调用 setRowData 方法报错

fix(table): method coverRowKey 关于 at 兼容性问题修复

---

package.json

https://github.com/ant-design/pro-components/issues/5380
the online demo dependencies error was fixed in https://github.com/umijs/dumi/pull/1109

fix: upgrade dumi to fix the online Demo dependencies error

---

packages/table/src/demos/dynamic-settings.tsx

https://procomponents.ant.design/playground/pro-table/
fix: 表单配置中-编辑查询文案无效

docs(protable): fix demo

---

packages/form/src/components/Group/index.md

ProFormList Api文档itemRender 少左括号
issus: fix https://github.com/ant-design/pro-components/issues/5553

fix: ProFormList Api文档itemRender 少左括号

---

packages/form/src/layouts/StepsForm/index.tsx
tests/form/stepFormTest.test.tsx

你好～
因为需要用到`StepsForm`在读source code的时候发现`unRegForm`生成新的`formArray`的逻辑不正确所以提交了这个PR。
这个bug会造成Step隐藏的时候把所有其他的Step清除。
https://codesandbox.io/s/steps-form-dynamic-f20g0x?file=/App.tsx
谢谢！

fix(form):Stepsform not properly unregister form

---

packages/table/src/Table.tsx
packages/utils/src/useEditableArray/index.tsx
tests/table/editor-table.test.tsx

When creating nested child rows in EditableProTable, if not set position to top and not set expandable:{childrenColumnName:'children'} in cache record type, the nested children (at least in level 2) can not be add correctly
related issues:clsoe #5566

fix(table): useEditableArray fix nested children can not be add when position is not top and expandable.childrenColumnName isundefined

---

packages/form/src/layouts/DrawerForm/index.tsx
packages/form/src/layouts/ModalForm/index.tsx

fix #5516
曾经 #3739 特意考虑了这个问题，默认是不重置表单，不知道出于什么考虑又取消了，先帮忙看一看这样改对不对，谢谢！

fix(form): destroyOnClose does not work as expected 

---

packages/layout/src/components/WaterMark/index.tsx
tests/layout/__snapshots__/demo.test.ts.snap
tests/layout/__snapshots__/waterMark.test.tsx.snap

第一次生命周期内，base64Url为空字符串，水印组件引用了空图片，实际上发起了一个location.href的多余请求

fix(layout): 水印导致页面发起404请求

---

packages/utils/src/useEditableArray/index.tsx
tests/table/editor-table.test.tsx

问题: 之前的PR #5643 修复了多层嵌套结构(存在2级及以上)情况下在不做额外配置情况下无法正确添加子节点,目前可以正常添加但是非根节点下添加子节点只会增加到同级的顶端, 也就是无论是否配置top都是top方向

fix(table): editable table 增加children时没有按照position方向增加

---

packages/table/src/components/EditableTable/index.tsx
tests/table/editor-table.test.tsx

fix(table): 解决 EditableTable 与 ProForm 配合使用时初始化数据也会触发 onValuesChange 的问题

---

packages/field/src/components/TimePicker/index.tsx

```ts
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```
ref: https://github.com/ant-design/pro-components/issues/5870

fix(field): fix forward ref of the time-picker

---

packages/layout/src/components/GlobalHeader/style.ts
packages/layout/src/layout.en-US.md
packages/layout/src/layout.md

主要是为了改小屏幕下的展开收起菜单按钮的颜色
不好意思，之前 https://github.com/ant-design/pro-components/pull/5889 姿势不对。直接用 `colorHeaderTitle`。
另外这个字段 `colorMenuBackground` 是不是应该改为 `colorBgMenu` 更合适。

fix(layout): header add `colorHeaderTitle` token

---

packages/layout/src/components/GlobalHeader/style.ts
packages/layout/src/components/TopNavHeader/index.tsx
packages/layout/src/layout.en-US.md
packages/layout/src/layout.md

before
after
<details>
<summary><h3>Token Config</h3></summary>
<code>
<pre>
{
"fixSiderbar": true,
"layout": "top",
"navTheme": "light",
"contentWidth": "Fixed",
"colorPrimary": "#722ED1",
"siderMenuType": "sub",
"token": {
"colorTextAppListIcon": "#fff",
"colorTextAppListIconHover": "#ffc400",
"colorBgAppListIconHover": "rgba(255,255,255,0.15)",
"sider": {
"colorMenuBackground": "rgb(114, 46, 209)",
"colorBgMenuItemCollapsedHover": "#ffc400",
"colorBgMenuItemCollapsedSelected": "#555",
"colorMenuItemDivider": "rgba(255,255,255,0.15)",
"colorBgMenuItemHover": "rgba(255,255,255,0.2)",
"colorBgMenuItemSelected": "#491293",
"colorTextMenuSelected": "#ffaa00",
"colorTextMenuActive": "#ffc400",
"colorTextMenu": "#fff",
"colorTextMenuSecondary": "#fff"
},
"header": {
"colorHeaderTitle": …

fix(layout): submenu support token `layout=top` 

---

packages/card/src/components/Card/style.ts

fix(card): fixed col width precision lose

---

packages/list/src/index.tsx

fix(list): 修复类型问题：未将RecordType的泛型传入meta中

---

packages/table/src/utils/columnRender.tsx

错位：
```tsx
const Component = () => (
<EditableProTable
columns={[
{
title: '操作',
valueType: 'option',
render: () => [<Link key="edit">编辑</Link>, <Link key="delete">删除</Link>],
},
]}
editable={{ actionRender: (record, config, actions) => [actions.save, actions.cancel] }}
/>
);
```
---
对齐：
```tsx
const Component = () => (
<EditableProTable
columns={[
{
title: '操作',
valueType: 'option',
render: () => [<Link key="edit">编辑</Link>, <Link key="delete">删除</Link>],
},
]}
editable={{ deleteText: <></> }}
/>
);
```

fix(table): EditableProTable编辑模式下与只读模式下的操作按钮对齐问题

---

packages/form/src/components/List/ListItem.tsx
tests/form/__snapshots__/demo.test.ts.snap

```tsx
<ProFormList
name={["default", "users"]}
isValidateList
alwaysShowItemLabel
containerClassName={'containerClassName'}
containerStyle={{marginInlineStart: '50px'}}>
....
</ProFormList>
```
目前是直接在最外层结构显示了

fix(form): 修复ListItem自定义样式和样式名称不生效的BUG

---

packages/form/src/layouts/DrawerForm/index.tsx

- 删除重复冗余代码，该逻辑在`drawerOpenProps`中已有更优实现：

feat(form): remove redundant code

---

packages/field/src/components/Segmented/index.tsx

Segmented上没有这个属性呀：https://ant.design/components/segmented-cn/#API

fix(segmented): remove invalid property `allowClear`

---

packages/form/src/components/Group/index.en-US.md
packages/form/src/components/Group/index.md
packages/form/src/components/List/ListItem.tsx

`action.remove` 方法参数应与源码中一致为 `field.name`。
按照当前文档参数为 `field.key`，删除操作后，再次添加，删除条目不正确
源码如下
1. 创建若干条item，并填写值
2. 点击第二条“delete by key”
3. 新增一条
4. 点击最后一条“delete by key”，删除失败。删除其他条目，删除条目不正确。
5. 点击“delete by name”，删除正确
https://codesandbox.io/s/proform-list-forked-z8osfh?file=/App.tsx
文档中将该示例改为 `action.remove(field.name)`

doc: Correct the remove method parameters in document

---

packages/field/src/components/Segmented/index.tsx
packages/layout/src/components/PageContainer/demos/fixHeader.tsx
packages/layout/src/components/PageContainer/index.tsx
packages/layout/src/components/PageContainer/style/index.ts
packages/layout/src/components/PageHeader/index.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/layout/__snapshots__/demo.test.ts.snap
tests/layout/__snapshots__/index.test.tsx.snap
tests/layout/__snapshots__/pageContainer.test.tsx.snap
tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap
tests/table/dynamic-columns-state.test.tsx
tests/table/editor-table-two.test.tsx

fix(Layout): 修复 PageContainer 设置 fixedHeader 属性后，样式 ant-pro-page-container-warp 未生效问题

---

packages/descriptions/src/demos/columns.tsx
packages/field/src/components/Money/index.tsx
packages/layout/src/components/SiderMenu/BaseMenu.tsx
packages/provider/src/index.tsx
packages/table/src/components/EditableTable/index.tsx
tests/descriptions/__snapshots__/demo.test.ts.snap

fix(form): 金额格式化支持负数形式展示

---

packages/field/src/components/Digit/index.tsx

fix(form): ProFormDigit value will fixed when not set precision

---

packages/utils/src/useEditableArray/index.tsx
packages/utils/src/useEditableMap/index.tsx
tests/table/editor-table.test.tsx

`editable`对象`actionRender`方法的`defaultDoms`参数对每个action按钮都扩展了一个ref对象，可以让调用者以编程的方式直接触发对应的action。
相较于新的api，调用者只能调用config对象的`onSave/onDelete/onCancel`方法，但需要传递很多参数(尤其是onSave)，需要了解很多内部知识，自己需要用form来获取整个编辑行的数据，门槛太高。而新的方法，内部获取所有信息，无需传参。
如果页面上存在多个tab，或者编辑表格会动态显示/隐藏，如果编辑行没有保存就被隐藏了，那最后保存表单时这一行就会丢失掉。借助新方法，调用者可以在隐藏表格之前自动保存编辑行，避免数据丢失的问题。
* bad(图)
* good(图)

feat(table): add new api actionRef.saveEditable

---

packages/layout/src/components/SettingDrawer/ThemeColor.tsx
packages/layout/src/components/SettingDrawer/index.tsx

现象：当前SettingDrawer内的ThemeColor组件在遍历colorList时查找的是/packages/layout/src/locales/zh-CN文件里的key作为tooltip的值，如果自定义colorList则tooltip会不显示
[https://github.com/ant-design/ant-design-pro/issues/10126](url)
改进的方案：如果colorList的item传入title则会作为tooltip的value显示
```js
import React, {useEffect} from 'react';
import ProLayout, { SettingDrawer } from '@ant-design/pro-layout';
const Pro = () => {
const [opts, setOpts] = useState({});
const colorList = [
{key: 'ifss-default', color: '#4684ff', title: '自定义提示'},
{key: 'ifss-daybreak', color: '#1890ff'},
{key: 'ifss-dust', color: '#F5222D'},
{key: 'ifss-volcano', color: '#FA541C'},
{key: 'ifss-sunset', color: '#FAAD14'},
{key: 'ifss-cyan', color: '#13C2C2'},
{key: 'ifss-green', color: '#52C41A'},
{key: 'ifss-geekblue', color: '#2F54EB'},
{key: 'ifss-purple', color: …
```

feat(SettingDrawer): 支持 colorList 传 title 属性作为 tooltip

---

packages/layout/src/components/WaterMark/index.tsx

fix(WaterMark): fontSize过大导致多行文字重叠

---

packages/table/src/components/DragSortTable/index.tsx

修复 DragSortTable 支持 request 时引入的 bug。
bug 描述：
useMergedState 缓存了 props.dataSource 第一次传入的值，后续 dataSource 值再次改变时 mergedDs 仍然是首次缓存的值，导致新的 dataSource 未能正确渲染。
期望：
当传入 dataSource（dataSouce 不是 null / undefined 时） 时优先使用 dataSource 进行数据渲染。

fix(table): 修复 DragSortTable 的 dataSource 值变更后未正常渲染

---

packages/field/src/components/Select/index.tsx
packages/form/src/components/FieldSet/demos/components-other-readonly.tsx
tests/field/__snapshots__/demo.test.ts.snap
tests/form/__snapshots__/demo.test.ts.snap
tests/table/__snapshots__/demo.test.ts.snap

fix(field): 只读模式下的 ProFormSelect 应该支持wrap

---

packages/table/src/utils/useDragSort.tsx

`useDragSort` hook 每次执行会创建新的tbody和tr组件，导致table内容重建。
同时 `SortableItem` 和 `SortableContainer` 组件没有任何副作用，可以提升到模块根部，防止不必要的重建。

fix(dragsortable): Sortable 组件提取到外部防止不必要的页面重建

---

packages/field/src/components/Select/SearchSelect/index.tsx

修复SearchSelect组件在设置了showSearch和 多选模式下，当搜索并选中后，搜索的文字没有清空的问题
close  #6258

fix(form): 修复SearchSelect组件在设置了showSearch和 多选模式下，当搜索并选中后，搜索的文字没有清空的问题

---

packages/table/src/Table.tsx

问题导致 preserveSelectedRowKeys 开启后无法正常在 tableAlertOptionRender 和
toolBarRender 中获取到 selectedRows ,而 selectedRowKeys 可以正常获取

fix(table): 修复table使用后端分页时（频繁变化dataSource场景）多选功能 selectedRow 缓存丢失

---

packages/card/src/components/Statistic/index.tsx

修复 statistic 元素中 hashId 在 trend 属性下不生效的问题，导致对应的 css 样式失效
详情见此问题：https://github.com/ant-design/pro-components/issues/6186#issuecomment-1333802449

fix(card): 修复 statistic 元素中 hashId 在 trend 属性下不生效的问题

---

packages/layout/src/components/PageContainer/index.tsx

Signed-off-by: 周立华 <zhoulihua.rd@gmail.com>
fix(PageContainer): 修复PageContainer设置为fixedHeader，内容滚动的时候Title抖动问题
bugID：#6329

fix(layout): 修复PageContainer设置为fixedHeader，内容滚动的时候Title抖动问题

---

packages/field/src/components/Select/LightSelect/index.tsx

修复 ProFormSelect 在LightFilter 中自定义过滤无效.
close #6309

fix(field): 修复 ProFormSelect 在LightFilter 中自定义过滤无效

---

packages/layout/src/components/SiderMenu/SiderMenu.tsx
packages/layout/src/demos/theme.tsx
packages/layout/src/layout.en-US.md
packages/layout/src/layout.md
packages/provider/src/typing/layoutToken.ts

#6131 默认的背景色不能覆盖绝大多数场景，应允许开发者自行配置

feat(layout): sider token 增加 colorBgElevated

---

packages/descriptions/src/descriptions.en-US.md
packages/descriptions/src/descriptions.md

docs(docs): 修改ProDescriptions文档中ellipsis和copyable参数的错误位置，这两个参数应当为ProDescriptions.Item的参数，但被放在了ProDescriptions参数列表中；

docs(docs): 修改ProDescriptions文档参数错误

---

packages/layout/src/components/PageContainer/style/index.ts

fix(layout): 修复 extraContent 在 md 尺寸不位于 content 右侧的 bug

---

packages/table/src/style/index.ts

fix(table): slove nested table background color was cover by card

---

packages/form/src/BaseForm/LightWrapper/index.tsx

修改了LightWrapper的清除功能，使得LightFilter中的Checkbox可以正常地被重置
close: #6429

fix(LightFilter): 修改了LightWrapper的清除功能，使得LightFilter中的Checkbox可以正常地被重置

---

packages/table/src/components/ColumnSetting/index.tsx

close https://github.com/ant-design/pro-components/issues/6474
点击“列展示”全选操作时，列配置子项的顺序不应该被重置，列配置的 disable 状态不应该发生改变

fix(Table): 列配置点击“列展示”全选操作时，顺序排列和 disable 状态异常

---

packages/table/src/components/ColumnSetting/index.tsx

fix  https://github.com/ant-design/pro-components/issues/6474
子项 disable 时，“固定”按钮点击有效

fix(Table): 列配置子项 disable 时，“固定”按钮点击无效

---

packages/table/src/components/ColumnSetting/index.tsx

close https://github.com/ant-design/pro-components/issues/6474
子项 disable 时，可以拖动调整顺序

fix(Table): 列配置子项 disable 时，无法拖动调整顺序

---

packages/form/src/components/List/ListItem.tsx
packages/form/src/components/List/style.ts
tests/form/__snapshots__/demo.test.ts.snap

修复因为 https://github.com/ant-design/pro-components/issues/6392
导致默认模式下ProFormList 第一排的label 被强制关闭不生效的问题

fix(form): slove form list label defalut mode show problem

---

packages/table/src/demos/listToolBar.tsx

fix(table): 列设置里面拖动列改变顺序会导致重新发布按钮出现多次

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx
tests/layout/index.test.tsx

Sider关闭后（collapsed=true）会将展开的菜单收起，当Sider再次打开时（collapsed=false）会丢失原本的菜单展开状态

fix(layout): 修复因为Sider折叠导致菜单展开状态丢失的bug

---

packages/field/src/components/TextArea/index.tsx

fix #6619
原因分析：
`Textarea`组件为只读模式时，没有限制最大宽度。
调整后的示例代码如下：

fix(form): textarea read-mode error

---

.dumi/theme/DemoReactTechStack.ts
.dumi/theme/plugin.ts

fix: issue #6626
`dumi`框架在生成`codesandbox`链接时会分析当前`tsx`文件中的所有`import`语句，并将相关依赖的元数据信息(asset)注入为`props`，然后直接根据依赖项生成`codesandbox`链接。由于部分`pro-components`的`demo`代码没有在示例代码中显式引入`antd`，所以生成的`codesandbox`项目没有把`antd`作为依赖，导致预览失败。
利用`dumi`提供的插件能力，在每一个`code`关联的示例代码中自动引入`antd`依赖。
[相关文档](https://d.umijs.org/plugin/api#registertechstack)

fix(docs): codesandbox link missing antd dependency  #6626

---

docs/playground/index.en-US.md
docs/playground/index.md
packages/form/src/components/LoginForm/index.md
packages/form/src/components/form.en-US.md
packages/form/src/components/form.md
packages/layout/src/components/layout.en-US.md
packages/layout/src/components/layout.md
packages/table/src/components/table.md

针对下面的代码，`580px`设置其实是失效的
```js
<code src="../demos/layout-footer.tsx" iframe="580px" title="固定页脚"></code>
```
可以参照[dumi中iframe相关设置的源码](https://github.com/umijs/dumi/blob/master/src/client/theme-default/builtins/Previewer/index.tsx#L26-#L37)。
iframe参数如果是字符串的话必须能经过`Number`来转换为数字
之前：
调整后：

fix: iframe height set failed

---

packages/field/src/components/TreeSelect/index.tsx
packages/form/src/components/TreeSelect/index.tsx
tests/form/base.test.tsx

feat(form): ProFormTreeSelect support fetchDataOnSearch

---

packages/table/src/components/ListToolBar/style.ts

tabs父级没有给一个宽度，在flex布局下会出现奇奇怪怪的抖动或者无限延伸的情况，100%会自动撑开多余的空间，并不会挤兑剩余右侧内容。

fix(table): ProTable组件toolbar menu属性为tab时抖动问题(#6584)

---

packages/layout/src/ProLayout.tsx
packages/layout/src/components/layout.en-US.md
packages/layout/src/components/layout.md
packages/layout/src/defaultSettings.ts
packages/layout/src/demos/dynamicMenu.tsx
tests/layout/index.test.tsx

原代码只在开启了自动切割菜单（splitMenus=true）时，提供了当左侧菜单为空隐藏Sider的逻辑，当未开启自动切割菜单（splitMenus=false）时，根据不同条件获取服务器菜单且菜单为空的情况下，Sider显示空白且占用空间。

💥 feat(layout): layout提供在菜单为空时隐藏Sider的功能

---

packages/layout/src/components/SiderMenu/SiderMenu.tsx

if layout's avatarProps doesn't exist, the actionsRender props should also take effect

fix(layout): the actionsRender props doesn't take effect when avatarProps is null

---

packages/layout/src/components/SiderMenu/SiderMenu.tsx
packages/layout/src/components/TopNavHeader/index.tsx
packages/layout/src/components/layout.en-US.md
packages/layout/src/components/layout.md

> 修复 top 模式下，`menuHeaderRender` 不生效的问题，系 https://github.com/ant-design/pro-components/pull/6560 引入的 breaking Change
* 判断未设置 `menuHeaderRender` 时，才配置默认值
--------
> Fix the `menuHeaderRender` doesn't work in top mode, it's a breaking change in https://github.com/ant-design/pro-components/pull/6560
* Configure default value only when `menuHeaderRender` is undefined.

fix: menuHeaderRender not work

---

packages/table/src/utils/index.ts

Aciton的方法中，似乎只有reload是promise，resetAll和reset的方法其实最后都是调用hook去set数据，useState 返回的值是一个状态值和一个更新该状态值的函数，这个更新函数是异步的，但是它并不返回一个 Promise 对象，而是直接更新状态值。因此，似乎无法使用 await 关键字等待更新状态的完成。

fix: remove useless code

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx
packages/layout/src/components/SiderMenu/SiderMenu.tsx
packages/layout/src/components/TopNavHeader/index.tsx

`Layout` 组件的 `SiderMenu` 在 Dark 主题并折叠的情况下，`SubMenu` 的主题色不正常。官网的示例可复现 https://procomponents.ant.design/components/layout#packages-layout-src-components-layout-demo-dark
定位到是 `theme` 没有正确传递，尝试修复了下，辛苦 review

fix(layout): siderMenu 中的 subMenu 在 Dark 主题下显示不正常

---

packages/form/src/BaseForm/BaseForm.tsx
packages/form/src/BaseForm/createField.tsx
packages/form/src/FieldContext.tsx

`BaseForm`组件在 `fieldProps` 和 `formItemProps` 默认值的基础上增加了 `proFieldProps` ，可以设给所有field设置一些默认值，比如 `emptyText`

feat(form): BaseForm 增加 proFieldProps 默认值设置

---

packages/field/src/components/Radio/index.tsx

demo 地址 https://procomponents.ant.design/~demos/packages-form-src-components-field-set-demo-components-other
bug 如下
修复如下

🐛 fix(ProFormRadio): 修复radio和text水平对齐#6869

---

packages/provider/src/index.tsx

修复在浏览器环境下,typeof process !== 'undefined'的值始终为false,导致hashed始终为false的bug.
该问题会导致#6733
因为hashed为false,导致生成的样式没有:where选择器
导致样式被覆盖

fix: 修复在浏览器环境下hashed必为false的bug

---

packages/table/src/useFetchData.tsx

🐛 bug 描述
当loading为对象时,pro-table无法接管loading状态,必须手动控制
💻 复现代码
https://codesandbox.io/p/sandbox/loadingding-zhi-wu-xiao-wen-ti-rim9k5?file=%2Fsrc%2FApp.tsx
🏞 期望结果
无需手动控制,pro-table接管loading,加载数据时自动loading
解决方案
经过排查,是useMountMergeState方法,当入参value为undefined时,才会为非受控模式,setTableLoading才能生效.
所以只需要当loading为对象时,取出loading.spinning作为useMountMergeState的value入参,最后返回是再合并即可

fix(table): 修复当loading为对象时,pro-table无法接管loading状态,必须手动控制的问题

---

packages/field/src/components/Money/index.tsx

fix: https://github.com/ant-design/pro-components/issues/6931
ProFormMoney：当string类型的值无法正常转换成正常的数字时，比如  '****'  隐藏的值，直接展示，由开发者自行处理

fix(form): fix  parsed NaN value not display in readonly mode

---

package.json
packages/form/src/BaseForm/createField.tsx
packages/form/src/components/Dependency/index.tsx
packages/form/src/components/Field/index.tsx
packages/form/src/components/FieldSet/demos/components-other-readonly.tsx
packages/form/src/components/FieldSet/index.md
packages/form/src/components/SchemaForm/demos/ModalAndDrawerForm.tsx
packages/form/src/layouts/StepsForm/StepForm.tsx
packages/layout/src/components/SiderMenu/SiderMenu.tsx
packages/layout/src/components/TopNavHeader/index.tsx
packages/table/src/utils/cellRenderToFromItem.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/layout/PageHeader.test.tsx
tests/layout/index.test.tsx
tests/table/editor-table-two.test.tsx

close https://github.com/ant-design/pro-components/issues/7014

fix(table): table should support dependencies

---

packages/table/src/Table.tsx

容错处理 链操作符保持一致
use optional chaining for newLineOptions in editableDataSource
Define new variables isNewLineRecordAtTop

Refator/master:use optional chaining for newLineOptions in editableDataSource

---

packages/form/src/components/Field/index.tsx
packages/form/src/components/SchemaForm/index.tsx
packages/form/src/components/SchemaForm/valueType/field.tsx
tests/form/schemaForm.test.tsx

fix(form): 修复form自定义组件过多卡顿的问题

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx
packages/layout/src/components/SiderMenu/style/menu.ts

fix(layout): 修复因为 menu 不存在 icon 时候，收起的 tooltip 会多展示一个字的问题

---

packages/form/src/components/List/index.tsx

fix https://github.com/ant-design/pro-components/issues/7127

fix(list): 修复 ProFormList 使用 className 无效问题

---

packages/list/src/index.tsx

Extend the `ProListMeta<T>` type with `renderFormItem`, as it's currently missing.
We use it successfully in our codebase (with a typescript workaround) and it looks like others are expecting this type to be extended as well.
Closes https://github.com/ant-design/pro-components/issues/6871

fix: Extend ProListMeta<T> type with `renderFormItem`

---

packages/layout/src/components/TopNavHeader/index.tsx
packages/table/src/components/ColumnSetting/index.tsx
packages/table/src/components/table.en-US.md
packages/table/src/components/table.md
tests/table/columnSetting.test.tsx

When user click reset button on column setting dropDown. `clearClick` function will execute and set column value.
But the reset value can not be controlled. 
```
/** 重置项目 */
const clearClick = useRefFunction(() => {
clearPersistenceStorage?.();
setColumnsMap(
columnRef.current ||
counter.propsRef.current?.columnsState?.defaultValue ||
counter.defaultColumnKeyMap!,
);
});
```
If i change the code order be selected `defaultValue` first. Developer can use defaultValue with value to control reset value.
```
counter.propsRef.current?.columnsState?.defaultValue ||
columnRef.current ||
```
I think defaultValue should follow the literal meaning  as `default`.

fix(table): Edit to make defaultValue become higher priority to reset column setting

---

.dumirc.ts
docs/changelog.en-US.md
docs/changelog.md

使用 dumi 的 `atomDirs` 配置来识别资产目录，确保在 dumi 2.2 中 theme API 的返回值符合期望
另外修正了 `changelog.md` 的语法错误，现在打开会渲染报错

docs: use dumi atom dirs

---

packages/form/src/layouts/LightFilter/index.tsx

ProTable 开启 lightFilter 时，有需求在 columns 里配置 proFieldProps，但是不生效

fix(form): 修复 ProTable 的 columns.proFieldProps 不生效

---

packages/table/src/Table.tsx
packages/table/src/typing.ts

新增自定义搜索表单渲染支持。
我的业务需求是在 search form 外面套一层 provider，类似用  tableRender  可以在  table  外面套一层 wrapper 那样。

feat(table): add support of custom render serch form

---

packages/form/src/components/form.en-US.md
packages/form/src/components/form.md
packages/utils/src/typing.ts

ProFormField的前置转化prop`convertValue` 的类型`SearchConvertKeyFn`支持返回boolean类型。
因为`ProFormCheckbox`组件的value值是boolean类型，所以convertValue 返回的值按理来说应该要支持boolean值。

fix(form): update ReturnType<SearchConvertKeyFn>

---

packages/layout/src/demos/searchMenu.tsx

close [#6810 ](https://github.com/ant-design/pro-components/issues/6810)

fix: ProLayout 搜索菜单匹配到父级时带出子菜单

---

packages/utils/src/transformKeySubmitValue/index.ts
tests/table/search.test.tsx
tests/utils/index.test.tsx

fix: https://github.com/ant-design/pro-components/issues/7483
有点担心是否会造成已经在将错就错得使用的代码引发问题😥

fix(form): 修复transform方法与文档用法预期不符

---

packages/utils/src/typing.ts

https://github.com/ant-design/pro-components/commit/f6215e98eaeb46fa979c1ca4ac40ceaa0828f9f3#diff-c085eaf1db2f2058548f56b8ebba89098f79abb6593952091cc3ebee47d8c847R170
这个 commit 中给未定义的 ValueType 做了兜底，然而第一层用的是 `ValueType extends any`，事实上导致了永远走 true 的分支（ValueType 视为 text），失去了自动推断的效果
old:
new:

fix(type): ValueTypeWithFieldPropsBase 泛型参数失效

---

packages/field/src/components/TextArea/index.tsx
packages/field/src/components/TextArea/readonly.tsx

- 为只读状态的 textarea 组件添加 `.ant-pro-field-readonly` 和 `.ant-pro-field-readonly-textarea` 样式类
- 将原先只读 textarea 的样式转移至 `.ant-pro-field-readonly-textarea` 样式类下
- 移除了 `padding: '4px 11px'` 样式
我认为可以把所有只读状态的表单项都统一包裹 span 标签并添加  `.ant-pro-field-readonly`，便于开发者进行修改，这么做是否合适需要各位给一些意见。
fix #7578 
fix #6618

fix(form): textarea 只读状态样式不统一

---

docs/components/schema.$tab-api.md
packages/form/src/BaseForm/EditOrReadOnlyContext.ts
packages/form/src/components/Dependency/index.tsx
packages/form/src/layouts/QueryFilter/index.tsx
tests/form/base.test.tsx

fix(form): dependency 支持 colSize

---

packages/table/src/Table.tsx

具体表现：
1. 假设：请求数据100条，总数100条，每页5条；（预期本地翻页）
2. 初始通过request请求服务端数据100条；
3. 点击第2页，预期本地翻页，但实际发起了request请求 因此列表始终会有两次request请求。
原因：
setProSort(sortConfig)时，sortConfig值为undefined，与原初始值{}不相同，触发effect，从而发起了request请求。

fix(table): sortConfig值为undefined时与默认值{}不一致，会导致翻页时再次触发request请求

---

packages/table/README.md
packages/table/src/components/table.en-US.md
packages/table/src/components/table.md

This PR fixes a bug reported in #7655

doccs: Refine the collapseRender type

---

packages/field/src/components/TreeSelect/index.tsx

treeSelect组件，fieldProps中的bordered无法生效

fix(treeSelect): 修复treeSelect组件bordered属性无法生效

---

packages/table/src/components/EditableTable/index.tsx

Why:
editableFormRef.current.setRowData 这个 API 用了 coverRowKey 方法，而 coverRowKey 又用到了 value，但是没有加入到 hooks deps 中，导致 value 取值不是最新的

fix(table): 修复editableFormRef hooks 未正确传递 deps 依赖导致 value 取值不是最新

---

package.json

vscode 中使用 pnpm install 依赖后，eslint 插件报如下错误，eslint 插件无法正常运行
```
Uncaught exception received.
Error: Failed to load plugin 'jest' declared in '.eslintrc.js » /Users/xliez/Github/pro-components/node_modules/.pnpm/@umijs+fabric@4.0.1/node_modules/@umijs/fabric/dist/eslint.js': Cannot find module 'eslint-plugin-jest'
```
环境: 
MacOS 13
vscode: 1.82.2
pnpm: 8.6.3

chore: 修复 eslint 插件报错

---

packages/utils/src/typing.ts

不返回对象类型时，应该支持 undefined 或 null 或其它格式，不应该只支持 string 类型
```
// 现在这样会报错
transform: (value) => value ? moment(value).valueOf : undefined
```

fix(Table): 修改 search transform 类型

---

packages/form/src/BaseForm/BaseForm.tsx

**现状**
现有 syncToUrl 如果是函数，在组件初始化的时候并不会执行。而初始化时参数一定会带上翻页参数 current 和 pageSize。基于现有实现这俩参数将永远出现在 url 参数中（即使 syncToUrl 中配置为 undefined 也无效）。
**解决方法**
组件初始化同步 url 参数时也执行 syncToUrl 函数

fix(form): 首次同步到 url 参数时也执行 syncToUrl

---

packages/layout/src/components/Help/ProHelpDrawer.tsx
packages/layout/src/components/Help/ProHelpModal.tsx
packages/layout/src/components/Help/ProHelpPanel.tsx

1. Add `title` property to `ProHelp` component to allow rename card title
2. Remove deprecated `bodyStyle`, `headerStyle` property

fix(layout): add `title` property to `ProHelp` component

---

packages/table/src/utils/cellRenderToFromItem.tsx
packages/utils/src/useEditableArray/index.tsx

fix: https://github.com/ant-design/pro-components/issues/7790
我的方案是类似 rowKey ，用户可以给 dataSource 每项配置个 index 的属性，设置了 editable.getRealIndex 方法就去取这个 index 的值来生成 Item.name ，这样分页后的 表单就和真正的 index 对应上

fix(table): 修复 EditableProTable 实时编辑表格存在 name 属性且有分页的时候，渲染的数据总是为第一页

---

packages/layout/src/components/SiderMenu/BaseMenu.tsx

revert：https://github.com/ant-design/pro-components/commit/24cf79956f5078f5c68320036c2af01f5cb36fe9
会导致 Layout 的 siderMenuType 为 Group 时候的默认逻辑变动。
左侧为老版本

revert(layout): 回滚 Layout Menu 的获取逻辑

---

packages/field/src/components/Options/index.tsx

原来FieldOptions组件样式有问题，子元素默认都设置了 `flex: 1` ，当子元素宽度不一致是，样式会错乱。效果如官网 playground 中所示：

fix(FieldOptions): 修复 FieldOptions 中子元素换行问题

---

packages/layout/src/components/SiderMenu/index.tsx

[Drawer 抽屉](https://ant.design/components/drawer-cn#api)

fix(SiderMenu): [antd: Drawer] `bodyStyle` is deprecated waring

---

packages/field/src/index.tsx

Fix issue https://github.com/ant-design/pro-components/issues/7801.
以7801中的例子来解释，form item按antd联动的方式定义
```
{
title: "标签",
dataIndex: "labels",
valueType: "text",
formItemProps: {
dependencies: ["state"]
},
renderFormItem: (_, config, form) => {
return form.getFieldValue("state") === "open" ? (
<Input />
) : (
<Select></Select>
);
}
}
```
那么这个FormItem会在`state`值更改的时候重新渲染，但是重新渲染时props的内容用deep compare比较时并未改变，所以diff中的`useDeepCompareMemo`会导致本来可以渲染出的更新丢失掉。
2.6.20以及之前版本是正常的，是因为之前用的是 `useMemo`，`useMemo`生效是因为`rest`在每次渲染的时候都会生成一个新的，应该是没有意义的，这里我直接去掉了。

fix(field): remove useDeepCompareMemo which causing renderFormItem not updated

---

packages/components/package.json

**问题：**
访问 <https://www.unpkg.com/@ant-design/pro-components>，会自动跳转到 <https://www.unpkg.com/@ant-design/pro-components@2.6.41/dist/components.min.js>，报如下错误：
**原因：**
是 package.json 中 unpkg 字段配置为`"unpkg": "dist/components.min.js",`，而实际打包的 umd 文件名为 pro-components.min.js
**解决方案：**
将 package.json 中 unpkg 字段调整为 `"unpkg": "dist/pro-components.min.js",`，对应的 unpkg 文件访问截图：

fix: entry file of the unpkg

---

packages/layout/src/components/SiderMenu/SiderMenu.tsx

It would be great if we could access whether the sider is collapsed or not in the avatar render function.

fix(layout): pass SiderProps to avatar render function

---

packages/table/src/components/EditableTable/index.tsx

Revert previous change to `useMemo()` dependencies to allow re-rendering record creator button when button props have changed (not just toggled from false to object).
It has to be possible to re-render this button, in situations, when for example its state changed from "disabled" to "enabled".
Closes #7991

fix(table): Record Creator re-render when props change

---

packages/form/src/BaseForm/BaseForm.tsx
packages/table/src/typing.ts
packages/utils/src/conversionMomentValue/index.ts

Example
通过Example和测试发现`string`类型的参数生效, 但是类型声明需要调整一下

fix: 修复dateFormatter使用string类型提示错误

---

packages/form/src/components/List/index.tsx

具体属性为containerClassName、containerStyle、readonly。解决方案是将其从props中解构出来并调整对应使用的地方

fix: 修复ProFormList透传部分属性到FormItem中导致的react警告

---

packages/form/src/components/FormItemRender/index.tsx
packages/form/src/components/form.md
packages/form/src/components/index.ts
packages/form/src/demos/antd.modify.tsx
packages/form/src/demos/antd.nest.tsx
packages/form/src/demos/antd.tsx
packages/form/src/demos/form-control-render.tsx
packages/form/src/demos/form-item-render.tsx
tests/form/__snapshots__/demo.test.ts.snap
tests/form/formitemrender.test.tsx

添加了一些可以更方便在业务中使用的组件，设计成render props的风格去劫持渲染函数的组件
- FormControlRender
- FormItemRender
- ProFormItemRender
- useControlModel
详细的使用也添加了演示例子

feat: 添加FormItemRender组件

---

packages/table/src/components/ColumnSetting/index.tsx

https://github.com/ant-design/pro-components/assets/63690944/29148fa9-f153-4957-863f-a0344d84c513

feat(table): column SettingTitle 内容太长时显示省略&弹出 tooltip

---

packages/table/src/components/DragSortTable/demos/drag-sort-table.tsx
packages/table/src/components/DragSortTable/demos/drag.tsx

1. demo 中 onDragSortEnd 方法 newDataSource 取值有误，导致拖动后会报错，官网可复现。
3. demo 中的测试数据已经又 key 字段作为表格 rowKey 的传参，因此删除了多余的 index 字段。
4. demo 中的搜索表单没有效果，因此修改 search 进行隐藏。

fix(DragSortTable): demo 拖动排序后报错

---

packages/provider/src/index.tsx

ProConfigContext 每次渲染都会因为 children 改变会发生重置，导致表格等组件的 cell 进行无效的渲染

perf: 优化 config provider context 频繁触发渲染问题

---

packages/provider/src/index.tsx
tests/provider/index.test.tsx

This PR allows developers to pass an `intl` property (created via `createIntl`) to the ConfigProvider in order to define custom translations.

feat: allow custom translations

---

packages/form/src/layouts/QueryFilter/index.tsx

fix: https://github.com/ant-design/pro-components/issues/8067
这个 [pr](https://github.com/ant-design/pro-components/pull/7611) 中引入了这个 BUG，建议原 [issue](https://github.com/ant-design/pro-components/issues/6928) 自己实现 Table 的筛选区

fix(QueryFilter): 修复 ProFormDependency 在 QueryFilter 中失效的问题

---

scripts/bootstrap.js

调整判断逻辑，原逻辑会导致packages目录下文件夹内有pacages.json没有README.md时，报错：`TypeError: Cannot read properties of undefined (reading 'description') `

fix: 修复bootstrap.js创建文件bug

---

packages/form/src/layouts/DrawerForm/index.tsx
tests/form/ssr.test.tsx

 fix(form): DrawerForm ssr 错误 : window is not defined

---

packages/form/src/BaseForm/BaseForm.tsx
packages/form/src/components/form.md

onFinish在部分场景或部分用户开发习惯中，是不需要写async函数的，所以不用默认去setLoading，省去2次组件刷新

perf：onFinish为同步函数时不用setLoading，避免开销浪费

---

packages/table/src/Store/Provide.tsx

实际生产中，defaultValue往往作为系统方默认配置，则优先级不应高于用户配置的storageValue。
否则会出现在设置defaultValue后用户无论如何修改都无法获取自己配置的效果
[#8204](https://github.com/ant-design/pro-components/issues/8240)
原有代码  `  if (storageValue) {
if (props?.columnsState?.defaultValue) {
return merge(
JSON.parse(storageValue),
props?.columnsState?.defaultValue,
);
}
return JSON.parse(storageValue);
} `

 🐛 fix(proTable): 将Table columnsState storageValue覆盖defaultValue

---

packages/form/src/layouts/ModalForm/index.tsx
tests/form/modalForm.test.tsx

close: https://github.com/ant-design/pro-components/issues/8156
close: https://github.com/ant-design/pro-components/issues/7545

fix(form): onOpenChange fires twice when opening ModalForm

---

packages/field/src/components/TextArea/readonly.tsx

fix: textarea readonly mode cant use fieldProps.style
I add style `wordBreak: 'break-all'`, its not effective
```js
<ProFormTextArea
name="name2"
label="name"
fieldProps={{
style: {
wordBreak: 'break-all',
},
}}
/>
```

fix(form): textarea readonly mode cant use fieldProps.style

---

packages/card/src/components/CheckCard/index.tsx
packages/card/src/components/CheckCard/style.ts

The extra element and title ellipsis in the checkcard are not functioning correctly when the title is too long.
#7894

fix(card): extra element and title ellipsis in the checkcard

---

packages/table/src/Store/Provide.tsx

fix(table): 修复columnsMap重新赋值时总是使用默认值的问题

---

packages/form/src/components/FormItem/index.tsx

##当filedChildren不是'ProFormComponent'并且是reactElement时 将onBlur透传给proformItem下的children组件。

fix: fix issues #8380

---

packages/table/src/components/DragSortTable/index.tsx

From this issue id #8232. I just move DndContext from tableViewRender to wrap ProTable component for avoid css ficking when some component in DragSortTable change state.
🐛 bug detail
when create or take any action to make DragSortTable component re-render it alway filking a bit

DragSortTable layout flicker when using in explanable table

---

packages/form/src/layouts/ModalForm/index.tsx
tests/form/modalForm.test.tsx

如果ModalForm的open状态由父级通过props控制，并且需要在打开时对form设定初值，就需要监听propOpen的状态，并在其为 true时执行一次onOpenChange。

fix(form): 修复openChange打开时不触发问题

---

packages/table/src/demos/single.tsx
packages/table/src/demos/theme.tsx

bug: pro-table案例代码dropdown子项key都一样导致鼠标悬浮dropdown时全部被选中
修改内容：将pro-table案例代码中的key从全部都是字符串1修改为1、2、3，与其他相关案例保持一致

docs(proTable): 修复pro-table文档案例代码里Dropdown内元素key冲突问题

---

packages/utils/src/conversionMomentValue/index.ts

递归过程中 parentKey 传递的应该是之前所有遍历过的name

fix(form):ProFormTimePicker.RangePicker 获取时间区间，当name超过两层时，值为日期+时间格式 #8223

---

packages/field/src/components/Second/index.tsx

处理了 second 字段类型为负数时的显示, 目前在 local repo 使用, 不确定是否符合组件设计意图
issue #8447

feat: the second field supports negative numbers

---

packages/layout/src/components/SiderMenu/style/index.ts

token.layout?.sider?.colorTextMenuItemHover
menuItem 的 hover 字体颜色，不应该包含已选中的菜单

移除选中菜单hover字体变色的效果

---

packages/layout/src/components/PageHeader/index.tsx
packages/layout/src/components/PageHeader/style/index.ts
pnpm-lock.yaml

Fixes #8479
Fixes #8490
1. 如果背景默认透明是 by design，那 PageHeader `ghost` 就默认给个 true 吧
2. 修复 `has-breadcrumb`, `has-footer` 样式不生效
3. 修复 `breadcrumb.routes` 不生效导致面包屑空白
4. 官网白屏可能是依赖的问题，我本地一开始也跑不起来，更新 lock 文件后就正常了

fix(layout): PageHeader style and breadcrumb.routes prop

---

packages/form/src/components/FormItem/index.tsx

I worked on #8462 a few days ago.
Fix this operation because it is bugged.
1. help typing error
2. Handling when addonBefore, addonAfter does not exist
3. A problem that cannot be rendered because help is not delivered to FormItem
I should have checked more, but I couldn't.
I'm sorry

fix: formItem help render type

---

packages/table/src/components/DragSortTable/index.tsx

Reverts ant-design/pro-components#8414

Revert "DragSortTable layout flicker when using in explanable table"

---

packages/provider/src/intl.ts

For example, if the user has not defined `editableTable.onlyAddOneLine` in the context:
```ts
// Intl passed to ProConfigProvider
export default {
editableTable: {},
};
```
The translation will fall back to default message. However, `editableTable.onlyAddOneLine` is actually defined in the provider's default language set. This fix ensures that the translation is found in the default set.

fix(provider): use built-in translation when translation in ProConfigContext is missing

---

packages/table/src/Table.tsx
packages/utils/src/useEditableArray/index.tsx

[#8547](https://github.com/ant-design/pro-components/pull/8547)的另外一种改法

fix: 解决ProTable.editable.actionRender无法获取最新state快照的问题（第二种改法）

---

packages/form/src/components/StepsForm/demos/steps-form-vertical.tsx

bug：https://github.com/ant-design/pro-components/issues/8596
修改内容：修复文档案例(分步表单垂直模式)因ProFormCheckbox.Group嵌套层级不对导致的布局错乱的问题

docs(StepsForm): 修复文档案例(分步表单垂直模式)的布局错乱问题

---

packages/card/src/components/Card/style.ts

fix: add unit to transition duration in procard

---

packages/form/src/components/index.ts
packages/form/src/index.tsx

feat(form): export ProFormTreeSelectProps

---

packages/table/src/components/ColumnSetting/index.tsx

fix(table): don't spread key to children

---

packages/form/src/components/Select/index.tsx

**这笔修改是为了让 ProFormSelect  外部传入的 OptionType 类型正常透传给 antd 的 Select，如下图示：**

fix(form): pass the OptionType type of ProFormSelect to the inner Select

---

package.json
packages/form/package.json
packages/form/src/BaseForm/BaseForm.tsx
packages/form/src/layouts/StepsForm/StepForm.tsx
packages/table/package.json
pnpm-lock.yaml
tests/form/base.test.tsx

feat(Form): FormRef support forward nativeElement

---

packages/field/src/components/Select/LightSelect/index.tsx

轻量筛选 通过搜索框筛选后只能再通过鼠标操作选择，操作稍显麻烦。
搜索框输入后可直接通过方向键上下选择和回车选中。
恢复选择器输入框除退格键外的键盘事件。

fix(field): keyboard events of search input in LightSelect

---

packages/form/src/layouts/LoginFormPage/index.tsx

相关连接 https://stackoverflow.com/questions/32467408/http-localhost-undefined-404-not-found

fix: 修复backgroundImageUrl 为空时 会导致 url("undefined") 发送一次请求 http://localhost/undefined 404 (Not Found) 报错

---

packages/layout/package.json
pnpm-lock.yaml

fix(layout): downgrade path-to-regexp to version 8.0.0

---

packages/layout/src/ProLayout.tsx

情况
1. ProLayout 中只有获取菜单会用到 swr ，组件销毁时已有清理缓存
https://github.com/ant-design/pro-components/blob/a3d14c3464fb07f41c1e2be96ce3dd9e4a23d451/packages/layout/src/ProLayout.tsx#L494-L523
2.  设置了 `autoClearCache` 会把  SWR 全局缓存清掉，导致其他功能异常 #7670
https://github.com/ant-design/pro-components/blob/a3d14c3464fb07f41c1e2be96ce3dd9e4a23d451/packages/provider/src/index.tsx#L193-L210
因此这个属性可以直接去掉？

fix(layout): remove `autoClearCache` in ProLayout

---

packages/card/package.json
packages/components/package.json
packages/descriptions/package.json
packages/field/package.json
packages/form/package.json
packages/layout/package.json
packages/list/package.json
packages/provider/package.json
packages/skeleton/package.json
packages/table/package.json
packages/utils/package.json

Added `exports` field so the components can be loaded with nodejs ESM resolver. This is needed when importing components in `vitest` for example.
Fixes https://github.com/ant-design/pro-components/issues/8627

feat: added exports to support ESM environments such as vitest

---

packages/card/package.json
packages/layout/package.json
packages/list/package.json
packages/provider/package.json
packages/table/package.json
pnpm-lock.yaml

These packages use `@ant-design/cssinjs` and `dayjs` in their codebase, but not install them correctly.

fix: add missing dependencies

---

packages/layout/src/components/PageContainer/index.en-US.md
packages/layout/src/components/PageContainer/index.md

antd v5 移除 PageHeader 组件，移至 @ant-design/pro-components 中维护，修正相关 PageHeader 文档超链接。

docs: PageHeader 超链接更新

---

packages/utils/src/components/FieldLabel/index.tsx

substr api 未来会已弃用，可以替换为 splice
> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/substr

perf: replace substr with splice

---

packages/form/src/BaseForm/BaseForm.tsx

官网第一个demo保存就是有问题的，created_at格式变成了默认的 dateTime
https://github.com/ant-design/pro-components/issues/8875

fix:(editableTable)点击保存后valueType未读取到导致convertMoment的日期格式错误

---

packages/form/tsconfig.json

https://github.com/cycleccc/pro-components/blob/943212b57bbaeb67bc76bf2dfac46db53ba8630f/packages/form/src/components/SchemaForm/demos/schema.tsx#L5
类似于以上代码的导入语句因为没有配置对应的 tsconfig 路径导致不方便 查找源文件及对应的 ts type。
补齐似乎更好。

perf: add pro-componets path

---

packages/form/src/components/Switch/index.tsx
packages/form/src/typing.ts

1.  添加 fieldItem 公共属性 emptyText
2.  针对 form switch 屏蔽 emptyText 属性（没找到 form option 组件 ）
相关issue：https://github.com/ant-design/pro-components/issues/8848

fix: add emptyText fieldItem props

---

packages/provider/src/useStyle/index.ts

在排查 https://github.com/ant-design/ant-design/issues/51867 问题时发现， pro 没有配置 layer 选项
虽然 pro 修改了 prefix 可以很大程度上避免样式权重比 antd 小的情况。
结合前面的 issue 来看，也有开发者会需要 layer。 所以先把 PR 开在这里，评审一下是否需要吧～
CC @zombieJ @chenshuai2144

✨ feat: Support response to antd-cssinjs cascade layer config

---

packages/form/src/components/Select/index.tsx

不确定要不要提升 antd 依赖， 如果 antd 版本比较低的话， 可能 ts 类型会导出失败？
看了一下，至少 5.6.1 就有导出这几个类型的 see：https://github.com/ant-design/ant-design/blob/5.6.1/components/select/index.tsx#L29
fix #8901

chore(TS): fix TS type error

---

packages/field/src/components/Select/SearchSelect/index.tsx
packages/field/src/components/Select/index.tsx

- Add preserveOriginalLabel prop to control whether to use the original label when option is selected
- Fix the issue where highlighted search text appears in the input box when option is selected
BREAKING CHANGE: None
close #8918 
出现问题的原因：
在多选且开启 labelInValue 的情况，onChange 的时候会使用 getMergeValue 来合并最终数据
https://github.com/ant-design/pro-components/blob/21ce755745c1b5fa26415cd1dcc1a8ac8ed2c159/packages/field/src/components/Select/SearchSelect/index.tsx#L155
代码如下：
```typescript
// 多选模式开启 labelInValue 的时候生成最终变化的值的函数
const getMergeValue: SelectProps<any>['onChange'] = (value, option) => {
if (Array.isArray(value) && Array.isArray(option) && value.length > 0) {
// 多选情况且用户有选择
return value.map((item, index) => {
const optionItem = (option as DefaultOptionType[])?.[
index
] as DefaultOptionType; …
```

fix(field): add preserveOriginalLabel prop to SearchSelect

---

package.json
packages/form/src/components/Select/index.tsx
packages/layout/src/demos/customSider.tsx
packages/provider/src/useStyle/index.ts
pnpm-lock.yaml

logs: https://github.com/ant-design/pro-components/actions/runs/12368252911/job/34517899002

:green_heart: chore: format code

---

packages/form/src/components/FormItem/index.tsx

antd 那边估计是不会再修改_internalItemRender，看能不能先将这个移除下
input的信息抖动太难受了，如果之后antd合了
[#8935](https://github.com/ant-design/pro-components/pull/8935)
这个之后改回来吧。
因为这个抖动导致antd只能锁在5.21

fix(formItem):移除默认的_internalItemRender使input校验信息不抖动

---

packages/field/src/components/Select/SearchSelect/index.tsx

如果用户使用了 request和labelInValue，保存之后，刷新页面，正常回显，但是再次添加会出现 label 丢失的情况。所以需要兼容

fix: 修复刷新之后 label 丢失的情况

---

packages/table/src/components/EditableTable/index.tsx

修复 EditableProTable 的 Form.Item 中 shouldUpdate 与 dependencies 的冲突问题。
目前，当使用带有 `name` 属性的 EditableProTable 时，如果我们想在 `formItemProps` 中使用 `dependencies`，会出现以下警告：
```tsx
warning(
!(shouldUpdate && dependencies),
'usage',
"`shouldUpdate` and `dependencies` shouldn't be used together. See https://u.ant.design/form-deps.",
);
```
这是因为 EditableProTable 内置的 `shouldUpdate` 逻辑与 `dependencies` 产生了冲突。
将默认的 `shouldUpdate` 移到 `{...props?.formItemProps}` 前面，这样用户的配置就可以覆盖默认值：
```diff
return (
<Form.Item
style={{
maxWidth: '100%',
}}
+   shouldUpdate={(prev, next) => {
+     const name = [props.name].flat(1) as string[];
+     try {
+       return JSON.stringify(get(prev, name)) !== JSON.stringify(get(next, name));
+     } catch (error) {
+       return true;
+     }
+   }}
{...props?.formItemProps} …
```

fix(table): resolve EditableProTable Form.Item shouldUpdate conflict

---

packages/layout/tsconfig.json

更新最新的pro-components后发现ProForm的index.d.ts文件有部分类型引入错误
经过版本对比，typescript@v.5.7版本会把 "../.." 重写为 “src”
添加了resolvePackageJsonExports和resolvePackageJsonImports选项避免typescript@v5.7把某些import路径编译为src路径下

chore(TS): fix TS compilation type errors

---

packages/utils/src/pickProFormItemProps/index.tsx

fix: https://github.com/ant-design/pro-components/issues/9050
同步 antd 的 validateDebounce 属性到 antdFormItemPropsList 列表中，解决了传参丢失的问题

fix(ProFormItem): 修复 validateDebounce 属性不生效的问题

---

packages/form/src/components/List/ListItem.tsx
tests/form/formList.test.tsx

increase the parame of the actions function to maintain consistency 
让onAfterAdd函数的入参保持一致性，既然复制一行总是会在最后一行添加，也把这个参数透出.
修复此issue的bug：[BUG] ProFormList的onAfterAdd回调函数参数异常 fix：#9102

fix :increase the parame of the actions function to maintain consistency.

---

packages/layout/src/components/Help/ProHelpPopover.tsx
packages/utils/src/components/FilterDropdown/index.tsx

修复报 Warning: [antd: Tooltip] `overlayInnerStyle` is deprecated. Please use `styles={{ body: {} }}` instead. 这个错误的问题

fix(deprecated):修复Popover使用overlayInnerStyle后报deprecated错误的问题

---

packages/card/src/ProCard.tsx
packages/card/src/components/Card/index.tsx
packages/card/src/components/card.en-US.md
packages/card/src/components/card.md
packages/card/src/demos/collapsible.tsx
packages/card/src/typing.ts

Fix issue [#8989](https://github.com/ant-design/pro-components/issues/8989)[#8922](https://github.com/ant-design/pro-components/issues/8922)
Update the `collapsible` prop to accept values such as `header` or `icon` to define the trigger area.

feat: ProCard collapsible now supports specifying trigger area

---

packages/field/src/components/RangePicker/index.tsx

Fix issue [9105](https://github.com/ant-design/pro-components/issues/9105)
DatePicker 组件貌似没有提供 onClear 方法

fix(LightFilter):DatePicker resets to its initial state after data is cleared.
