README.md, package.json, packages/list/README.md, packages/list/demos/base.tsx, packages/list/demos/complex.tsx, packages/list/demos/expand.tsx, packages/list/demos/group.tsx, packages/list/demos/headerRender.tsx, packages/list/demos/layout.tsx, packages/list/demos/minMenu.tsx, packages/list/demos/selectedRow.tsx, packages/list/demos/size.tsx, packages/list/demos/special.tsx, packages/list/docs/index.md, packages/list/package.json, packages/list/src/Item.tsx, packages/list/src/hooks/useLazyKVMap.ts, packages/list/src/hooks/usePagination.ts, packages/list/src/hooks/useSelection.tsx, packages/list/src/index.less, packages/list/src/index.tsx, packages/list/src/toolBar/index.less, packages/list/src/toolBar/index.tsx, packages/list/src/util/getPrefixCls.ts, tsconfig.json, yarn.lock
=> feat: add list component

packages/table/src/table.md
如: 
- tableRender
- tableExtarRender
Related Issue: 
https://github.com/ant-design/pro-table/issues/657
=> 📚doc: 补全 table 的一些 API 

docs/index.md
=> fix: docs features desc

packages/table/src/component/status/index.tsx, packages/table/src/component/util.tsx
=> valueEnum支持自定义色值,status值不区分大小写

packages/card/demos/gutter.tsx, packages/card/demos/responsive.tsx, packages/card/src/card.md, packages/card/src/index.tsx, tests/__snapshots__/demo.test.tsx.snap
feat: procard support responsive gutter and colSpan
支持响应式布局和 gutter。
=> feat: procard support responsive gutter and colSpan

packages/card/CHANGELOG.md, packages/field/CHANGELOG.md, packages/form/CHANGELOG.md, packages/layout/CHANGELOG.md, packages/list/CHANGELOG.md, packages/provider/CHANGELOG.md, packages/skeleton/CHANGELOG.md, packages/table/CHANGELOG.md, packages/table/demos/single.tsx, scripts/release.js
=> docs: update table demo

packages/table/demos/single.tsx, packages/table/docs/table.md
现在文档的组织还有部分描述有点问题
- 部分描述口语化
- API 层级组织不够清晰
close  https://github.com/ant-design/pro-components/issues/61
=> doc: optimize table docs

packages/provider/src/index.tsx, packages/provider/src/locale/pt_BR.tsx, packages/table/demos/intl.tsx, packages/table/src/index.tsx
=> Added pt_BR locale

packages/form/src/components/LabelIconTip/index.less, packages/form/src/components/LabelIconTip/index.tsx, tests/__snapshots__/demo.test.tsx.snap, yarn.lock
=> 💄 UI: same style as design draft

packages/table/src/Table.tsx
=> fix colunm.sorter bug

packages/table/docs/table.md, packages/table/src/form/index.tsx
=> 📝 docs: add span and ColConfig doc

packages/table/src/form/index.tsx
=> fix(table): 搜索项如果只选择起始日期时，会出现Invalid Date

packages/layout/docs/getting-started-layout.md, packages/layout/docs/layout.md, packages/table/demos/table-nested.tsx, packages/table/docs/table.md
close https://github.com/ant-design/pro-components/issues/117
close https://github.com/ant-design/pro-components/issues/128
=> 📝 docs: fix docs error

README.md, docs/index.md, package.json, packages/card/package.json, packages/descriptions/package.json, packages/field/package.json, packages/form/package.json, packages/layout/package.json, packages/list/package.json, packages/provider/package.json, packages/skeleton/package.json, packages/table/package.json, packages/utils/package.json, scripts/bootstrap.js
ref https://github.com/ant-design/pro-components/issues/127
=> 🎨 chore: add browserslist config

packages/table/src/Table.tsx, packages/table/src/defaultRender.tsx, packages/table/src/utils.tsx, tests/__snapshots__/demo.test.tsx.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/demo.tsx
close https://github.com/ant-design/pro-components/issues/152
=> 🐛 fix(table): Fix the problem that text is react node when valueType does not exist

packages/field/src/field.md, packages/skeleton/src/skeleton.md, packages/table/src/utils.tsx, packages/utils/src/pickProProps/index.tsx, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/162
=> 🐛 fix(table): fix pagination no work error

jest.config.js, packages/card/package.json, packages/descriptions/package.json, packages/field/package.json, packages/form/package.json, packages/layout/package.json, packages/provider/package.json, packages/skeleton/package.json, packages/table/package.json, packages/utils/package.json, scripts/bootstrap.js
ref https://github.com/ant-design/pro-components/issues/163
=> 🎨 chore: rm src publish and add module

.github/workflows/deploy.yml, packages/field/src/field.md, packages/skeleton/src/skeleton.md, packages/table/src/utils.tsx, packages/utils/src/pickProProps/index.tsx, tests/table/index.test.tsx
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration
pro 和其他库也可以这样改改。
=> chore: run deploy action in master branch only

packages/field/src/components/Percent/util.ts, packages/field/src/index.tsx, tests/field/__snapshots__/field.test.tsx.snap, tests/field/__snapshots__/status.test.tsx.snap, tests/field/field.test.tsx, tests/field/status.test.tsx, tests/layout/pageContainer.test.tsx
close https://github.com/ant-design/pro-components/issues/176
=> 🐛 fix(field): fix emptyText no work error

packages/table/src/Table.tsx
=> 🐛 fix(table): fix table default have key bug

packages/layout/fixtures/defaultProps.tsx, packages/layout/src/SiderMenu/BaseMenu.tsx, packages/layout/src/SiderMenu/index.less, tests/layout/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/196
=> 🐛 fix(layout): Fix the submenu misalignment problem

packages/field/demos/base.tsx, packages/field/src/components/Percent/util.ts, packages/field/src/index.tsx, packages/form/src/components/Field/index.tsx, packages/form/src/layouts/QueryFilter/index.tsx, packages/table/demos/form.tsx, packages/table/demos/linkage_form.tsx, packages/table/demos/search.tsx, packages/table/demos/search_option.tsx, packages/table/demos/valueType.tsx, packages/table/src/Form/index.tsx, packages/table/src/component/ToolBar/index.tsx, packages/utils/src/pickProProps/index.tsx, tests/descriptions/index.test.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/field/__snapshots__/field.test.tsx.snap, tests/field/field.test.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/225
=> 🐛 fix(table): fix table search key warning error

packages/table/src/Table.tsx, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/227
close https://github.com/ant-design/pro-components/issues/195
=>  🐛 fix(table): reloadAndRest will reset filter and sort

packages/layout/docs/layout.md
https://github.com/ant-design/pro-components/issues/226
=> docs: fix typo

packages/table/demos/valueType.tsx, packages/table/src/Table.tsx, packages/utils/src/pickProProps/index.tsx, tests/descriptions/index.test.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/238
=> 🐛 fix(table): do not pick mode props

packages/table/src/index.less
from https://github.com/ant-design/pro-table/pull/690
=> 💄 UI: update td font-size to antd less var

packages/field/src/components/Select/index.tsx, packages/field/src/index.tsx, packages/table/demos/single.tsx, packages/table/demos/valueType.tsx, packages/table/src/Form/index.tsx, packages/table/src/Table.tsx, tests/layout/settingDrawer.test.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/269
close https://github.com/ant-design/pro-components/issues/256
close https://github.com/ant-design/pro-components/issues/255
close https://github.com/ant-design/pro-components/issues/266
=>  🐛 fix(table): support value and onChange

package.json, packages/form/src/components/Checkbox/index.tsx, packages/form/src/components/DateRangePicker/index.tsx, packages/form/src/components/DateTimePicker/index.tsx, packages/form/src/components/DateTimeRangePicker/index.tsx, packages/form/src/components/Digit/index.tsx, packages/form/src/components/Radio/index.tsx, packages/form/src/components/Rate/index.tsx, packages/form/src/components/Select/index.tsx, packages/form/src/components/Slider/index.tsx, packages/form/src/components/Switch/index.tsx, packages/form/src/components/TextArea/index.tsx, packages/form/src/components/TimePicker/index.tsx, packages/form/src/components/UploadButton/index.tsx, packages/form/src/components/UploadDragger/index.tsx, packages/table/demos/batchOption.tsx, packages/table/demos/valueType.tsx, packages/table/src/Table.tsx, packages/table/src/useFetchData.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/field/__snapshots__/demo.test.ts.snap, tests/field/__snapshots__/field.test.tsx.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/__snapshots__/valueEnum.test.tsx.snap, yarn.lock
close https://github.com/ant-design/pro-components/issues/261
=> ⚡performance(table): Optimize performance to reduce render

packages/form/src/layouts/QueryFilter/Actions.tsx
=> fix: actions intl message

packages/utils/src/conversionSubmitValue/index.ts
close https://github.com/ant-design/pro-components/issues/268
=> 🐛 fix(table): Fixes an issue that removes parameter 0

packages/table/src/Form/index.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
- pro-table 文档显示的 labelWidth 默认值是 98.
- 如果没有指定 labelWidth ,就使用 undefined，使用 QueryFilter 组件默认的 `labwlWidth = 98`
=> fix: use default value of labelWidth

packages/form/src/layouts/QueryFilter/Actions.tsx, packages/form/src/layouts/QueryFilter/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/queryFilter.test.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/303
=> 🐛 fix(form): fix collapseRender no work error

packages/table/src/Form/index.tsx, packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/301
=> 🐛 fix(table): fix reset no use initvalues error

packages/form/src/components/DateRangePicker/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/296
=> 🐛 fix(form): fix ProFormDatePicker is dateTimeRange error

packages/table/src/Form/index.less
close https://github.com/ant-design/ant-design-pro/issues/7249
=> 💄 UI(table): fix mobile style error

packages/layout/src/FooterToolbar/index.less, packages/layout/src/FooterToolbar/index.tsx, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/pageContainer.test.tsx.snap
=> 🚑 hotfix: layout decoupling antd@4

packages/card/src/card.md, packages/card/src/demos/colspan.tsx, packages/card/src/demos/holygrail.tsx, packages/card/src/demos/layout.tsx, packages/card/src/demos/split23.tsx, packages/card/src/style/index.less, tests/card/__snapshots__/demo.test.ts.snap, tests/skeleton/__snapshots__/demo.test.ts.snap
1. 修复垂直居中demo 中body内容未撑满问题。
2. 添加圣杯布局。
=> docs(procard): add more demos

packages/form/src/components/Field/index.tsx, packages/table/src/Form/index.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/210
=> 🐛 fix(table): fix initialValue no work error

packages/table/src/index.less
close https://github.com/ant-design/pro-components/issues/79
=> 💄 UI(table): strict css style rewrite

packages/layout/src/GlobalHeader/index.tsx, packages/layout/src/SiderMenu/SiderMenu.tsx, packages/layout/src/TopNavHeader/index.tsx, packages/layout/src/demos/base.tsx, packages/layout/src/layout.md, tests/layout/index.test.tsx
close https://github.com/ant-design/pro-components/issues/223
=> 🐛 fix(layout): fix onMenuHeaderClick no work in mix mode

packages/table/src/Table.tsx, packages/table/src/useFetchData.tsx, packages/table/src/utils.tsx, packages/utils/src/typing.ts, tests/table/index.test.tsx, tests/table/pagination.test.tsx
close https://github.com/ant-design/pro-components/issues/279
=>  🐛 fix(table): pagination=false, do not have pageParams

packages/form/src/layouts/QueryFilter/index.tsx, packages/table/src/Form/index.tsx, tests/table/search.test.tsx
修复 close [#332](https://github.com/ant-design/pro-components/issues/332) 问题
=>  fix(compiler): 修复proTable search span 配置问题

packages/layout/src/layout.md
=> docs(layout): add description of location property

packages/form/src/components/Group/index.less, packages/form/src/components/Group/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
Group 的响应式规则：控件宽度是固定的，容器宽度不够的时候换行即可。
=> 💄 UI(form): ProForm group responsive rule

packages/utils/src/conversionSubmitValue/index.ts
=> 🐛 fix(compiler): 修复ProForm表单值为空时,缺少字段

packages/table/src/useFetchData.tsx
close https://github.com/ant-design/pro-components/issues/336
=> 🐛 fix(bug): fix request error don't setLoading error

packages/table/src/Form/index.tsx, packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/346
=> 🐛 fix(table): if type=from, textarea should show textarea

packages/table/src/demos/batchOption.tsx, packages/table/src/demos/no-title.tsx, packages/table/src/demos/normal.tsx, packages/table/src/demos/table-nested.tsx, packages/table/src/table.md, tests/table/__snapshots__/demo.test.ts.snap
1. 迁移官网 Protable 示例到 Pro components 中。
2. 整理 Protable 文档示例。
=> docs(table): 迁移官网 Protable 示例到 Pro components，整理文档

packages/table/src/defaultRender.tsx
close https://github.com/ant-design/pro-components/issues/369
=> 🐛 fix(table): fix columnEmptyText no work error

packages/utils/src/hooks/useDebounceFn/index.ts
close https://github.com/ant-design/pro-components/issues/376
=> 🐛 fix(table): fix reload no support wait

packages/form/src/layouts/QueryFilter/index.tsx
close https://github.com/ant-design/pro-components/issues/374
=> 🐛 fix(form): fix a problem with searchtext passing

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/250
=> 🐛 fix(table): fix sort has undefined key error

packages/table/src/defaultRender.tsx
=> 🐛 fix(table): 完善columnEmptyText空值不显示

packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/components/Field/index.tsx, packages/table/src/Form/index.tsx, packages/table/src/demos/linkage_form.tsx, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/413
close https://github.com/ant-design/pro-components/issues/409
=> 🐛 fix(table): fix renderFormItem item no work bug

packages/layout/src/layout.md
=> docs: fix layout siderWidth default value

packages/table/src/utils.tsx
close #410
请问一下 你们保存eslint 会很慢吗？换了个电脑 不知道 怎么了 每次保存要好几秒😂
=> 🐛 fix(table): table text is null copy

packages/table/src/table.md
=> docs(table): 删除已移除功能描述

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/415
=> 🐛 fix(table): fix pageinfo is undefined error

packages/card/package.json, packages/descriptions/package.json, packages/field/package.json, packages/form/package.json, packages/layout/package.json, packages/list/package.json, packages/skeleton/package.json, packages/table/package.json, packages/utils/package.json
添加 sideEffect 开启 webpack treeShaking
ref https://github.com/ant-design/pro-components/issues/283
ref https://github.com/ant-design/pro-components/issues/177
ref https://github.com/ant-design/pro-components/issues/50
=> chore: add sideEffect to components to activate webpack treeshaking

packages/form/src/form.md
=> docs: update ProForm API doc

packages/field/src/components/Select/LightSelect/index.less, packages/field/src/components/Select/LightSelect/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
如果使用`vscode`编写代码,可以安装`Code Spell Checker`进行提示单词是否编写错误.
=> 🎨 fix(field): fix classname naming error

packages/table/src/Table.tsx, tests/table/pagination.test.tsx
close https://github.com/ant-design/pro-components/issues/477
=> 🐛 fix(table): fix table pageSize or current problem

packages/table/src/Table.tsx, packages/table/src/utils.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/479
=> 🐛 fix(table): better ellipsis function

packages/provider/src/index.tsx, packages/table/src/demos/intl.tsx, tests/table/__snapshots__/demo.test.ts.snap
=> 🐛 fix(table): fix the problem that intl switching is not fulfilled

packages/table/src/Form/index.tsx
close https://github.com/ant-design/pro-components/issues/510
=> 🐛 fix(table): fix tip no work in form mode

packages/table/src/Form/index.tsx
=> 🐛 fix(table): fix react dom props warning

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/505
=> 👷 fix(table): beforeSearchSubmit retrun value support any values

packages/layout/src/PageContainer/index.tsx, tests/layout/__snapshots__/pageContainer.test.tsx.snap, tests/layout/pageContainer.test.tsx
ref https://github.com/ant-design/pro-components/issues/464
=> 💥 feat(table): layout support header Props

packages/field/src/components/Select/index.tsx, packages/form/src/demos/components-other.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/524
=> 🐛 fix(filed): fix request no work error

packages/field/package.json, packages/layout/src/PageContainer/index.tsx, packages/list/package.json, packages/utils/package.json, packages/utils/src/hooks/useDeepCompareEffect/index.ts, yarn.lock
close https://github.com/ant-design/pro-components/issues/461
=> ⚡️ performance(table): support fast isequal function

packages/table/src/Table.tsx, packages/table/src/useFetchData.tsx, packages/utils/src/omitUndefinedAndEmptyArr/index.ts
close https://github.com/ant-design/pro-components/issues/490
=> 🐛 fix(table): fix onCell no work error

package.json, packages/form/src/components/UploadButton/index.tsx, packages/form/src/components/UploadDragger/index.tsx, packages/form/src/demos/components-other.tsx, tests/form/upload.test.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/472
=> 💥 feat(form): support max fileList props

packages/card/src/card.md, packages/card/src/demos/inner.tsx, packages/card/src/index.tsx, packages/card/src/style/index.less
=> feat(card): 卡片支持类型为内部卡片

packages/card/src/card.md, packages/card/src/demos/basic.tsx, packages/card/src/demos/bordered.tsx, packages/card/src/demos/headerBordered.tsx, packages/card/src/index.tsx, packages/descriptions/src/demos/base.tsx, packages/descriptions/src/descriptions.md, packages/descriptions/src/index.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/demos/base.tsx, packages/form/src/demos/layout-base.tsx, packages/form/src/demos/multi-card-step-form.tsx, packages/form/src/demos/steps-from.tsx, packages/form/src/form.md, packages/table/src/Form/index.tsx, packages/table/src/Table.tsx, packages/table/src/component/ToolBar/index.tsx, packages/table/src/table.md, packages/utils/src/components/LabelIconTip/index.tsx, packages/utils/src/demos/subTitle.tsx, packages/utils/src/typing.ts, tests/card/__snapshots__/demo.test.ts.snap, tests/skeleton/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/540
=> 🎨 docs: change tip props to tooltip

packages/field/src/components/Select/index.tsx, packages/field/src/demos/base.tsx, packages/utils/src/typing.ts
close https://github.com/ant-design/pro-components/issues/486
=> 💥 feat(field): valueEnum support disable

packages/layout/src/SiderMenu/BaseMenu.tsx, packages/layout/src/typings.ts
close https://github.com/ant-design/pro-components/issues/456
=> 💥 feat(layout): support disable in menuitem

packages/table/package.json, packages/table/src/component/ColumnSetting/DndItem.tsx, packages/table/src/component/ColumnSetting/index.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/549
=> 🐛 fix(table): fix some style error

packages/provider/src/index.tsx, packages/provider/src/locale/ko_KR.tsx
Hi. 
Thank you for sharing. 
I added ko_KR locale files.
=> Add ko_KR locale 

packages/layout/src/BasicLayout.tsx, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/mobile.test.tsx
close https://github.com/ant-design/pro-components/issues/587
=> 🐛 fix(layout): fix split menu error in mobile mode

packages/layout/src/Header.tsx, packages/layout/src/PageContainer/index.tsx, packages/layout/src/layout.md, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/__snapshots__/pageContainer.test.tsx.snap, tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap, tests/layout/pageContainer.test.tsx
close https://github.com/ant-design/pro-components/issues/464
=> 💥 feat(layout): support fixedHeader for PageContainer

packages/table/src/Form/index.tsx, packages/table/src/Table.tsx, packages/table/src/useFetchData.tsx, tests/layout/settingDrawer.test.tsx, tests/table/column.test.tsx, tests/table/index.test.tsx, tests/table/pagination.test.tsx, tests/table/search.test.tsx
close https://github.com/ant-design/pro-components/issues/579
=> 🐛 fix(table): form should fisrt render

packages/field/src/index.tsx, packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/layouts/LightFilter/index.less, packages/list/src/demos/filter.tsx, packages/list/src/demos/layout.tsx, packages/list/src/demos/pagination.tsx, packages/list/src/demos/size.tsx, packages/list/src/index.less, packages/list/src/index.tsx, packages/list/src/list.md, packages/table/src/Form/index.less, packages/table/src/Form/index.tsx, packages/table/src/Table.tsx, packages/table/src/demos/lightfilter.tsx, packages/table/src/table.md, packages/utils/src/index.tsx, packages/utils/src/isDropdownValueType/index.ts, tests/list/__snapshots__/demo.test.ts.snap, tests/list/index.test.tsx, tests/table/__snapshots__/demo.test.ts.snap
支持 `<ProTable search={{ filterType: 'light' }} />`
=> feat: ProTable & ProList support LightFilter

packages/layout/src/layout.md
=> docs: fix PageContainer repeat issue

packages/skeleton/src/skeleton.md
=> docs: fix document typo

package.json, packages/layout/src/BasicLayout.tsx, packages/layout/src/Header.tsx, packages/layout/src/SiderMenu/BaseMenu.tsx, packages/layout/src/utils/utils.ts
close https://github.com/ant-design/pro-components/issues/640
=> 🐛 fix(layout): fix mix mode menu error for layout

packages/card/src/demos/basic.tsx, packages/card/src/style/index.less, tests/card/__snapshots__/demo.test.ts.snap, tests/skeleton/__snapshots__/demo.test.ts.snap
=> fix: card title font size

packages/form/src/components/Text/index.tsx
=> 📖 docs: 修正password拼写错误

packages/table/src/index.tsx
=> ✨ feat(provide): 导出 ConfigProviderWarp

packages/form/src/BaseForm/index.tsx, packages/form/src/components/Text/index.tsx, packages/form/src/interface.d.ts, tests/form/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/667
=> 🐛 fix(form): use antd default tooltip

packages/form/src/components/UploadButton/index.tsx, tests/form/__snapshots__/upload.test.tsx.snap, tests/form/upload.test.tsx
close https://github.com/ant-design/pro-components/issues/565
=> ✨ feat(form): ProFormUploadButton support diable

packages/field/src/components/Text/index.tsx, tests/field/__snapshots__/field.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/604
=> ✨ feat(field): allowClear default is true

packages/table/src/useFetchData.tsx
=> fix(pro-table): Fix pro-table 在卸载之后仍然设值，导致 react 报错

packages/table/src/table.md
=> chore: remove Listtoolbar demo

packages/form/src/components/Field/index.tsx, packages/table/src/Form/index.tsx, packages/table/src/demos/lightfilter.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/566
=> 🐛 fix(table): fix request no work error

packages/list/src/demos/filter.tsx, packages/list/src/index.tsx, packages/table/src/Form/index.tsx, packages/table/src/demos/batchOption.tsx, packages/table/src/demos/columnsStateMap.tsx, packages/table/src/demos/dataSource.tsx, packages/table/src/demos/form.tsx, packages/table/src/demos/intl.tsx, packages/table/src/demos/lightfilter.tsx, packages/table/src/demos/linkage_form.tsx, packages/table/src/demos/renderTable.tsx, packages/table/src/demos/search.tsx, packages/table/src/demos/search_backup.tsx, packages/table/src/demos/search_option.tsx, packages/table/src/demos/single.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/700
=> 📖 docs: better table demos

packages/form/src/components/Group/index.less
close https://github.com/ant-design/pro-components/issues/708
=> 💄 UI(form): fix group style error

packages/table/src/useFetchData.tsx, tests/table/index.test.tsx, tests/table/search.test.tsx
close https://github.com/ant-design/pro-components/issues/623
=> 🐛 fix(table): fix loading no work in success=false

packages/table/src/Form/index.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/valueEnum.test.tsx
close https://github.com/ant-design/pro-components/issues/621
=> 🐛 fix(table): table default remove width

packages/form/src/BaseForm/index.tsx, packages/form/src/FieldContext.tsx, packages/form/src/demos/base.tsx, packages/table/src/Table.tsx, packages/utils/src/conversionSubmitValue/index.ts, tests/form/__snapshots__/demo.test.ts.snap, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/559
=> 🐛 fix(form): fix name path no work problem

packages/table/src/Form/index.less
close https://github.com/ant-design/pro-components/issues/460
=> 🐛 fix(table): fix search item too long warning

packages/layout/src/SettingDrawer/index.tsx
close https://github.com/ant-design/pro-components/issues/658
=> 🐛 fix(layout): colorWeek use by body

packages/layout/src/PageContainer/index.tsx, packages/layout/src/layout.md, tests/table/search.test.tsx
close https://github.com/ant-design/pro-components/issues/726
=> fix(layout): fixedHeader=false, offsetTop should is 0 

packages/card/package.json, packages/descriptions/package.json, packages/field/package.json, packages/form/package.json, packages/layout/package.json, packages/table/package.json
close https://github.com/ant-design/pro-components/issues/715
close https://github.com/ant-design/pro-components/issues/646
close https://github.com/ant-design/pro-components/issues/595
=> 🐛 bug: fix @ant-design/pro-utils version error

packages/form/src/BaseForm/index.tsx, packages/form/src/demos/drawer-form.tsx, packages/form/src/demos/light-filter-bordered.tsx, packages/form/src/demos/light-filter-collapse.tsx, packages/form/src/demos/light-filter.tsx, packages/form/src/demos/modal-form.tsx, packages/form/src/demos/query-filter-vertical.tsx, packages/form/src/demos/query-filter.tsx, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/LightFilter/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, packages/form/src/layouts/QueryFilter/index.tsx, packages/form/src/layouts/StepsForm/StepForm.tsx, tests/form/drawerForm.test.tsx, tests/form/modalForm.test.tsx
close https://github.com/ant-design/pro-components/issues/724
close https://github.com/ant-design/pro-components/issues/721
=> ✨ feat(form): onFinish auto close modal

package.json, packages/form/src/BaseForm/index.tsx, packages/form/src/demos/query-filter.tsx, packages/form/src/layouts/StepsForm/StepForm.tsx, packages/form/src/layouts/StepsForm/index.tsx
close https://github.com/ant-design/pro-components/issues/758
close https://github.com/ant-design/pro-components/issues/754
=> 🐛 fix(loading): better loading set

packages/layout/src/TopNavHeader/index.less
| 修改前 | 修改后 |
| --- | --- |
| <img width="631" alt="image" src="https://user-images.githubusercontent.com/507615/96399170-490fbc00-1200-11eb-87c7-8c780538443d.png"> | <img width="689" alt="image" src="https://user-images.githubusercontent.com/507615/96399153-3f865400-1200-11eb-8526-469644a05c6b.png"> |
| <img width="729" alt="image" src="https://user-images.githubusercontent.com/507615/96399196-5b89f580-1200-11eb-96db-88294946b269.png"> | <img width="804" alt="image" src="https://user-images.githubusercontent.com/507615/96399269-8f651b00-1200-11eb-8a99-ef6438cb6b74.png"> |
=> 💄 style(layout): update Logo title color in light mode

packages/layout/src/Header.tsx, packages/layout/src/demos/_defaultProps.tsx, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/index.test.tsx
fix: [763](https://github.com/ant-design/pro-components/issues/763)
=> fix: mix layout hideInMenue bug

packages/card/src/card.md, packages/card/src/demos/colspan.tsx, packages/card/src/demos/inner.tsx, packages/card/src/index.tsx, tests/card/__snapshots__/demo.test.ts.snap, tests/skeleton/__snapshots__/demo.test.ts.snap, tests/skeleton/demo.test.ts
1. add flex direction property.
2. 纠正 skeloton 的 demo 测试指定成了card
=> feat(card): add card direction

packages/table/src/Table.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/770
close https://github.com/ant-design/pro-components/issues/789
=> 🐛 fix(layout): fix tableLayout no auto set to fixed

packages/layout/src/BasicLayout.tsx, packages/layout/src/SiderMenu/BaseMenu.tsx, packages/layout/src/defaultSettings.ts, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/index.test.tsx
close https://github.com/ant-design/pro-components/issues/772
=> ✨ feat(layout): layout support menu.loading

packages/card/src/style/index.less
=> fix(card): card padding

packages/layout/src/PageContainer/index.tsx, packages/table/src/table.md
=> fix(layout): fix PageContainer header ts definition

package.json, packages/form/src/components/Checkbox/index.tsx, packages/table/src/component/ListToolBar/index.less, packages/table/src/component/ListToolBar/index.tsx, packages/table/src/demos/single.tsx, tests/field/__snapshots__/field.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/__snapshots__/settingDrawer.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap, yarn.lock
close https://github.com/ant-design/pro-components/issues/818
=> 💄 UI: optimized styleo

packages/card/src/demos/inner.tsx, packages/card/src/index.tsx, packages/card/src/style/index.less
=> fix(card): fix collpase and inner style

packages/form/src/BaseForm/index.tsx, packages/form/src/demos/components-test.tsx, packages/form/src/index.tsx, packages/form/src/layouts/QueryFilter/index.tsx, packages/table/src/Form/index.tsx, packages/table/src/demos/linkage_form.tsx
close https://github.com/ant-design/pro-components/issues/833
=> fix(table): renderFormItem should run in form init

packages/form/src/layouts/StepsForm/index.tsx, packages/provider/src/locale/en_US.tsx, packages/provider/src/locale/es_ES.tsx, packages/provider/src/locale/fr_FR.tsx
=> feat(pro-form): localize stepsform submitter buttons texts

packages/layout/src/BasicLayout.tsx, packages/layout/src/utils/useCurrentMenuLayoutProps.ts, tests/layout/index.test.tsx
close https://github.com/ant-design/pro-components/issues/862
=> 🐛 fix(layout): fix current menu layout bug

packages/field/src/components/Select/index.tsx, tests/field/field.test.tsx
close https://github.com/ant-design/pro-components/issues/863
=> 🐛 fix(field): options should trigger  getOptions

packages/layout/src/GlobalHeader/index.tsx
close https://github.com/ant-design/pro-components/issues/886
=> 🐛 fix(layout): fix headerTheme no work error

packages/table/src/component/ListToolBar/HeaderMenu.tsx, tests/table/listtoolbar.test.tsx
close https://github.com/ant-design/pro-components/issues/796
=> ✨ feat(table): ListToolBar.menu support disabled

packages/form/src/layouts/StepsForm/index.tsx, tests/form/stepFormTest.test.tsx
close https://github.com/ant-design/pro-components/issues/725
=> ✨ feat(form): step form  onfisih support return boolean

packages/utils/src/transformKeySubmitValue/index.ts
close https://github.com/ant-design/pro-components/issues/898
=> 🐛 fix(form): fix transformKeySubmitValue namepath error

packages/field/src/components/FromNow/index.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
=> fromNow 增加 Tooltip 提示

packages/layout/src/BasicLayout.tsx, packages/layout/src/SiderMenu/BaseMenu.tsx, packages/layout/src/demos/DefaultOpenAllMenu.tsx, tests/layout/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/ant-design-pro/issues/7526
=> 🐛 fix(layout): fix the problem that openKeys does not take effect

packages/field/src/components/Select/index.tsx
close https://github.com/ant-design/pro-components/issues/919
=> 🐛 fix(field): new key gen function

packages/table/src/Form/index.tsx, packages/table/src/utils.tsx
close https://github.com/ant-design/pro-components/issues/911
=> 🐛 fix(table): name takes precedence over dataindex

packages/field/src/components/Select/LightSelect/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/921
=> 🐛 fix(field): support some props no work error

packages/layout/src/GlobalHeader/index.tsx
fix https://github.com/ant-design/pro-components/issues/684
=> fix: 修复mix模式下，顶部导航渲染bug

packages/form/src/layouts/QueryFilter/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/queryFilter.test.tsx, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/search.test.tsx
close https://github.com/ant-design/pro-components/issues/956
=> 💄 UI(form): add a empty label

packages/layout/src/PageContainer/index.less, packages/layout/src/demos/ghost.tsx, packages/layout/src/layout.md, tests/layout/__snapshots__/demo.test.ts.snap
PageContainer 配置 ghost 可以将页头切换为透明模式的时候内容 padding-top 应取消。
=> feat(layout): Feat/pagecontainer ghost

packages/descriptions/package.json
https://codesandbox.io/s/i1z4r?file=/index.tsx
=> fix: missing dependency use-json-comparison

packages/form/src/layouts/StepsForm/StepForm.tsx
close https://github.com/ant-design/pro-components/issues/1021
=> 🐛 fix(form): fix  stepForm formRef no work error

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/981
=> 🐛 fix(table): if propsRowSelection || tableAlertRender =0 no render dom

packages/descriptions/src/demos/columns.tsx, packages/field/src/field.md, packages/form/src/components/Field/index.tsx, packages/list/src/demos/filter.tsx, packages/table/src/Form/index.tsx, packages/table/src/Table.tsx, packages/table/src/component/ColumnSetting/index.tsx, packages/table/src/component/ToolBar/index.tsx, packages/table/src/container.tsx, packages/table/src/demos/ListToolBar/menu.tsx, packages/table/src/demos/ListToolBar/multipleLine.tsx, packages/table/src/demos/ListToolBar/no-title.tsx, packages/table/src/demos/ListToolBar/tabs.tsx, packages/table/src/demos/batchOption.tsx, packages/table/src/demos/columnsStateMap.tsx, packages/table/src/demos/config-provider.tsx, packages/table/src/demos/crud.tsx, packages/table/src/demos/dataSource.tsx, packages/table/src/demos/lightfilter.tsx, packages/table/src/demos/single.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/demo.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/1015
close https://github.com/ant-design/pro-components/issues/986
=> fix(table): fix the problem that the table rendering is not timely

packages/field/src/components/TextArea/index.tsx, tests/field/field.test.tsx
close https://github.com/ant-design/pro-components/issues/1019
=> 🐛 fix(field): textarea stopPropagation enter

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/731
close https://github.com/ant-design/pro-components/issues/917
=> fix(form): modal and drawer render to body

packages/form/src/BaseForm/createField.tsx, packages/table/src/demos/single-test.tsx, packages/table/src/demos/single.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1036
=> 🐛 fix(form): fix formItemProps no work error

packages/form/src/BaseForm/index.tsx, tests/form/__snapshots__/base.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/form/upload.test.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1038
ref https://stackoverflow.com/questions/1370021/why-does-forms-with-single-input-field-submit-upon-pressing-enter-key-in-input
=> 🐛 fix(form): do not trigger submit twice

packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/TimePicker/index.tsx
close https://github.com/ant-design/pro-components/issues/964
=> 🐛 fix(field): fix ProFormTimePicker value no moment error

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
trigger感觉不是一个好主意，加个样式
close https://github.com/ant-design/pro-components/issues/1040
=> fix: drawerForm&modalForm trigger 区域调整

package.json, packages/form/src/BaseForm/createField.tsx, packages/form/src/components/Field/index.tsx, packages/table/src/Form/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/table/search.test.tsx, yarn.lock
ref https://github.com/ant-design/pro-components/issues/740
ref https://github.com/ant-design/pro-components/issues/228
=> feat(table): table support fieldProps.onChange

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/633
=> 🐛 fix(table): fix filter sometime show 0 error

packages/form/src/layouts/QueryFilter/Actions.tsx, packages/form/src/layouts/QueryFilter/index.tsx, packages/table/src/demos/ListToolBar/basic.tsx, packages/table/src/demos/ListToolBar/menu.tsx, packages/table/src/demos/ListToolBar/multipleLine.tsx, packages/table/src/demos/ListToolBar/no-title.tsx, packages/table/src/demos/ListToolBar/tabs.tsx, packages/table/src/demos/batchOption.tsx, packages/table/src/demos/columnsStateMap.tsx, packages/table/src/demos/lightfilter.tsx, packages/table/src/demos/listToolBar.tsx, packages/table/src/demos/no-title.tsx, packages/table/src/demos/single.tsx, packages/table/src/demos/split.less, packages/table/src/demos/split.tsx, packages/table/src/demos/table-nested.tsx, packages/table/src/table.md, packages/utils/src/components/LabelIconTip/index.less, packages/utils/src/components/LabelIconTip/index.tsx, tests/card/__snapshots__/demo.test.ts.snap, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
=> fix(table): optimize table demos and table style.

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1115
=> fix(form): No longer generate redundant dom

packages/table/src/component/InlineErrorFormItem/index.tsx, packages/table/src/demos/editable-table.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1122
=> fix(table): fix editable table show rules error

packages/table/src/EditableTable.tsx, packages/table/src/demos/editable-table.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1124
=> 🐛 fix(table): fix Whitespace warning

packages/field/package.json, packages/field/src/components/Switch/index.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/demos/components-other-readonly.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1116
=> fix(form): fix setState() call inside `Field` error

packages/provider/src/locale/ar_EG.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap
Translation: Translate the missing variables.
=> 🌎 localization: Update ar_EG.tsx

packages/card/src/index.tsx
ProCard 增加 onClick属性
https://github.com/ant-design/pro-components/issues/1113
=> 💥 feat(card): add onClick

packages/table/src/component/useEditable.tsx, packages/table/src/table.md
close https://github.com/ant-design/pro-components/issues/1154
=> fix(table): support onlyAddOneLineAlertMessage and onlyOneLineEditorAlertMessage

packages/table/src/Form/index.tsx, packages/table/src/typing.ts
close https://github.com/ant-design/pro-components/issues/802
=> fix(table): fix protable form types error

packages/table/src/utils.tsx
在 EditableProTable中支持列的children
=> fix: support children of column in EditableProTable

packages/form/src/BaseForm/index.tsx, packages/table/src/Table.tsx, tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/1155
=> 🐛 fix(table): fix startEditable key=0 warning

packages/table/src/table.md, packages/table/src/typing.ts, packages/table/src/utils.tsx, packages/utils/src/index.tsx, packages/utils/src/typing.ts, tests/table/editor-table.test.tsx
支持editable属性
close https://github.com/ant-design/pro-components/issues/1142
=> 💥 feat(compiler): support editable

packages/form/src/demos/modal-form.tsx, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/drawerForm.test.tsx
close https://github.com/ant-design/pro-components/issues/1171
=> 🐛 fix(form): fix modalForm cancel button is invalid error

packages/field/src/components/Second/index.tsx, packages/field/src/demos/base.tsx, packages/field/src/index.tsx, packages/table/src/demos/valueTypeNumber.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/field/field.test.tsx, tests/table/__snapshots__/demo.test.ts.snap
=> feat(field): support new valueType `second`

packages/table/src/component/ColumnSetting/DndItem.tsx, packages/table/src/component/ColumnSetting/index.tsx, packages/table/src/component/ListToolBar/index.less, packages/table/src/component/ListToolBar/index.tsx, packages/table/src/container.tsx, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1133
=> 🐛 fix(table): fix toolbar setting provide error

packages/list/src/Item.tsx, tests/list/__snapshots__/index.test.tsx.snap, tests/list/index.test.tsx
close https://github.com/ant-design/pro-components/issues/969
=> fix(list): if title is null, remove header dom

packages/table/src/component/useEditable.tsx, packages/table/src/demos/editable-table.tsx
close https://github.com/ant-design/pro-components/issues/1189
=> 📖 docs: fix editable-table demo bug

packages/list/src/Item.tsx, packages/list/src/demos/expand.tsx
close https://github.com/ant-design/pro-components/issues/641
=> fix(list): actions support react node

packages/layout/src/demos/customize-collapsed.tsx, packages/layout/src/layout.md, tests/layout/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/ant-design-pro/issues/7662
=> docs: add customize collapsed demos

packages/table/src/Form/index.tsx, packages/table/src/demos/single-test.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1193
=> fix(table): fix formItemProps no work error

packages/table/src/utils.tsx, tests/table/__snapshots__/editor-table.test.tsx.snap
新增时 text 有可能为 undefined，这时会导致如下错误：
Uncaught Error: FormItem(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
=> fix: avoid exceptions when text is undefined

docs/components.md
=> docs: update docs/components.md

packages/form/src/BaseForm/createField.tsx, packages/form/src/form.md, packages/form/src/layouts/QueryFilter/index.tsx, packages/skeleton/src/skeleton.md, packages/table/src/table.md, packages/table/src/typing.ts
close https://github.com/ant-design/pro-components/issues/1042
=> fix(colsize): fix colsize warning

packages/layout/src/BasicLayout.less, packages/layout/src/BasicLayout.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/__snapshots__/pageContainer.test.tsx.snap, tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap, tests/layout/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1250
flex 真香
=> fix(layout): use ant class name

README.en-US.md, README.es-PR.md, README.md, README.zh-CN.md
Fix Issues and Pull requests url
=> docs: fix issues and pull requests url

packages/descriptions/package.json, packages/form/package.json, packages/layout/package.json, packages/utils/package.json
add required dependencies to package.json
=> fix(dependencies):add dependencies to pro-utils & pro-descriptions & pro-layout & pro-form

packages/layout/src/BasicLayout.tsx
close https://github.com/ant-design/ant-design-pro/issues/7718
=> fix(layout): Recalculate menu when pathname is changed

packages/layout/src/SiderMenu/index.less
=> 💄 UI(layout): Add transition effects to the ProLayout left menu

packages/utils/src/hooks/useDeepCompareEffect/index.ts
bug复现代码
https://codesandbox.io/s/interesting-burnell-mzps9?file=/src/App.js
=> fix: 修复新旧值均为map类型的等价判断，一直返回true的问题

packages/table/src/Table.tsx, packages/table/src/table.md, packages/table/src/typing.ts, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1310
=> 🐛 fix(table): change bordered to cardBorde

.umirc.js, packages/table/src/Form/index.tsx, packages/table/src/demos/single-test.tsx, packages/table/src/demos/single.tsx, packages/table/src/table.md, packages/table/src/typing.ts, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/99
终于来了
=> ✨ feat(table): support colSize

packages/form/src/form.md
=> fix(form): 修复ModalForm 和DrawerForm的编写错误

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/1247
=> 💥 feat(table): beforeSearchSubmit support pagination

packages/table/src/Table.tsx
fix [1335](https://github.com/ant-design/pro-components/issues/1335)
=> fix(table): 设置pageSize后,查询或重置没获取最新的pageSize

packages/table/src/typing.ts
=> chore: 事件 to 时间

packages/descriptions/package.json
=> chore: update peerDependencies from umi to antd

packages/form/src/components/Captcha/index.tsx, tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/1356
=> 🐛 fix(form):  run validateFields before onGetCaptcha

packages/form/src/components/FieldSet/index.tsx, packages/form/src/demos/light-filter.tsx, packages/form/src/layouts/LightFilter/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1215
close https://github.com/ant-design/pro-components/issues/699
=> fix(form): fix ProFormSet no work error

packages/list/src/index.tsx, packages/provider/src/index.tsx, packages/table/src/Table.tsx, packages/table/src/components/EditableTable/index.tsx, packages/table/src/demos/columnsStateMap.tsx, packages/table/src/demos/crud.tsx, packages/table/src/demos/dataSource.tsx, packages/table/src/demos/listToolBar.tsx, packages/table/src/demos/pollinga.tsx, packages/table/src/demos/rtl_table.tsx, packages/table/src/demos/single-test.tsx, packages/table/src/demos/single.tsx, packages/table/src/typing.ts, packages/table/src/utils.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/demo.tsx, tests/table/filter.test.tsx
close https://github.com/ant-design/pro-components/issues/1276
=> fix(table): fix onfilter no work error

package.json
close https://github.com/ant-design/pro-components/issues/1401
=> chore: add tsc script

packages/layout/src/components/PageContainer/index.tsx, tests/layout/__snapshots__/pageContainer.test.tsx.snap, tests/layout/pageContainer.test.tsx
close https://github.com/ant-design/ant-design-pro/issues/7743
=> fix(layout): fix props is null, no render pageheader

packages/card/src/index.tsx, packages/card/src/style/index.less, tests/card/__snapshots__/demo.test.ts.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
=> feat(card): support collapsible title

packages/table/src/utils.tsx
close https://github.com/ant-design/pro-components/issues/1406#issuecomment-751933680
=> fix(table): reloadAndRest should reset page index

packages/form/src/components/Checkbox/index.tsx, packages/form/src/components/Field/index.tsx, packages/form/src/components/Select/index.tsx, packages/table/src/components/Form/index.tsx, packages/table/src/defaultRender.tsx, packages/table/src/typing.ts, packages/table/src/utils.tsx, packages/utils/src/index.tsx, packages/utils/src/runFunction/index.ts, packages/utils/src/typing.ts, tests/table/__snapshots__/index.test.tsx.snap, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1414
=> ✨ feat(table): valueEnum support function

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx
close https://github.com/ant-design/pro-components/issues/1458
=> fix(form): add footer warning

packages/table/src/components/Form/index.tsx, packages/table/src/demos/single-test.tsx
close https://github.com/ant-design/pro-components/issues/1441#issuecomment-752010427
=> fix(table): fix colSize no work error

packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/Percent/index.tsx, packages/field/src/components/TimePicker/index.tsx
close https://github.com/ant-design/pro-components/issues/1451
=> fix(form): fix the problem of attribute priority

packages/table/src/components/Form/index.tsx, packages/table/src/demos/columnsStateMap.tsx, packages/table/src/demos/dynamic-settings.tsx, packages/table/src/utils.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1265
试了一下 sort(()=>0) 在不同的浏览器版本中不一样
=> fix(table): fix the compatibility problem of sorting

packages/card/src/style/index.less
close https://github.com/ant-design/pro-components/issues/1473
=> fix(card): fix the wrong background color issue

packages/form/src/components/Dependency/index.tsx, packages/form/src/demos/dependency.tsx, packages/form/src/index.tsx, tests/form/__snapshots__/base.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/462
=> feat(from): support ProFormDependency

packages/form/src/components/Submitter/index.tsx, packages/form/src/demos/login.tsx, packages/form/src/layouts/ModalForm/index.tsx
close https://github.com/ant-design/pro-components/issues/1463
=> fix(form): fix form submitButtonProps no work error

packages/field/src/index.tsx, packages/provider/src/index.tsx, tests/table/editor-table.test.tsx
close https://github.com/ant-design/pro-components/issues/1423
=> fix(table): fix fieldProps.onChange no work error

packages/field/src/components/Image/index.tsx, packages/field/src/demos/base.tsx, packages/field/src/demos/base_test.tsx, packages/field/src/field.md, packages/field/src/index.tsx, packages/table/src/demos/valueType.tsx, packages/utils/src/typing.ts, tests/field/__snapshots__/demo.test.ts.snap, tests/field/field.test.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1408
=> feat(field): support image valueType

packages/list/src/Item.tsx, packages/list/src/ListView.tsx, packages/list/src/demos/editable.tsx, packages/list/src/index.less, packages/list/src/index.tsx, packages/list/src/list.md, packages/table/src/Table.tsx, packages/table/src/utils.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/list/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1423
close https://github.com/ant-design/pro-components/issues/1365
=> fix(list): fix editable for list

packages/layout/src/components/SiderMenu/BaseMenu.tsx, packages/layout/src/demos/customize-collapsed.tsx, tests/layout/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1410
=> 📖 docs: add collapsed button demos

packages/provider/src/locale/en_US.tsx, packages/provider/src/locale/zh_CN.tsx, packages/utils/src/useEditableArray/index.tsx, packages/utils/src/useEditableMap/index.tsx
ref Issue #1343 
Please make a release asap once this PR is approved. Thanks!
如果PR审核通过请尽快做一个版本更新。谢谢！
=> feat(table): add 'internationalization for editabletable action' option

packages/form/src/BaseForm/createField.tsx, packages/form/src/demos/components-other-readonly.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1498
=> fix(form): fix form width no work error

packages/table/src/Table.tsx, packages/table/src/components/Form/index.tsx, packages/table/src/demos/single-test.tsx
close https://github.com/ant-design/pro-components/issues/1482
=> feat(table): reset will rest form values

packages/field/src/components/Options/index.tsx, packages/list/src/demos/selectedRow.tsx, packages/list/src/demos/size.tsx, tests/field/__snapshots__/field.test.tsx.snap, tests/field/field.test.tsx, tests/list/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1494
=> fix(filed): auto insert dom key

packages/field/src/index.tsx
close https://github.com/ant-design/pro-components/issues/1522
=> fix(table): add  exception handling

.github/workflows/ci.yml, .github/workflows/coverage.yml, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx
close https://github.com/ant-design/pro-components/issues/1524
=> fix(form): fix ModalForm and DrawerFrom props error

packages/table/src/components/EditableTable/demos/basic.tsx, packages/table/src/components/Form/index.tsx, packages/utils/src/transformKeySubmitValue/index.ts, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1504
=> fix(form): fix transform no work when namePath is array

packages/table/src/components/ListToolBar/index.less
close https://github.com/ant-design/pro-components/issues/1536
=> fix(table): fix hover dom style error

packages/field/src/components/Radio/index.less, packages/field/src/components/Radio/index.tsx, packages/form/src/components/Radio/index.tsx, packages/form/src/demos/components-other.tsx, packages/table/src/Table.tsx, packages/table/src/utils.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1338
=> fix(form): fix ProFormRadio.Group vertical style error

packages/list/src/Item.tsx, tests/list/__snapshots__/demo.test.ts.snap
close  https://github.com/ant-design/pro-components/issues/1089
=> fix(list): the action of a list is no longer bubbled

packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/BaseForm/index.tsx, packages/table/src/Table.tsx, packages/table/src/components/Form/index.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/index.test.tsx
ref https://github.com/ant-design/pro-components/issues/1515
=> ⚡️ performance: less render funtion

packages/field/src/components/Select/index.tsx, packages/table/src/demos/single.tsx, tests/field/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1565
=> fix(field): fix valueEnum disabled no work error

packages/table/src/components/EditableTable/index.tsx
close https://github.com/ant-design/pro-components/issues/1573
=> feat: editable table add tableViewRender

packages/form/src/demos/base.tsx, packages/utils/src/transformKeySubmitValue/index.ts, tests/demo.tsx, tests/form/base.test.tsx, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1574
close https://github.com/ant-design/pro-components/issues/1577
=>  fix(form): fix namePath is array error

packages/table/src/Table.tsx, packages/table/src/table.md, packages/table/src/typing.ts, packages/table/src/useFetchData.tsx, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1131
=> feat: table request add debounce wait

packages/form/src/BaseForm/index.tsx, packages/table/src/components/Form/index.tsx, packages/table/src/demos/single.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1588
=> fix(form): default render form

packages/form/src/BaseForm/index.tsx, packages/form/src/components/Submitter/index.tsx, tests/form/base.test.tsx, tests/form/queryFilter.test.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1590
=> fix(form): onFinish close loading when throw error

jest.config.js, package.json, packages/layout/package.json, packages/layout/src/components/SettingDrawer/index.tsx, packages/layout/src/demos/base.tsx, tests/layout/__snapshots__/settingDrawer.test.tsx.snap, tests/layout/settingDrawer.test.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/142
close  https://github.com/ant-design/ant-design-pro/issues/7209
=> fix(layout): use use-url-search-params hooks sync url

packages/field/src/components/Options/index.tsx, packages/table/src/Table.tsx, packages/table/src/components/EditableTable/demos/basic.tsx, packages/table/src/components/EditableTable/demos/real-time-editing.tsx, packages/table/src/components/EditableTable/index.md, packages/table/src/components/EditableTable/index.tsx, packages/utils/src/useEditableArray/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/editor-table.test.tsx
close https://github.com/ant-design/pro-components/issues/1603
close https://github.com/ant-design/pro-components/issues/1616#issuecomment-760762166
=> feat(table): table support editable.onValuesChange

packages/form/src/BaseForm/index.tsx, packages/form/src/components/Captcha/index.tsx, packages/form/src/components/Submitter/index.tsx, packages/form/src/demos/sync-to-url.tsx, packages/form/src/form.en-US.md, packages/form/src/form.md, packages/form/src/layouts/QueryFilter/index.tsx, packages/form/src/layouts/StepsForm/StepForm.tsx, packages/form/src/layouts/StepsForm/index.tsx, packages/layout/package.json, packages/list/src/Item.tsx, packages/table/package.json, packages/table/src/components/Form/index.tsx, packages/table/src/demos/single.tsx, packages/table/src/typing.ts, packages/table/src/useFetchData.tsx, tests/descriptions/index.test.tsx, tests/form/__snapshots__/base.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/form/base.test.tsx, tests/form/fieldSet.test.tsx, tests/layout/defaultSettings.ts, tests/layout/index.test.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/index.test.tsx, tests/util.ts, yarn.lock
close https://github.com/ant-design/pro-components/issues/317
close https://github.com/ant-design/pro-components/issues/1633
=> feat(form): support sync url

packages/descriptions/src/demos/data-source.tsx, packages/descriptions/src/descriptions.en-US.md, packages/descriptions/src/descriptions.md, tests/descriptions/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1645
=> docs: add dataSoruce descriptions demos

packages/form/src/components/ModalForm/index.en-US.md, packages/form/src/components/ModalForm/index.md, packages/form/src/demos/visible-on-visible-change.tsx, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/drawerForm.test.tsx, tests/form/modalForm.test.tsx
close https://github.com/ant-design/pro-components/issues/1649
=> fix(form): visible=true when simulate onVisibleChange

packages/descriptions/src/index.tsx, packages/field/src/components/Options/index.tsx
close https://github.com/ant-design/pro-components/issues/1647
=> fix(descriptions): fix items=null throw error

packages/list/src/Item.tsx, tests/list/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1652
=> fix(list): fix card list no support Avatar error

packages/form/src/BaseForm/index.tsx, packages/form/src/demos/base.tsx, packages/form/src/demos/drawer-form.tsx, packages/form/src/demos/light-filter.tsx, packages/form/src/demos/modal-form.tsx, packages/form/src/demos/query-filter.tsx, packages/form/src/demos/steps-from.tsx, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/LightFilter/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, packages/form/src/layouts/ProForm/index.tsx, packages/form/src/layouts/QueryFilter/index.tsx, packages/form/src/layouts/StepsForm/StepForm.tsx, packages/form/src/layouts/StepsForm/index.tsx
close https://github.com/ant-design/pro-components/issues/1638
=> fix(form): form supports generic types

packages/form/src/components/QueryFilter/index.en-US.md, packages/form/src/components/QueryFilter/index.md, packages/form/src/layouts/QueryFilter/index.tsx, tests/form/queryFilter.test.tsx
close https://github.com/ant-design/pro-components/issues/1006
=> feat(form): QueryForm support preserve

packages/form/src/BaseForm/index.tsx, packages/form/src/form.en-US.md, packages/form/src/form.md, packages/utils/src/conversionSubmitValue/index.ts, tests/form/base.test.tsx, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1005
=> feat(form): form support omitNil

packages/table/src/Table.tsx
=> fix(pro-table): on option search resetPageIndex

packages/form/src/demos/pro-form-editableTable.tsx, packages/form/src/form.md, packages/form/src/layouts/ProForm/index.tsx, packages/table/src/Table.tsx, packages/table/src/components/EditableTable/demos/real-time-editing.tsx, packages/table/src/components/EditableTable/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1706
=> feat(table): EditableProTable support onValuesChange

packages/form/src/layouts/StepsForm/index.tsx, packages/table/src/components/EditableTable/demos/custom.tsx, tests/form/stepFormTest.test.tsx, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1697
=> fix(form): fix StepsForm onFinish error

packages/utils/src/transformKeySubmitValue/index.ts, tests/utils/index.test.tsx
=> fix: ignore Blob type

packages/descriptions/src/index.tsx, tests/descriptions/__snapshots__/editor.test.tsx.snap
=> 🐛 fix(Description): fix title dom always exists

packages/card/src/card.md, packages/card/src/demos/colspan.tsx, packages/card/src/demos/hoverable.tsx, packages/card/src/index.tsx, packages/card/src/style/index.less, tests/card/__snapshots__/demo.test.ts.snap
1. 支持 卡片可 hover
2. 支持 colSpan = 0
=> feat: support card hoverable and colSpan = 0

.github/workflows/preview.yml
=> fix: revert to pull_request

packages/list/src/demos/base.tsx, packages/table/src/demos/pollinga.tsx, packages/table/src/table.md, packages/table/src/useFetchData.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1744
=> fix(table): fix the problem that it still executes when polling=false

packages/descriptions/src/index.tsx, packages/table/src/useFetchData.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/descriptions/__snapshots__/index.test.tsx.snap, tests/descriptions/index.test.tsx, tests/table/polling.test.tsx
close  https://github.com/ant-design/pro-components/issues/1738
=> feat(descriptions): descriptions Columns support order

packages/table/src/Table.tsx, tests/table/search.test.tsx
close https://github.com/ant-design/pro-components/issues/1761
=> fix(table): fix manualRequest always show loading error

packages/table/src/defaultRender.tsx
close https://github.com/ant-design/pro-components/issues/1724
=> fix(table): reset messageVariables to label

packages/form/src/components/StepsForm/demos/modal-step-form.tsx, packages/form/src/components/StepsForm/index.md, packages/form/src/layouts/StepsForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
fix "分布表单" to "分步表单" in document
=> fix: StepsForm document error

packages/list/src/index.less, packages/list/src/index.tsx, packages/table/src/Table.tsx, tests/list/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1668
=> feat(list): proList support checkox alert

packages/list/src/ListView.tsx, packages/list/src/demos/card-list.tsx, packages/list/src/demos/pagination.tsx, packages/list/src/demos/special.tsx, packages/list/src/index.tsx, tests/list/index.test.tsx
close  https://github.com/ant-design/pro-components/issues/1201#issuecomment-770359508
=> feat(list): ProList support renderItem

packages/table/src/useFetchData.tsx
close https://github.com/ant-design/pro-components/issues/1804
=> fix(table): fix table no close loading when error

packages/table/src/components/Form/index.less
close https://github.com/ant-design/pro-components/issues/1725
close https://github.com/ant-design/pro-components/issues/1278
=> fix(form): fix form control error

packages/descriptions/src/index.tsx, packages/table/src/defaultRender.tsx, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/editor-table.test.tsx
close  https://github.com/ant-design/pro-components/issues/1793
=> fix(table): fix editabletable initialValue alaway rewirte

packages/list/src/Item.tsx, packages/table/src/demos/customization-value-type.tsx
close https://github.com/ant-design/pro-components/issues/1794
=> fix(list): fix list item no key error

packages/table/src/useFetchData.tsx
close https://github.com/ant-design/pro-components/issues/1835
=> fix(table): fix table unmount warning

packages/layout/src/components/PageContainer/index.less
close https://github.com/ant-design/pro-components/issues/1811
=> fix(layout):  container add width:100%

packages/table/src/components/EditableTable/demos/real-time-editing.tsx, packages/table/src/utils.tsx, packages/utils/src/typing.ts, packages/utils/src/useEditableArray/index.tsx, tests/table/editor-table.test.tsx
close https://github.com/ant-design/pro-components/issues/702
=> feat(table): actionRef add pageInfo

packages/provider/src/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/base.test.tsx, tests/form/lightFilter.test.tsx, tests/layout/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/demo.test.ts.snap, tests/list/index.test.tsx, tests/table/__snapshots__/column.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/__snapshots__/valueEnum.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1867
close https://github.com/ant-design/pro-components/issues/1862
=> fix(provide): set default locale zh-CN

packages/table/src/components/Form/index.tsx
close https://github.com/ant-design/pro-components/issues/1861
close  https://github.com/ant-design/ant-design-pro/issues/8066
=> fix(table): no has colSize on renderFormItem

packages/form/src/components/Submitter/index.tsx, packages/form/src/layouts/QueryFilter/index.tsx, tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/1863
=> fix(form): fix searchText and resetText no work error

packages/table/src/defaultRender.tsx
close https://github.com/ant-design/pro-components/issues/1860
=> fix(form): fix error message no work error

packages/descriptions/src/descriptions.en-US.md, packages/descriptions/src/descriptions.md, packages/descriptions/src/index.tsx, packages/table/src/Table.tsx, packages/table/src/components/EditableTable/demos/custom.tsx, packages/table/src/components/EditableTable/index.en-US.md, packages/table/src/components/EditableTable/index.md, packages/utils/src/useEditableArray/index.tsx, tests/descriptions/editor.test.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1866
=> feat(table): editable support form config

packages/descriptions/src/demos/editable.tsx, packages/descriptions/src/index.less, packages/descriptions/src/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/descriptions/__snapshots__/editor.test.tsx.snap, tests/descriptions/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/ant-design-pro/issues/8064
=> fix(descriptions): fix descriptions editor error

packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/RangePicker/index.tsx, packages/field/src/components/TimePicker/index.tsx, packages/field/src/demos/base.tsx, packages/field/src/index.tsx, packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/BaseForm/createField.tsx, packages/form/src/components/DateRangePicker/index.tsx, packages/form/src/components/DateTimeRangePicker/index.tsx, packages/form/src/components/FieldSet/demos/components-other.tsx, packages/form/src/components/FieldSet/index.md, packages/form/src/components/QueryFilter/demos/light-filter.tsx, packages/form/src/components/TimePicker/index.tsx, packages/utils/src/components/FieldLabel/index.tsx, packages/utils/src/dateArrayFormatter/index.tsx, packages/utils/src/index.tsx, packages/utils/src/typing.ts, tests/field/__snapshots__/demo.test.ts.snap, tests/field/field.test.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/lightFilter.test.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
close  https://github.com/ant-design/pro-components/issues/1700
close https://github.com/ant-design/pro-components/issues/1753
close https://github.com/ant-design/pro-components/issues/1496
=> feat(field): support timeRange

packages/form/src/BaseForm/index.tsx
close https://github.com/ant-design/pro-components/issues/1847
=> fix(table): fix the problem of onInit call sequence

packages/provider/src/locale/tr_TR.tsx
=> Update tr_TR.tsx locale for provider

packages/form/src/BaseForm/createField.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/components/FieldSet/index.en-US.md, packages/form/src/components/FieldSet/index.md, packages/form/src/components/List/index.less, packages/form/src/components/List/index.tsx, packages/form/src/demos/list.tsx, packages/form/src/form.md, packages/form/src/index.tsx, packages/form/src/layouts/LightFilter/index.tsx, packages/utils/src/conversionSubmitValue/index.ts, tests/form/__snapshots__/demo.test.ts.snap, tests/form/formList.test.tsx, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/463
close https://github.com/ant-design/pro-components/issues/1100
=> feat(form): support form list

packages/card/src/card.md, packages/descriptions/src/descriptions.md, packages/form/src/components/FieldSet/index.md, packages/form/src/components/ModalForm/index.md, packages/form/src/components/QueryFilter/index.md, packages/form/src/components/StepsForm/index.md, packages/form/src/form.md, packages/layout/src/components/PageContainer/index.md, packages/layout/src/layout.md, packages/list/src/list.md, packages/skeleton/src/skeleton.md, packages/table/src/table.md
所有 demo 添加 title 属性，避免资产元数据中没有标题。
=> feat: add title for all demos

packages/field/src/components/Select/SearchSelect/index.tsx, packages/form/src/components/Select/index.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/field/__snapshots__/field.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1934
=> fix(filed): fix select show showArrow error

packages/field/src/components/Select/SearchSelect/index.tsx, packages/form/src/components/Select/index.tsx, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/field/__snapshots__/field.test.tsx.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/1901
=> fix(form):  modelForm and DrawerForm stopPropagation

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/1894
=> fix(table): export Table.Summary

packages/layout/src/components/SiderMenu/BaseMenu.tsx, packages/table/src/Table.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/457
=> fix(layout): menu item add title config

packages/form/src/layouts/QueryFilter/index.tsx
close https://github.com/ant-design/pro-components/issues/1283
=> fix(form): fix breakpoint xl width error

packages/field/src/components/Select/SearchSelect/index.tsx
close https://github.com/ant-design/pro-components/issues/1950
=> fix(form): fix error onchange params

packages/form/src/components/FieldSet/demos/components-other.tsx
修复 ProForm demo中 相对路径引入  TimePicker 的问题。
=> fix(proform): ProFormTimePicker relatvie import

packages/layout/src/components/SettingDrawer/LayoutChange.tsx, packages/layout/src/defaultSettings.ts, packages/table/src/useFetchData.tsx, tests/layout/settingDrawer.test.tsx
close https://github.com/ant-design/pro-components/issues/1948
=> fix(layout): layout sync url diff params

docs/faq.md
close #1844
抄袭了一下antd的一些东西
我起了个头，从issues里面拉了一些东西过来。
具体还是要等大佬一锤定音。
=> 🎨 chore: add FAQ (#1844)

packages/field/src/index.tsx, packages/form/src/BaseForm/createField.tsx, packages/form/src/demos/login.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/ant-design-pro/issues/8117
close https://github.com/ant-design/pro-components/issues/1973
=> fix(form): fix placeholder no work error

packages/list/src/index.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/index.test.tsx.snap, tests/table/__snapshots__/demo.test.ts.snap
Closes: https://github.com/ant-design/pro-components/issues/1911
=> fix(list): list selectedRow

packages/form/src/components/FieldSet/index.md, packages/form/src/components/List/index.tsx, packages/form/src/demos/list.tsx, packages/table/src/demos/dynamic-settings.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/formList.test.tsx
close https://github.com/ant-design/pro-components/issues/1985
=> fix(form): form list support formlist

packages/form/src/BaseForm/LightWrapper/index.tsx, packages/utils/src/components/FieldLabel/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/lightFilter.test.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/1975
=> fix(form): fix ligthfilter label error

packages/field/src/components/Select/SearchSelect/index.tsx, tests/table/__snapshots__/valueEnum.test.tsx.snap, tests/table/valueEnum.test.tsx
close https://github.com/ant-design/pro-components/issues/2001
=> fix(from): should support disable

packages/list/src/index.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/2031
=> fix(list): default close rowSelection

packages/descriptions/src/demos/editable.tsx, packages/descriptions/src/index.tsx
close https://github.com/ant-design/pro-components/issues/2033
=> fix(description): description support editableUtils

packages/field/src/components/Select/SearchSelect/index.tsx, packages/form/src/components/Select/index.tsx, tests/table/__snapshots__/valueEnum.test.tsx.snap
close https://github.com/ant-design/ant-design-pro/issues/8136
=> fix(select): no overwirtter defalut select props

packages/field/src/components/Select/SearchSelect/index.tsx, packages/field/src/demos/base.tsx, packages/field/src/demos/base_test.tsx, packages/field/src/index.tsx, packages/utils/src/index.tsx, packages/utils/src/typing.ts, tests/field/__snapshots__/demo.test.ts.snap, tests/field/fixtures/demo.tsx
close https://github.com/ant-design/pro-components/issues/2066
close https://github.com/ant-design/pro-components/issues/1994
=> feat(form): select optipn support optGroup

packages/form/src/components/Group/demos/list.tsx, packages/form/src/components/List/index.tsx
close https://github.com/ant-design/pro-components/issues/2046
=> fix(form): FormList support rules

packages/field/src/components/Digit/index.tsx, packages/form/src/BaseForm/createField.tsx, packages/form/src/components/Digit/index.tsx, packages/form/src/components/FieldSet/demos/components-other.tsx, packages/form/src/components/Group/demos/list.tsx, tests/field/__snapshots__/demo.test.ts.snap, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2050
=> fix(form): fix ProFormDigit width no work error

packages/form/src/components/DateTimeRangePicker/index.tsx
close https://github.com/ant-design/pro-components/issues/2073
=> fix(form): fix ProFormDateTimeRangePicker filedProps error

packages/list/src/demos/base.tsx, packages/list/src/index.tsx, packages/table/src/Table.tsx, packages/table/src/demos/dynamic-settings.tsx, packages/table/src/typing.ts, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2076
=> fix(table): fix tooltip no work error

packages/utils/src/conversionSubmitValue/index.ts
fix https://github.com/ant-design/pro-components/issues/2071
=> fix(utils): support value of BLOB array types

packages/form/src/components/Group/demos/nested-list.tsx, packages/form/src/components/List/index.tsx, packages/provider/src/locale/pt_BR.tsx, tests/form/formList.test.tsx
close https://github.com/ant-design/pro-components/issues/2061
close https://github.com/ant-design/pro-components/issues/2062
=> fix(form): fix form list copy no work error

packages/field/src/demos/base_test.tsx, packages/field/src/index.tsx, tests/field/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2099
=> fix(field): valueType 为对象时 不走 空值判断

packages/form/src/components/Dependency/index.tsx, packages/form/src/components/Group/demos/nested-list.tsx, packages/form/src/components/List/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/formList.test.tsx
close https://github.com/ant-design/pro-components/issues/2020
=> fix(list): fix nested list copy no work error

packages/form/src/BaseForm/index.tsx
close https://github.com/ant-design/pro-components/issues/2101
=> fix(form): fix form dateFormatter no export error

packages/list/src/Item.tsx
close https://github.com/ant-design/pro-components/issues/2120
=> fix(form): fix list key no had error

packages/form/src/components/List/index.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/2131
=> fix(form): fix copy trigger rerender error

packages/list/src/Item.tsx, packages/list/src/ListView.tsx, packages/list/src/demos/base.tsx, packages/list/src/index.less, packages/list/src/index.tsx, packages/list/src/list.md, tests/list/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/index.test.tsx.snap
=> ✨ feat(list): support showExtra(#2090)

packages/field/src/components/Money/index.tsx, packages/provider/src/index.tsx, packages/provider/src/locale/sr_RS.tsx, packages/table/src/demos/intl.tsx
=> Add sr_RS locale

packages/form/src/layouts/QueryFilter/index.tsx
close https://github.com/ant-design/pro-components/issues/2167
=> fix(form): fix width<16, layout will change error

packages/form/src/components/DateRangePicker/index.tsx
close https://github.com/ant-design/pro-components/issues/2174
=> fix(form): fix ProFormDateRangePicker type error

packages/field/src/index.tsx, packages/table/src/components/EditableTable/demos/basic.tsx, packages/table/src/utils/cellRenderToFromItem.tsx, packages/utils/src/useEditableArray/index.tsx
close https://github.com/ant-design/pro-components/issues/2129
=> fix(form): fix text is 0, initialValue no work error

packages/form/src/components/List/index.less, packages/form/src/components/List/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close  https://github.com/ant-design/pro-components/issues/2162
=> fix(form): fix list form label no display error

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/drawerForm.test.tsx
close https://github.com/ant-design/pro-components/issues/2207
=> fix(form): fix drawer and modal from render error

packages/layout/src/components/PageContainer/demos/basic.tsx, packages/layout/src/components/PageContainer/demos/fixHeader.tsx, packages/layout/src/components/PageContainer/demos/hideBreadMenu.tsx, packages/layout/src/components/PageContainer/index.md, tests/layout/__snapshots__/demo.test.ts.snap
页容器 demo 的背景设置为灰色，强调 PageContainer 背景为透明。
=> docs: PageContainer demo background

packages/form/src/components/FieldSet/index.md
=> chore: update proform width info

packages/form/src/BaseForm/index.tsx
=> fix(proform): call synctourl props during onreset

packages/descriptions/src/demos/request.tsx, packages/descriptions/src/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/descriptions/__snapshots__/editor.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/2226
=> fix(descriptions): if label is null, no render lable

packages/table/src/components/ListToolBar/index.tsx
close https://github.com/ant-design/pro-components/issues/2262
=> fix(table): fix activeKey no work error

packages/list/src/Item.tsx, packages/list/src/ListView.tsx, packages/list/src/index.tsx, packages/table/src/typing.ts, packages/table/src/utils/genProColumnToColumn.tsx, tests/table/column.test.tsx
close https://github.com/ant-design/pro-components/issues/2188
=> fix(list): fix list no use dataIndex error

packages/table/src/index.tsx, packages/table/src/utils/cellRenderToFromItem.tsx, packages/table/src/utils/columnRender.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/2102
=> fix(table): fix textarea ellipsis no work error

packages/table/src/Table.tsx, packages/table/src/typing.ts, packages/table/src/useFetchData.tsx
close https://github.com/ant-design/pro-components/issues/2245
=> fix(table): fix pagination no work error

packages/utils/src/useEditableMap/index.tsx
close https://github.com/ant-design/pro-components/issues/2227
=> fix(descriptions): fix descriptions onsave no work where key is array

packages/form/src/layouts/StepsForm/index.less
close https://github.com/ant-design/ant-design-pro/issues/8248
=> fix(form): fix StepsForm min-width error

packages/form/src/BaseForm/createField.tsx, packages/form/src/components/Group/index.less, packages/form/src/index.less, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2330
=> fix(form): fix moblie style width is over

packages/form/src/components/List/index.less, packages/form/src/layouts/StepsForm/index.less
close https://github.com/ant-design/pro-components/issues/2162
=> fix(form): fix form list hidde label error

packages/form/src/components/UploadButton/index.tsx, packages/form/src/layouts/StepsForm/index.less
fix ProFrom 中 ProFormUploadButton组件 name 属性固定导致上传字段固定ERROR
=> fix ProFrom 中 ProFormUploadButton组件 name 属性固定导致上传字段固定ERROR

packages/field/src/components/Select/index.tsx
Issues related to #2311
fixed #2311
=> fix(field): Select component crash while using backslash

packages/table/src/Table.tsx, packages/table/src/typing.ts
=> feat(table): table column sorter supports field

packages/table/src/utils/cellRenderToFromItem.tsx
=> fix(table): fix text is 0, initialValue no work error

packages/table/src/components/EditableTable/index.md
=> chore: add creatorButtonText

packages/provider/src/index.tsx, packages/provider/src/locale/pl_PL.tsx
added polish locales
work is based on https://github.com/ant-design/pro-components/pull/1696 and https://github.com/ant-design/pro-components/pull/1290
=> 🇵🇱localization:  polish locales added for provider

packages/form/src/components/Group/index.tsx, packages/form/src/interface.d.ts
=> feat(form): group support align

packages/field/src/components/Select/SearchSelect/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/base.test.tsx
=> fix(filed): fix ProFormSelect onClear not searching (#2288)

packages/table/src/components/ListToolBar/index.less
=> fix(table): fix style error when getPopupContainer

packages/table/src/Table.tsx
=> fix(table): if  request is null,pageSize change no set datasoucre

docs/index.en-US.md, docs/index.md, packages/layout/src/Footer.tsx, packages/layout/src/layout.en-US.md, packages/layout/src/layout.md, tests/layout/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2459
=> fix(layout): default remove copyright

packages/form/src/components/UploadButton/index.tsx, packages/table/src/Table.tsx, tests/demo.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/2436
=> fix(table): use user config tableLayout

packages/form/src/BaseForm/createField.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/components/UploadButton/index.tsx, packages/table/src/Table.tsx, tests/demo.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/column.test.tsx
close https://github.com/ant-design/pro-components/issues/2442
close  https://github.com/ant-design/pro-components/issues/2382
=> fix(table): fix valueType no work error

packages/table/src/Table.tsx, packages/table/src/typing.ts
close https://github.com/ant-design/pro-components/issues/2297
=> fix(table): fix ProTable always have form error

packages/form/src/BaseForm/createField.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/FieldContext.tsx, packages/form/src/components/FieldSet/demos/components-other.tsx, packages/form/src/components/FormItem/index.tsx, packages/form/src/interface.d.ts, packages/utils/src/conversionSubmitValue/index.ts, tests/form/__snapshots__/demo.test.ts.snap, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/2230
=> fix(form): transform support format config

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx
close https://github.com/ant-design/pro-components/issues/2398
=> fix(form): drawer and modal add scrollLocker

packages/layout/src/Header.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/mobile.test.tsx.snap
close https://github.com/ant-design/ant-design-pro/issues/8313
close https://github.com/ant-design/ant-design-pro/issues/8326
=> fix(layout): fix headerTheme no work error when layotu=mix

packages/list/src/index.less
close https://github.com/ant-design/pro-components/issues/2494
=> fix(list): fix list item border error

.dumi/theme/layout.less, .dumi/theme/layout.tsx, packages/descriptions/src/demos/columns.tsx, packages/field/src/components/Money/index.tsx, packages/utils/src/getFieldPropsOrFormItemProps/index.tsx
=> fix(form) : support moneySymbol=false

packages/descriptions/src/demos/columns.tsx, packages/field/src/components/Money/index.tsx
close https://github.com/ant-design/pro-components/issues/2535
=> fix(form): fix moneySymbol no work error

packages/layout/src/components/SiderMenu/BaseMenu.tsx, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/index.test.tsx
close https://github.com/ant-design/pro-components/issues/2540
=> fix(layout): fix error loading style

packages/list/src/Item.tsx, packages/list/src/ListView.tsx, packages/list/src/demos/base.tsx, packages/list/src/index.tsx, packages/list/src/list.md, tests/list/index.test.tsx
=> feat(list): support onRow

packages/layout/src/BasicLayout.tsx
close https://github.com/ant-design/pro-components/pull/2573
=> fix(layout): routes change should reload menu

packages/descriptions/src/index.tsx, packages/field/src/components/Money/index.tsx, packages/table/src/utils/cellRenderToFromItem.tsx, packages/table/src/utils/columnRender.tsx, packages/utils/src/typing.ts, tests/field/field.test.tsx
close https://github.com/ant-design/pro-components/issues/2577
=> fix(form): support moneySymbol=undefined

packages/table/src/demos/single-test.tsx, packages/table/src/useFetchData.tsx, packages/table/src/utils/columnRender.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2513
=> fix(table): fix the problem of nested data reporting errors

docs/schema.md
=> fix(doc): document error

packages/field/src/components/Image/index.tsx
close https://github.com/ant-design/pro-components/issues/2581
=> fix(form): FieldImage support fieldProps

packages/provider/src/locale/ru_RU.tsx
Hello!
Please up to date russian locale for current version
=> 🌎 localization: Update ru_RU.tsx

packages/form/src/components/FieldSet/demos/form-fieldset.tsx, packages/form/src/components/FieldSet/index.tsx, packages/form/src/components/Group/index.en-US.md, packages/form/src/components/Group/index.md, packages/table/src/demos/dynamic-settings.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2434
=> feat(form): FieldSet support type=group

packages/descriptions/src/demos/columns.tsx, packages/field/src/components/Switch/index.tsx, packages/field/src/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2609
=> fix(form): switch add default props

packages/form/src/layouts/LightFilter/index.less, packages/table/src/components/ListToolBar/index.tsx
close https://github.com/ant-design/pro-components/issues/2606
=> fix: 修复 ProTable 轻量筛选，小屏幕下变形 #2637

packages/table/src/utils/genProColumnToColumn.tsx
close https://github.com/ant-design/pro-components/issues/2636
=> fix(table): only onFilter === true run defaultOnFilter

packages/form/src/components/SchemaForm/demos/customization-value-type.tsx, packages/form/src/components/StepsForm/demos/steps-from.tsx, packages/layout/src/defaultSettings.ts, packages/table/src/components/EditableTable/index.tsx, packages/table/src/utils/index.ts, tests/form/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/editor-table.test.tsx
fix https://github.com/ant-design/pro-components/issues/1180
=> fix(table): fix the style problem of the fixed new button

packages/form/src/components/SchemaForm/demos/customization-value-type.tsx, packages/form/src/components/StepsForm/demos/steps-from.tsx, packages/form/src/layouts/LightFilter/index.tsx, packages/layout/src/defaultSettings.ts, packages/table/src/utils/index.ts, tests/form/lightFilter.test.tsx
fix https://github.com/ant-design/pro-components/issues/2171
=> fix(form): LightFilter 折叠的ProFormFields行为异常

packages/field/src/components/Select/index.tsx
close https://github.com/ant-design/pro-components/issues/2662
=>  🐛 fix(form): fix react warning

packages/form/src/components/UploadButton/index.tsx
=> 🐛 fix(form): UploadButton support fileList (#2231)

packages/form/src/BaseForm/index.tsx, packages/table/src/components/Form/FormRender.tsx, packages/table/src/components/Form/index.tsx
close https://github.com/ant-design/pro-components/pull/2006
close https://github.com/ant-design/pro-components/issues/1234
close https://github.com/ant-design/pro-components/issues/2109
=> feat(table): support sync pageinfo to url

packages/form/src/components/UploadButton/index.tsx, tests/form/upload.test.tsx
=> 🐛 fix(form): UploadButton upload failed value is still modified

packages/descriptions/src/descriptions.en-US.md, packages/form/src/components/FieldSet/index.en-US.md, packages/form/src/components/Group/index.en-US.md, packages/form/src/components/ModalForm/index.en-US.md, packages/form/src/components/StepsForm/index.en-US.md, packages/form/src/form.en-US.md, packages/layout/src/components/PageContainer/index.en-US.md, packages/layout/src/components/PageContainer/index.md, packages/layout/src/layout.en-US.md, packages/table/src/components/EditableTable/index.en-US.md, packages/table/src/table.en-US.md
修复文档表格错乱；添加缺少的英语文档；英语文档应该指向英语版本链接
=> docs: improve docs

.umirc.js, yarn.lock
Close: https://github.com/ant-design/pro-components/issues/2722
=> fix: codesandbox no find dependency

packages/descriptions/src/demos/editable.tsx, packages/field/src/components/Rate/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2719
=> fix(form) : fix Rate text no work error

packages/descriptions/src/demos/columns.tsx, packages/descriptions/src/demos/editable.tsx, packages/descriptions/src/index.tsx, packages/utils/src/useEditableArray/index.tsx, packages/utils/src/useEditableMap/index.tsx
=> fix(Descriptions): fix Descriptions reset will set value

packages/layout/src/utils/getBreadcrumbProps.tsx
close https://github.com/ant-design/pro-components/issues/2645
close https://github.com/ant-design/ant-design-pro/issues/8413
close https://github.com/ant-design/ant-design-pro/issues/7987
=> fix(layout): do not use base

packages/descriptions/src/demos/columns.tsx, packages/descriptions/src/index.tsx, packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/RangePicker/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2664
=> fix(form): support fieldProps.format

packages/card/src/components/Loading/index.less, packages/card/src/demos/loading.tsx, tests/card/__snapshots__/demo.test.ts.snap
=> fix(card): card loading in layout center 

packages/list/src/demos/editable.tsx, packages/list/src/index.tsx
close https://github.com/ant-design/pro-components/issues/2757
=> fix(list): add editable props types

packages/field/src/components/Select/index.less, packages/field/src/components/Select/index.tsx
=> feat(form): select option support ellipsis(#2555)

packages/form/src/components/List/index.less
=> fix(form): space between button and form (#2767)

packages/table/src/useFetchData.tsx, packages/table/src/utils/genProColumnToColumn.tsx, packages/utils/src/useEditableArray/index.tsx
fix https://github.com/ant-design/pro-components/issues/2789
fix https://github.com/ant-design/pro-components/issues/2770
fix https://github.com/ant-design/pro-components/issues/2776
=> fix(table): if editableKeys change,should Cell Update

.github/workflows/preview-build.yml, packages/form/src/BaseForm/index.tsx, packages/form/src/demos/base.tsx, packages/form/src/form.en-US.md, packages/form/src/form.md, packages/layout/package.json, packages/layout/src/components/PageLoading/index.tsx, packages/table/src/Table.tsx, packages/table/src/utils/genProColumnToColumn.tsx, packages/utils/src/hooks/useFetchData/index.tsx, packages/utils/src/index.tsx
close https://github.com/ant-design/ant-design-pro/issues/8465
=> feat(form): form support request and params

packages/descriptions/src/index.tsx
=> fix(descriptions): Fix the problem of remounting every time you refresh

packages/form/src/layouts/StepsForm/index.tsx
close https://github.com/ant-design/pro-components/issues/2784
=> fix(form): fix formRef no work error

packages/card/src/components/Statistic/index.less
close https://github.com/ant-design/pro-components/issues/2814
=> fix(card): use antd less var for title

packages/field/src/components/Digit/index.tsx, packages/table/src/demos/single.tsx, tests/field/field.test.tsx
close https://github.com/ant-design/pro-components/issues/2804
=> fix(form): digit support formatter

packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/Digit/index.tsx, packages/field/src/components/Select/LightSelect/index.tsx, packages/field/src/components/Text/index.tsx, packages/field/src/components/TimePicker/index.tsx, packages/form/src/BaseForm/createField.tsx, packages/form/src/BaseForm/index.tsx, packages/form/src/components/Field/index.tsx, packages/form/src/components/UploadButton/index.tsx, packages/form/src/components/UploadDragger/index.tsx, packages/form/src/index.tsx, packages/form/src/interface.d.ts, packages/table/src/components/EditableTable/demos/basic.tsx, packages/table/src/components/EditableTable/index.tsx, packages/table/src/demos/single.tsx, packages/table/src/utils/cellRenderToFromItem.tsx, packages/utils/src/conversionSubmitValue/index.ts, tests/__snapshots__/doc.test.ts.snap, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/field/field.test.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/__snapshots__/schemaForm.test.tsx.snap, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/table/editor-table.test.tsx, yarn.lock
close https://github.com/ant-design/pro-components/issues/2793
=> feat(table):  eidt table use Proform

packages/list/src/index.tsx
=> feat(list): list support locale(#2828)

packages/form/src/components/List/index.less
=> fix(form): The label is displayed when the createButton above（#2786）

packages/table/src/utils/genProColumnToColumn.tsx
=> fix(table): fix table shouldUpdate

packages/utils/src/isDropdownValueType/index.ts, tests/utils/index.test.tsx
fix(table): dateRange render wrong with light mode
=> fix(table): dateRange render wrong with light mode

package.json, packages/form/package.json
=> fix: build error

packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/components/QueryFilter/demos/light-filter-footer.tsx, packages/form/src/components/QueryFilter/index.md, packages/form/src/interface.d.ts, packages/form/src/layouts/LightFilter/index.tsx, packages/utils/src/components/DropdownFooter/index.tsx, packages/utils/src/components/FilterDropdown/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/lightFilter.test.tsx
=> feat(form): LightFilter support footer (#2794)

packages/form/src/components/StepsForm/demos/add-or-edit-step-form.tsx, packages/form/src/components/StepsForm/index.en-US.md, packages/form/src/components/StepsForm/index.md
看了源码才知道怎么去给分布表单设置值。觉得略坑。写个demo帮助后面的人规避这个问题
=> docs: 添加StepForm在编辑场景下的的示例

packages/form/src/demos/formRef.tsx, packages/form/src/form.md, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap
ProForm 添加 formRef 示例，很多同学不清楚怎么用 formRef 。
=> chore(form): add formRef demo

packages/layout/src/BasicLayout.tsx, tests/layout/index.test.tsx
close https://github.com/ant-design/ant-design-pro/issues/8501
=> fix(layout): fix menu params alway run error

docs/components.en-US.md, docs/components.md, packages/card/src/type.ts, packages/descriptions/src/index.tsx, packages/form/src/interface.d.ts, packages/list/src/index.tsx, packages/table/src/components/ListToolBar/index.tsx, packages/table/src/components/ToolBar/index.tsx, packages/table/src/typing.ts, packages/utils/src/components/LabelIconTip/index.tsx, packages/utils/src/typing.ts, tests/card/__snapshots__/demo.test.ts.snap, tests/descriptions/__snapshots__/demo.test.ts.snap, tests/form/base.test.tsx, tests/list/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/utils/__snapshots__/index.test.tsx.snap, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/2866
=> feat(form): support more tooltip props

packages/table/src/table.md, packages/utils/src/transformKeySubmitValue/index.ts, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/2937
=> fix(table): support three levels of nesting

packages/form/src/components/ModalForm/demos/drawer-form-nested.tsx, packages/form/src/components/ModalForm/index.en-US.md, packages/form/src/components/ModalForm/index.md, packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/2894
=> fix(form): fix scrollLocker no unlock error

packages/table/src/utils/columnRender.tsx, packages/table/src/utils/genProColumnToColumn.tsx
=> fix(table): fix tree table no work error

packages/form/src/BaseForm/LightWrapper/index.tsx, packages/form/src/components/Field/index.tsx, packages/form/src/components/SchemaForm/index.tsx
close https://github.com/ant-design/pro-components/issues/2902
close https://github.com/ant-design/pro-components/issues/2917
=> fix(table): fix onChange multiple calls error

packages/descriptions/src/descriptions.en-US.md, packages/descriptions/src/descriptions.md, packages/table/README.md, packages/table/src/components/EditableTable/demos/basic.tsx, packages/table/src/components/EditableTable/index.en-US.md, packages/table/src/components/EditableTable/index.md, packages/table/src/table.en-US.md, packages/utils/src/useEditableArray/index.tsx, packages/utils/src/useEditableMap/index.tsx, tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2946
close https://github.com/ant-design/pro-components/issues/2251
close https://github.com/ant-design/pro-components/issues/2251
=> feat(table): onsave support origin data and no merge record

packages/form/src/components/Select/index.tsx
=> fix(form): add optionItemRender types

packages/form/src/demos/config-provider.tsx, packages/form/src/layouts/StepsForm/index.tsx, packages/provider/src/index.tsx, tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/2805
=> fix(form) : stepform support intl

packages/table/src/utils/columnRender.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/__snapshots__/index.test.tsx.snap
=> fix(table): fix table ellipsis automatically (#2948)

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/2446
=> fix(table): SelectedRowKeys受控处理selectRows (#2446)

packages/table/src/Table.tsx
close https://github.com/ant-design/pro-components/issues/2966#issue-914615492
=> fix(table): fix table rowselection bug when set false

packages/form/src/components/Captcha/index.tsx
close https://github.com/ant-design/pro-components/issues/2968
=> fix(form): fix ProFormCaptcha now work error

packages/table/src/components/Dropdown/index.tsx, packages/table/src/table.md
=> feat(table): TableDropdown support all Menu.Item

packages/form/src/components/SchemaForm/index.tsx, packages/table/src/Table.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/2986
=> fix(table): hideInForm true的时候，hideInSearch失效 (#2986)

packages/form/src/BaseForm/index.tsx, packages/form/src/components/ModalForm/demos/modal-form-submitter.tsx, packages/form/src/components/ModalForm/index.md, packages/form/src/layouts/ModalForm/index.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/form/modalForm.test.tsx
=> feat(form): ModalForm support footer is null

packages/table/src/useFetchData.tsx, tests/table/pagination.test.tsx
close https://github.com/ant-design/pro-components/issues/2212
=> fix(table): 处理分页问题 (#2212)

packages/descriptions/src/demos/format.tsx, packages/descriptions/src/descriptions.md, packages/field/src/components/DatePicker/index.tsx, packages/field/src/components/FromNow/index.tsx, packages/field/src/components/RangePicker/index.tsx, packages/field/src/components/TimePicker/index.tsx, tests/descriptions/__snapshots__/demo.test.ts.snap, tsconfig.json
close https://github.com/ant-design/pro-components/issues/2959
=> fix(descriptions): fix descriptions fomart error

packages/form/src/interface.d.ts
=> fix(form): fix ProForm.Group size typescript(#3004)

packages/form/src/components/Dependency/index.tsx, packages/form/src/components/Group/demos/dependency2.tsx, packages/form/src/components/Group/index.md, tests/form/__snapshots__/demo.test.ts.snap, tests/form/formList.test.tsx
close https://github.com/ant-design/pro-components/pull/2909
=> fix(form): fix ProFormDependency missing some dependency values

packages/field/src/components/Switch/index.tsx, packages/form/src/BaseForm/createField.tsx, packages/provider/src/locale/en_US.tsx, packages/provider/src/locale/zh_CN.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/mobile.test.tsx, tests/table/__snapshots__/demo.test.ts.snap, tests/table/__snapshots__/editor-table.test.tsx.snap, tests/table/__snapshots__/index.test.tsx.snap, tests/util.ts
close https://github.com/ant-design/pro-components/issues/3005
=> fix(form): switch  width style fixed

packages/form/src/layouts/DrawerForm/index.tsx, packages/form/src/layouts/ModalForm/index.tsx, tests/form/drawerForm.test.tsx
close https://github.com/ant-design/pro-components/issues/3016
close https://github.com/ant-design/pro-components/issues/2980
close https://github.com/ant-design/pro-components/issues/2972
=> fix(form): use same antd lock

packages/layout/src/components/SiderMenu/BaseMenu.tsx, tests/form/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/demo.test.ts.snap, tests/layout/__snapshots__/index.test.tsx.snap, tests/layout/__snapshots__/mobile.test.tsx.snap, tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap
Reverts ant-design/pro-components#2983
=> Revert "fix(layout) : menu icon use antd  code style"

packages/field/src/components/Select/index.tsx
=> fix(form): fix regular match

packages/table/src/table.md
docs: table columns add hideInDescriptions
=> docs(table): add hideInDescriptions

packages/field/src/components/Select/SearchSelect/index.tsx, packages/form/src/components/FieldSet/demos/search-select.tsx
修复 labelInValue 为 false 时，autoClearSearchValue 设置为 true 无效
=> fix(field): autoClearSearchValue no work

packages/list/src/index.less
close https://github.com/ant-design/pro-components/issues/3053
=> fix(prolist): title&description wordBreak
