ant-design/pro-components

- packages/table/src/utils/index.ts
> fix(table): fix mergePagination order (#2985)

- packages/form/src/demos/form-layout.tsx
- packages/form/src/form.md
- tests/form/__snapshots__/demo.test.ts.snap
> feat(form): add layout demo

- packages/descriptions/src/descriptions.md
close https://github.com/ant-design/pro-components/issues/3073
> docs: update Descriptions demos

- packages/form/src/components/SchemaForm/demos/embed.tsx
- packages/form/src/components/SchemaForm/index.md
- packages/form/src/components/SchemaForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3067
> feat(form) : support Embed mode

- packages/table/src/components/ListToolBar/index.tsx
- packages/table/src/components/ToolBar/index.tsx
- tests/table/listtoolbar.test.tsx
close https://github.com/ant-design/pro-components/issues/3093
> fix(table): fix onSearch no work error

- packages/field/src/components/Select/SearchSelect/index.tsx
- packages/field/src/components/Select/index.tsx
- packages/field/src/demos/base.tsx
- packages/field/src/demos/base_test.tsx
- packages/form/src/demos/base.tsx
- packages/utils/src/typing.ts
- tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/3040
> fix(form): fix select optionGroup no filter error

- packages/field/src/components/Checkbox/index.less
close https://github.com/ant-design/pro-components/issues/3096
> fix(form): fix Group vertical style error

- packages/layout/package.json
- packages/layout/src/components/SettingDrawer/index.tsx
- packages/layout/src/defaultSettings.ts
- packages/layout/src/demos/base.tsx
- tests/layout/settingDrawer.test.tsx
- yarn.lock
- fix(layout): defaultSettings do not set menu locale
- use new style
> fix(layout): defaultSettings do not set menu locale

- packages/table/src/utils/index.ts
Reverts ant-design/pro-components#3050
close https://github.com/ant-design/pro-components/issues/3110
> Revert "fix(table): fix mergePagination order (#2985)"

- packages/layout/src/components/WaterMark/demos/frontend.tsx
- packages/layout/src/components/WaterMark/index.md
- tests/layout/__snapshots__/demo.test.ts.snap
> feat(layout): add WaterMark demo

- docs/schema.md
- packages/field/src/components/Select/index.tsx
close https://github.com/ant-design/pro-components/issues/3158
> fix(select): fix FieldSelect request warning

- packages/list/src/index.tsx
- packages/table/src/Table.tsx
- tests/layout/__snapshots__/demo.test.ts.snap
> 🐛 fix(list): List onChange called multiple times

- packages/table/src/table.md
> chore: add initialValue doc

- packages/list/src/list.md
> 📝 docs: add ProList batch operations

- packages/list/package.json
> 🎨 chore(list): update depend rc-resize-observer

- packages/form/src/components/SchemaForm/demos/schema.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/utils/src/typing.ts
- tests/form/__snapshots__/demo.test.ts.snap
> ✨ feat(form): feat new valueType -> divider

- packages/form/src/components/Dependency/index.tsx
- packages/list/src/demos/editable.tsx
- packages/utils/src/transformKeySubmitValue/index.ts
- packages/utils/src/useEditableArray/index.tsx
- tests/utils/index.test.tsx
> fix(table): fix onSave will merge origin data error

- packages/form/src/components/StepsForm/index.md
- tests/form/stepFormTest.test.tsx
- tests/table/__snapshots__/demo.test.ts.snap
> 📝 docs: add StepForm onFinish description

- packages/form/src/BaseForm/createField.tsx
- packages/form/src/components/Rate/index.tsx
- packages/form/src/components/StepsForm/index.md
- packages/form/src/components/Text/index.tsx
- tests/form/stepFormTest.test.tsx
- tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3161
> fix(form): proform onValuesChange 触发两次

- packages/form/src/components/StepsForm/demos/steps-from.tsx
- packages/form/src/layouts/StepsForm/StepForm.tsx
- packages/form/src/layouts/StepsForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3214
close https://github.com/ant-design/pro-components/issues/3167
> feat(form): StepForm support step props

- packages/provider/src/locale/zh_TW.tsx
also moneySymbol, editableTable in zh_TW
> 🌍️locale(form): add lightFilter in zh_TW.tsx

- packages/form/src/components/UploadDragger/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/upload.test.tsx
> fix: proformUploadDragger padding

- .umirc.js
> 📝 docs: Add SchemaForm/index in english doc

- packages/table/src/components/EditableTable/index.en-US.md
- packages/table/src/components/EditableTable/index.tsx
close https://github.com/ant-design/pro-components/issues/3245
> feat(table): record function add new params dataSource

- packages/form/src/layouts/QueryFilter/index.tsx
- packages/table/src/demos/no-option.tsx
- packages/table/src/table.md
- tests/table/__snapshots__/demo.test.ts.snap
**问题**
QueryFilter组件optionRender设为false，optionRender节点仍站位渲染问题.
**期待**
optionRender设为false时，应当不渲染该节点
> fix(QueryFilter): 修复QueryFilter组件optionRender设为false无效问题

- packages/table/src/container.tsx
> 🐛 fix(table): add ListToolBar column default value

- packages/form/src/components/TextArea/index.tsx
- tests/form/fieldSet.test.tsx
> 🐛 fix(form): ProFormTextArea onChange

- packages/form/src/components/FieldSet/index.tsx
close https://github.com/ant-design/pro-components/issues/3310
> fix(form): ProFormSelect can not get values

- packages/table/src/components/ColumnSetting/index.tsx
> 🐛 fix(table): hideInSetting can't work when fixed

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/drawerForm.test.tsx
- tests/form/modalForm.test.tsx
close https://github.com/ant-design/pro-components/issues/3309
> fix(form): fix DrawerForm&ModalForm submitter overwirter error

- .fatherrc.ts
Reverts ant-design/pro-components#3341
> Revert "🏰 chore(build): build remove import plugin"

- packages/form/src/BaseForm/createField.tsx
i fixed a bug
Reproduce bug：
```jsx
<ProForm>
<ProFormText
name="id"
rules={[{ min: 5 }]}
/>
</ProForm>
```
> fix: error info undefined while label is undefined

- docs/demos/valueType.tsx
- packages/form/src/components/SchemaForm/demos/valueType.tsx
- packages/form/src/components/Select/index.tsx
- tests/form/base.test.tsx
mode: `singe`  ->  mode: `single`
> fix: typo error

- packages/utils/src/typing.ts
> fix(table): 设置ProSchema的proFieldProps为可选属性

- packages/form/src/components/SchemaForm/index.tsx
> 🐛 fix(form): ProFormGroup value of label

- packages/form/src/components/ModalForm/demos/modal-form-reset.tsx
> 🐛 fix(form): ModalForm demo value of formRef

- packages/form/src/BaseForm/index.tsx
- packages/table/src/Table.tsx
- packages/table/src/container.tsx
- packages/table/src/table.en-US.md
- packages/table/src/table.md
- packages/table/src/typing.ts
close https://github.com/ant-design/pro-components/issues/3346
> feat(table): support defualt size

- packages/form/src/components/FieldSet/index.md
Optimize the following issues：
> docs: optimize FieldSet/index.md

- packages/form/src/index.tsx
- packages/utils/src/typing.ts
fix #3372.
#3374 只是规避了这个问题，没完全解决。
> fix(table): 订正 ProSchema 类型中 proFieldProps的类型 & 导出 ProFormItemProps 类型

- docs/faq.md
- packages/form/src/BaseForm/index.tsx
- packages/form/src/form.md
> 🏰 chore(form): delete warning

- packages/form/src/interface.d.ts
- packages/utils/src/index.tsx
- packages/utils/src/typing.ts
> chore(interface): add interface ProFieldProps and export

- packages/list/src/demos/search.tsx
- packages/list/src/index.less
- packages/list/src/index.tsx
- packages/list/src/list.md
- tests/list/__snapshots__/demo.test.ts.snap
- tests/list/__snapshots__/index.test.tsx.snap
- 添加列表查询 demo
- 调整 ProList 的 padding 和 background。
调整后查询表单效果和 ProTable 一致。
> feat(list): 添加列表查询 demo

- packages/table/src/table.md
> 📝 docs(table): add alwaysShowAlert description

- packages/table/src/Table.tsx
> 🐛 fix(table): rowSelection rowKey of default value

- packages/field/src/components/Select/SearchSelect/index.tsx
> fix(form): ProFormSelect: can not search after triggered clear event

- packages/form/src/BaseForm/index.tsx
- packages/list/src/index.tsx
- packages/table/src/components/ListToolBar/index.less
- packages/table/src/components/ListToolBar/index.tsx
- tests/list/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/index.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/3370
> fix(table): 添加滚动条，防止小屏幕下溢出

- packages/form/src/components/List/index.tsx
close https://github.com/ant-design/pro-components/issues/3304
> feat(form): FormList itemRender support index

- packages/form/src/components/FormItem/index.tsx
close https://github.com/ant-design/pro-components/issues/3422
> fix(form): ProFormItem work like Form.Item

- packages/table/src/utils/cellRenderToFromItem.tsx
- packages/table/src/utils/columnRender.tsx
- packages/utils/src/transformKeySubmitValue/index.ts
- tests/demo.tsx
close https://github.com/ant-design/pro-components/issues/3447
> fix(table): fix typo entry -> entity

- packages/table/src/Table.tsx
- packages/table/src/components/ColumnSetting/index.less
- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/container.tsx
- packages/table/src/utils/genProColumnToColumn.tsx
- tests/table/columnSetting.test.tsx
close https://github.com/ant-design/pro-components/issues/3441
close https://github.com/ant-design/pro-components/issues/3424
close https://github.com/ant-design/pro-components/issues/3336
> feat(table): support column.chilren render

- packages/layout/src/components/PageContainer/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/pageContainer.test.tsx.snap
- tests/layout/__snapshots__/pageHeaderWarp.test.tsx.snap
- tests/layout/pageContainer.test.tsx
> fix(PageContainer): className prop should not be passed to its page header

- packages/provider/src/index.tsx
- packages/provider/src/locale/en_GB.tsx
- packages/table/src/demos/intl.tsx
> En gb locale

- packages/field/src/components/Percent/index.tsx
- tests/field/field.test.tsx
更新内容： 
1. 修复formatter的正则会给prefix的数字加逗号
2. 修复parser正则处理魔法prefix
> fix(field-percent): fix parser and formatter regexp #3459

- packages/form/src/components/FormItem/index.tsx
- tests/form/formitem.test.tsx
close https://github.com/ant-design/pro-components/issues/3513
> fix(form): fix ProForm onBlur no work error

- docs/schema.md
- packages/field/src/components/Select/index.tsx
- packages/form/src/BaseForm/createField.tsx
- packages/form/src/BaseForm/index.tsx
- packages/form/src/FieldContext.tsx
- packages/form/src/components/Field/index.tsx
- packages/form/src/components/FormItem/index.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/utils/src/typing.ts
- tests/form/schemaForm.test.tsx
close https://github.com/ant-design/pro-components/issues/3509
> feat(form): form columns support dependencies   

- packages/field/src/components/Text/index.tsx
- packages/form/src/components/FieldSet/demos/components-other-readonly.tsx
- packages/form/src/components/FieldSet/index.md
- tests/field/field.test.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3425
> fix(form): proformtext support prefix and suffix

- .fatherrc.ts
- .github/workflows/deploy.yml
- jest.config.js
- package.json
- packages/form/src/BaseForm/index.tsx
- packages/layout/src/BasicLayout.tsx
- packages/layout/src/WrapContent.tsx
- packages/layout/src/demos/error-boundaries.tsx
- packages/layout/src/layout.md
- packages/list/src/index.tsx
- packages/table/package.json
- packages/table/src/components/Form/index.tsx
- packages/table/src/components/ToolBar/index.tsx
- packages/table/src/utils/cellRenderToFromItem.tsx
- packages/table/src/utils/columnRender.tsx
- packages/utils/package.json
- packages/utils/src/hooks/useDeepCompareEffect/index.ts
- packages/utils/src/index.tsx
- packages/utils/src/isDeepEqualReact/index.ts
- tests/layout/__snapshots__/demo.test.ts.snap
- feat(layout): layout support error-boundaries
- feat(layout): layout support error-boundaries
> feat(layout): support layout error boundaries

- packages/form/src/components/FieldSet/demos/components-other-readonly.tsx
- packages/form/src/components/FieldSet/demos/components-other.tsx
- packages/form/src/components/FieldSet/index.en-US.md
- packages/form/src/components/Group/index.tsx
- packages/form/src/interface.d.ts
- tests/__snapshots__/doc.test.ts.snap
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3156
close https://github.com/ant-design/pro-components/issues/3107
close https://github.com/ant-design/pro-components/issues/3344
> fix(form): better FormGroup Space style

- packages/form/src/components/FieldSet/demos/components-other-readonly.tsx
- packages/form/src/components/FieldSet/demos/components-other.tsx
- packages/form/src/components/FieldSet/index.en-US.md
- packages/form/src/components/Group/index.tsx
- packages/form/src/interface.d.ts
- packages/utils/src/useEditableArray/index.tsx
- tests/__snapshots__/doc.test.ts.snap
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
close  https://github.com/ant-design/pro-components/issues/3553
> fix(table): fix save and cancel button click error

- packages/layout/src/demos/error-boundaries.tsx
- tests/layout/__snapshots__/demo.test.ts.snap
> chore: update ErrorBoundary demo for use real ErrorBoundary

- packages/form/src/BaseForm/index.tsx
- packages/form/src/layouts/LoginForm/index.tsx
- packages/form/src/layouts/QueryFilter/index.tsx
- tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/3610
close https://github.com/ant-design/pro-components/issues/3573
close https://github.com/ant-design/pro-components/issues/3451
close https://github.com/ant-design/pro-components/issues/3573
close https://github.com/ant-design/ant-design-pro/issues/9073
close https://github.com/ant-design/ant-design-pro/issues/8928
> fix(form): auto close KeyPress submit

- packages/table/src/table.md
close https://github.com/ant-design/pro-components/issues/3621
> docs(table): Complete the documentation of DragSortTable

- packages/field/src/components/Money/index.tsx
- packages/form/src/demos/base.tsx
- packages/layout/src/components/PageContainer/index.md
- tests/field/__snapshots__/demo.test.ts.snap
- tests/field/__snapshots__/field.test.tsx.snap
- tests/form/__snapshots__/demo.test.ts.snap
> fix: #3651 修复金额输入组件设置width无效的问题

- packages/form/src/components/DatePicker/DatePicker.tsx
- packages/form/src/components/DatePicker/MonthPicker.tsx
- packages/form/src/components/DatePicker/QuarterPicker.tsx
- packages/form/src/components/DatePicker/WeekPicker.tsx
- packages/form/src/components/DatePicker/YearPicker.tsx
- packages/form/src/components/DateRangePicker/index.tsx
- packages/form/src/components/DateTimePicker/index.tsx
- packages/form/src/components/DateTimeRangePicker/index.tsx
- packages/form/src/components/Text/index.tsx
- packages/form/src/components/TimePicker/index.tsx
- packages/form/src/interface.ts
close https://github.com/ant-design/pro-components/issues/3646
> chore: beta typescript error

- packages/form/src/components/FormItem/index.tsx
- packages/form/src/demos/base.tsx
- packages/form/src/layouts/LoginForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/3601
> fix(form): fix the problem of repeated prompts

- packages/table/src/demos/ListToolBar/tabs.tsx
- packages/table/src/utils/cellRenderToFromItem.tsx
- tests/table/__snapshots__/demo.test.ts.snap
> fix(ProTable): proFieldProps.proFieldKey custom key should priority over dataIndex

- packages/provider/src/locale/ru_RU.tsx
Correct translation to russian please.
> 🌎Internationalization: Update ru_RU.tsx

- packages/form/src/BaseForm/createField.tsx
- packages/form/src/components/DatePicker/index.tsx
- packages/form/src/components/Field/index.tsx
- packages/form/src/components/FieldSet/index.tsx
- packages/form/src/components/FormItem/index.tsx
- packages/form/src/components/Radio/index.tsx
- packages/form/src/components/Rate/index.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/form/src/components/Select/index.tsx
- packages/form/src/components/Text/index.tsx
- packages/form/src/components/TextArea/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/fieldSet.test.tsx
- tests/form/formitem.test.tsx
close https://github.com/ant-design/pro-components/issues/3669
close https://github.com/ant-design/pro-components/issues/3599
close https://github.com/ant-design/pro-components/issues/3667
> fix(form): fix the problem of multiple calls

- packages/list/src/Item.tsx
- packages/list/src/list.md
- tests/list/__snapshots__/demo.test.ts.snap
> feat(list): card list support selected

- packages/table/src/components/DragSortTable/index.tsx
- packages/table/src/demos/drag-sort-table.tsx
close https://github.com/ant-design/pro-components/issues/3689
> fix(table): fix DragSortTable render problems with multiple renders

- packages/form/src/BaseForm/index.tsx
- packages/form/src/demos/base.tsx
- packages/form/src/demos/formRef.tsx
- packages/form/src/form.md
- packages/provider/src/locale/ja_JP.tsx
- tests/form/__snapshots__/base.test.tsx.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/base.test.tsx
- 增加验证并返回格式化后值的方法 validateFieldsReturnFormatValue
- 并增加`formRef`相关说明文档
close https://github.com/ant-design/pro-components/issues/3639
> feat(form):  增加验证并返回格式化后值的方法 validateFieldsReturnFormatValue

- packages/form/src/BaseForm/createField.tsx
- tests/form/base.test.tsx
> fix(form): fix:select unnamed cache

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/demo.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- yarn.lock
close https://github.com/ant-design/pro-components/issues/3724
> fix(form): drawer/modal support getContainer=false

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- fix-drawer
- fix(form): no use div ref render dom
> fix(form): no use div ref render dom

- packages/form/src/components/List/index.tsx
close https://github.com/ant-design/pro-components/issues/3731
> 🐛 fix(form): 修复了formList组件无法向外抛出actionRef

- packages/form/src/components/Group/demos/base-use.tsx
- packages/form/src/components/List/index.tsx
- tests/form/formList.test.tsx
close https://github.com/ant-design/pro-components/issues/3756
> feat(form): form support use singer function

- packages/form/src/BaseForm/LightWrapper/index.tsx
- packages/form/src/BaseForm/createField.tsx
- packages/form/src/components/FormItem/index.tsx
- tests/form/lightFilter.test.tsx
close https://github.com/ant-design/pro-components/issues/3700
> fix(form): ProFormField lightProps no work error

- tests/list/__snapshots__/index.test.tsx.snap
- tests/list/index.test.tsx
As title, just add a test case to snapshot the list component in loading state.
> chore(test): add snapshot test for list in loading state

- packages/field/package.json
- packages/layout/package.json
- packages/utils/package.json
close https://github.com/ant-design/pro-components/issues/3942
> chore: lock swr fix mjs throw error

- packages/table/src/components/EditableTable/index.tsx
> 🐛 fix(table): EditableTable controlled default value

- packages/descriptions/src/demos/use-data-source.tsx
- packages/descriptions/src/descriptions.en-US.md
- packages/descriptions/src/descriptions.md
- packages/descriptions/src/index.tsx
- packages/table/src/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
> 💥 feat(pro-descriptions): support copyable and ellipsis

- packages/field/src/components/Select/SearchSelect/index.tsx
- packages/field/src/components/Select/index.tsx
- packages/field/src/demos/base_test.tsx
- packages/form/src/components/FieldSet/demos/components-other.tsx
- packages/form/src/components/FieldSet/demos/search-select.tsx
- packages/form/src/components/FieldSet/index.md
- packages/form/src/components/Select/index.tsx
- packages/utils/src/hooks/useDebounceFn/index.ts
- packages/utils/src/typing.ts
- tests/demo.tsx
- tests/field/field.test.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/schemaForm.test.tsx
1.防止请求频繁添加select防抖动属性debounceTime: number 
2.按照示例添加测试内容
> feat(field): select request 添加防抖动属性 

- packages/field/src/components/FromNow/index.tsx
- tests/field/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
与当前的时间进行比较的时候有显示几秒（前或后），几分种（前或后），几小时（前或后）
> fix(field): fromNow should show time

- packages/field/src/components/Money/index.tsx
> 🐛 fix(field): Money precision can't work

- packages/field/src/index.tsx
- packages/form/src/components/Field/index.tsx
- packages/layout/src/utils/getMenuData.ts
close https://github.com/ant-design/pro-components/issues/3231
close https://github.com/ant-design/pro-components/issues/2329
> fix(form): fix onchange rechange error

- packages/form/src/layouts/QueryFilter/index.tsx
- packages/layout/src/utils/getMenuData.ts
- tests/__snapshots__/doc.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/list/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/column.test.tsx.snap
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/index.test.tsx.snap
- tests/table/__snapshots__/valueEnum.test.tsx.snap
close https://github.com/ant-design/pro-components/issues/3592
close https://github.com/ant-design/pro-components/issues/4010
> fix(form): fix form item width overflow problew

- packages/card/src/components/Card/index.less
- packages/form/src/demos/form-layout.tsx
- packages/table/src/demos/card-title.tsx
- packages/table/src/table.md
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
1. 添加卡片表格示例
2. 添加 ProCard less token
3. 修复 form 的 layout demo 布局问题。
> feat(table): add card table 

- packages/form/src/BaseForm/index.tsx
- packages/form/src/components/Submitter/index.tsx
- packages/form/src/layouts/LightFilter/index.tsx
- packages/layout/src/components/SiderMenu/BaseMenu.tsx
- packages/layout/src/components/SiderMenu/index.tsx
- packages/list/src/index.less
- packages/table/src/Table.tsx
- packages/table/src/components/EditableTable/demos/form-linkage.tsx
- packages/table/src/components/EditableTable/demos/real-time-editing.tsx
- packages/table/src/components/EditableTable/index.tsx
- packages/table/src/container.tsx
- packages/table/src/utils/cellRenderToFromItem.tsx
- packages/table/src/utils/columnRender.tsx
- packages/utils/src/components/InlineErrorFormItem/index.tsx
- packages/utils/src/useEditableArray/index.tsx
- tests/setupTests.js
- tests/table/__snapshots__/editor-table.test.tsx.snap
- tests/table/editor-table.test.tsx
- tests/utils/index.test.tsx
> feat(table):Reduce the use of layering and forms

- packages/form/src/components/ModalForm/demos/drawer-form.tsx
- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
close https://github.com/ant-design/pro-components/issues/4036
> fix(form): support onVisibleChange form set

- packages/utils/src/useEditableArray/index.tsx
ref https://github.com/ant-design/pro-components/pull/3997
> fix(descriptions): fix descriptions cancel values no work error

- packages/table/src/utils/cellRenderToFromItem.tsx
- packages/utils/src/useEditableArray/index.tsx
close https://github.com/ant-design/pro-components/issues/4045
> fix(table): all render cell form

- packages/field/src/components/Digit/index.tsx
close https://github.com/ant-design/pro-components/issues/4040
> fix(form): support higher accuracy

- packages/form/src/components/Group/demos/dependency.tsx
- packages/form/src/components/Group/index.en-US.md
- packages/form/src/components/Group/index.md
- packages/form/src/components/List/index.less
- packages/form/src/components/List/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/formList.test.tsx
@chenshuai2144 看下可不可，不知道这么改合不合适
close #4041
> feat(form): ProFormList support showItemLabel

- packages/descriptions/src/index.tsx
- packages/table/src/index.tsx
- packages/table/src/utils/columnRender.tsx
- packages/utils/src/genCopyable/index.tsx
- packages/utils/src/index.tsx
close https://github.com/ant-design/pro-components/issues/4059
> fix(descriptions): unuse protable

- packages/form/src/BaseForm/createField.tsx
- packages/form/src/index.tsx
- packages/table/src/demos/lightfilter.tsx
- packages/table/src/typing.ts
- packages/utils/src/typing.ts
close  https://github.com/ant-design/pro-components/issues/4067
> fix(table): pro table support lightProps

- packages/field/src/components/Money/index.tsx
- packages/form/src/BaseForm/index.tsx
- packages/utils/src/hooks/useFetchData/index.tsx
通过较小改动修复了 #4007 这个问题，如果您同意，可以深度优化
close  #4007
> fix(ProForm): 修复ProForm请求两次问题

- packages/field/src/components/DatePicker/index.tsx
- packages/table/src/utils/columnRender.tsx
- packages/utils/src/genCopyable/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/field/__snapshots__/demo.test.ts.snap
- tests/field/__snapshots__/field.test.tsx.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/editor-table.test.tsx.snap
- tests/table/__snapshots__/index.test.tsx.snap
> 🐛 fix(field): DatePicker ellipsis can't work when mode is read

- packages/layout/src/components/TopNavHeader/index.less
- packages/list/src/ListView.tsx
close https://github.com/ant-design/ant-design-pro/issues/9328﻿
> fix(layout): no set topmenu font weight

- packages/form/src/components/FieldSet/index.md
> fix:docs ProFormCascader component example

- packages/form/src/BaseForm/index.tsx
> 🐛 fix(form): syncToUrl params judgment error

- packages/field/src/components/RangePicker/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
> 🐛 fix(field): RangePicker format support funtion

- packages/form/src/components/FormItem/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/4129
> fix(form): fix the problem that addonBefore Required does not work when formitem is set

- packages/table/src/Table.tsx
修复#4112-ProTable中 配置了params， 通过改变params来重新请求数据时，页码没有从第一页开始
fix #4112
> fix(#4112-ProTable中 配置了params， 通过改变params来重新请求数据时，页码没有从第一页开始): 已修复

- packages/table/src/components/EditableTable/demos/basic.tsx
> fix: fix wrong comment.

- packages/field/src/components/RangePicker/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/field/datePick.test.tsx
ref https://github.com/ant-design/pro-components/pull/4113
> fix(form): fix RangePicker format is string,will error

- packages/form/src/components/FieldSet/index.md
> 📝 docs(form): ProFormUploadButton props

- packages/provider/src/locale/ca_ES.tsx
Added file ca_ES.tsx with the catalan translations
> Added catalan translations

- packages/field/package.json
- packages/field/src/components/Select/index.tsx
- packages/layout/package.json
- packages/layout/src/BasicLayout.tsx
- packages/provider/package.json
- packages/utils/package.json
- packages/utils/src/hooks/useFetchData/index.tsx
- yarn.lock
[swr 1.1](https://github.com/vercel/swr/releases/tag/1.1.0) now has built-in and stable serialization for SWR keys.
> fix: simplify swr usage

- packages/list/src/list.md
> 📝 docs(list): actionRef props

- .github/workflows/coverage.yml
- packages/card/src/components/CheckCard/index.less
- packages/card/src/components/Operation/index.less
- packages/card/src/components/Statistic/index.less
- packages/card/src/components/StatisticCard/index.less
close https://github.com/ant-design/pro-components/issues/4212
> chore: alway use es path less

- packages/form/src/components/SchemaForm/demos/steps-form.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/form/src/layouts/StepsForm/index.tsx
> fix(form): 🐛 SchemaForm and StepsForm formRef error

- docs/schema.md
- packages/field/src/components/Cascader/index.tsx
- packages/field/src/demos/base.tsx
- packages/table/src/demos/valueType_select.tsx
- tests/field/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
> fix(form): cascader mode=text error

- packages/layout/src/layout.en-US.md
- packages/layout/src/layout.md
更新 defaultCollapsed 使用说明，需要配合 breakpoint 一起使用，容易造成困惑。
这里有一个相关 issue  #2800
> docs(pro-layout): 更新 defaultCollapsed 使用说明

- packages/form/src/BaseForm/index.tsx
- packages/layout/src/WrapContent.tsx
- packages/provider/src/index.tsx
close https://github.com/ant-design/pro-components/issues/4184
> fix(provide): close auto clean cache

- packages/layout/src/Footer.tsx
- packages/layout/src/demos/api.tsx
- tests/layout/__snapshots__/footer.test.tsx.snap
- tests/layout/footer.test.tsx
> fix(layout): remove defaultLinks

- .dumi/theme/useDarkreader.tsx
- .umirc.js
- packages/layout/package.json
- packages/layout/src/components/SettingDrawer/index.tsx
- packages/utils/src/isBrowser/index.ts
- yarn.lock
> docs: fix website ssr error

- packages/field/src/components/TimePicker/index.tsx
> fix(field): timeRange解析时间不填入format是会直接Invalid date

- packages/layout/src/layout.md
> 📝 docs(layout): code render error

- packages/form/src/BaseForm/index.tsx
fix #4269 syncToUrl params error
> fix(form): syncToUrl params error

- packages/table/src/table.md
文档页多了一个多余的“查询表格”，在代码中是debug，去除掉是不是比较好，如下。
> fix(table): remove exceptional 查询表格 section (it's debug purpose)

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/drawerForm.test.tsx
- tests/form/modalForm.test.tsx
close https://github.com/ant-design/pro-components/issues/4281
> fix(form): fix the problem that the animation of the floating layer form is lost

- packages/utils/src/transformKeySubmitValue/index.ts
- tests/utils/index.test.tsx
close https://github.com/ant-design/pro-components/issues/4143
> fix(utils): Stronger judgment

- packages/table/src/components/ColumnSetting/index.less
- packages/table/src/components/ColumnSetting/index.tsx
close https://github.com/ant-design/pro-components/issues/4180
> fix(table): if one node, no draggable

- packages/field/src/components/Cascader/index.tsx
- packages/field/src/demos/base_test.tsx
- tests/field/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/4247
> fix(field): Cascader support loading icon

- packages/utils/src/typing.ts
close https://github.com/ant-design/pro-components/issues/4345
> fix(utils): update typing.ts

- packages/form/src/form.md
> docs: fix doc error

- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/container.tsx
ColumnsState add disableCheckbox and disabled attribute to support disabled setting's operation.
> feat(ProTable): support disabled setting's operation

- packages/form/src/components/Submitter/index.tsx
<Space />  ->.  <Space wrap />
> fix(form): 表单 submitter 增加自动换行属性

- packages/layout/src/Footer.tsx
- packages/layout/src/demos/api.tsx
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/footer.test.tsx.snap
fix https://github.com/ant-design/pro-components/issues/3841
> fix(layout): remove default Copyright, fix#3841

- packages/form/src/BaseForm/createField.tsx
> fix(form): FormList same name will be cache problem

- packages/table/src/Table.tsx
- packages/table/src/components/Alert/index.tsx
- packages/table/src/demos/batchOption.tsx
- packages/table/src/table.en-US.md
- packages/table/src/table.md
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/index.test.tsx
close https://github.com/ant-design/pro-components/issues/4424
> fix(table): fix defaultSelectedRowKeys no work error

- packages/form/src/components/FormItem/index.tsx
- packages/list/src/demos/pagination.tsx
- packages/list/src/demos/special.tsx
- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/demos/dynamic-settings.tsx
- packages/table/src/demos/listToolBar.tsx
- packages/table/src/demos/valueType_select.tsx
- packages/table/src/utils/columnRender.tsx
- tests/table/__snapshots__/demo.test.ts.snap
https://user-images.githubusercontent.com/24643779/149089855-474a2ca7-c724-4b31-a990-c57acedc8d88.mp4
> 📝 docs(table): fix demo error

- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/components/EditableTable/demos/basic.tsx
- packages/table/src/typing.ts
- packages/table/src/utils/cellRenderToFromItem.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
> fix(table): 🎸 Support readonly option for EditableTable

- packages/form/src/interface.ts
> fix(form):  remove allowClear type

- packages/field/src/components/Select/LightSelect/index.tsx
- packages/field/src/components/Select/SearchSelect/index.tsx
- packages/field/src/components/Select/index.tsx
- packages/field/src/demos/search-value.tsx
- tests/field/field.test.tsx
> fix(field): select fieldNames options

- packages/table/src/table.en-US.md
- packages/table/src/table.md
修复后：
| 属性 | 描述 | 类型 | 默认值 |
| --- | --- | --- | --- |
| fieldProps | 查询表单的 props，...也支持方法传入 | ` (form,config)=>Record \| Record ` | - |
> fix(table): modify table document

- packages/list/src/Item.tsx
> fix(list): 修复 ProList 卡片模式 actions 区域事件冒泡导致点击选中卡片的问题

- packages/table/src/Table.tsx
- packages/table/src/components/ToolBar/index.tsx
- packages/table/src/typing.ts
- tests/table/index.test.tsx
> fix(table): parameter error when passing function to reload or fullScreen

- packages/form/src/components/SchemaForm/index.tsx
> fix(form): BetaSchemaForm setFieldsValue 失效

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/schemaForm.test.tsx
> fix(form): make sure it is valid to get the form instance through formRef

- packages/field/src/components/Switch/index.tsx
- tests/table/__snapshots__/index.test.tsx.snap
> fix(field): Switch checked为false不生效问题

- package.json
- packages/utils/src/types/index.ts
- packages/utils/src/types/valueTypeWithFieldProps.ts
- packages/utils/src/typing.ts
- tests/table/__snapshots__/index.test.tsx.snap
- yarn.lock
尝试过针对每一个valueType提供不同的fieldProps类型，但性能堪忧
目前是把所有具有类型聚合在一起提示，也就是说当valueType为`select`时依然会有`text`的maxLength类型提示
使用我的电脑测试发现，改动之后更加耗时了
执行yarn tsc目前为15 ~ 16s，之前为9 ~ 10秒
> feat(form): enhancement type

- packages/form/src/components/FieldSet/index.en-US.md
Fix formatting of tables
Before:
> docs(form): fix table formatting

- packages/field/src/components/Image/index.tsx
close https://github.com/ant-design/pro-components/issues/4563
> fix(form): fix cannot be given refs error

- packages/form/src/BaseForm/createField.tsx
- packages/form/src/components/FormItem/index.tsx
- packages/table/src/Table.tsx
- packages/table/src/components/EditableTable/index.tsx
- packages/table/src/useFetchData.tsx
- packages/table/src/utils/cellRenderToFromItem.tsx
- packages/utils/src/useEditableArray/index.tsx
- tests/form/base.test.tsx
close https://github.com/ant-design/pro-components/issues/4553
> feat(table): reduce the dom of the form

- packages/utils/src/hooks/useRefFunction/index.ts
> fix(utils): make sure the function doesn't change

- packages/form/src/components/ModalForm/demos/drawer-form.tsx
- packages/form/src/components/ModalForm/demos/modal-form.tsx
- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/drawerForm.test.tsx
- tests/form/modalForm.test.tsx
close https://github.com/ant-design/pro-components/issues/4446
> fix(form): modal and drawer new render function

- packages/descriptions/src/demos/arrayDataIndex.tsx
- packages/descriptions/src/descriptions.md
- packages/utils/src/useEditableArray/index.tsx
- packages/utils/src/useEditableMap/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/descriptions/editor.test.tsx
fix: #4611 
- 修复当 dataIndex 设置为 keypath 数组时 ProDescriptions 更新异常问题
> fix(descriptions): 修复当 dataIndex 设置为 keypath 数组时 ProDescriptions 更新异常问题

- docs/demos/valueType.tsx
- packages/form/src/components/SchemaForm/demos/dependencies.tsx
- packages/form/src/components/SchemaForm/demos/dynamic-rerender.tsx
- packages/form/src/components/SchemaForm/demos/embed.tsx
- packages/form/src/components/SchemaForm/demos/schema.tsx
- packages/form/src/components/SchemaForm/demos/valueType.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/form/src/components/SchemaForm/typing.ts
- tests/__snapshots__/doc.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/schemaForm.test.tsx
> feat(form): improve type reminder

- packages/field/package.json
- packages/field/src/components/Select/index.tsx
- packages/layout/package.json
- packages/provider/package.json
- packages/utils/package.json
- packages/utils/src/hooks/useDebounceFn/index.ts
- packages/utils/src/hooks/useDebounceValue/index.ts
- packages/utils/src/index.tsx
- tests/field/__snapshots__/field.test.tsx.snap
- tests/field/field.test.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/utils/index.test.tsx
- yarn.lock
fix #4534
重新实现debounce相关逻辑 参考 #https://github.com/vercel/swr/issues/110#issuecomment-552637429
> fix(field):  setting debounceTime results in repeated requests

- packages/form/src/demos/pro-form-editableTable.tsx
- packages/table/src/utils/cellRenderToFromItem.tsx
- tests/form/__snapshots__/demo.test.ts.snap
fix: #4330 
- EditableProTable 支持在 renderFormItem 中的 record 中返回用户自定义的字段
> fix(table,form): EditableProTable 支持在 renderFormItem 中的 record 中返回用户自定义的字段

- packages/form/src/components/FieldSet/index.en-US.md
- packages/form/src/components/FieldSet/index.md
- packages/provider/src/locale/tr_TR.tsx
- packages/provider/src/locale/zh_TW.tsx
feat: #4666 
- 更新`土耳其新里拉`货币符号
- 更新`新台币`货币符号
> feat(form): 更新货币符号

- packages/form/src/components/Dependency/index.tsx
- tests/form/dependency.test.tsx
> feat(form): improve dependency component archive

- packages/form/src/form.en-US.md
- packages/form/src/form.md
> docs(form): fix live code error

- .umirc.js
- packages/descriptions/src/demos/editable.tsx
- packages/descriptions/src/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/descriptions/editor.test.tsx
- tests/descriptions/index.test.tsx
- tests/layout/pageContainer.test.tsx
close https://github.com/ant-design/pro-components/issues/4683
close https://github.com/ant-design/pro-components/issues/4668
> fix(descriptions): fix descriptions copy dom error

- packages/field/src/components/Money/index.tsx
Adding support to render the PT-BR currency format
> feat(field): add pt-BR support to currency format

- packages/table/src/Table.tsx
- packages/table/src/demos/error-boundaries-false.tsx
- packages/table/src/demos/error-boundaries.tsx
- packages/table/src/table.md
- packages/table/src/typing.ts
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/index.test.tsx.snap
Table 支持自定义 ErrorBoundary ，用于自定义错误处理
> feat(table): support ErrorBoundary

- tests/table/pagination.test.tsx
补充ProTable pagination受控时候的单元测试。
> （chore: test）: 补充ProTable单测

- docs/schema.md
- packages/form/src/components/Cascader/index.tsx
- packages/form/src/components/Checkbox/index.tsx
- packages/form/src/components/Radio/index.tsx
- packages/form/src/components/Select/index.tsx
- packages/form/src/components/TreeSelect/index.tsx
- packages/form/src/interface.ts
> docs: improve type and load remote data docs

- packages/field/src/components/Select/index.tsx
> fix(form): Select search result label containing `#` do not display

- packages/table/src/components/ColumnSetting/index.tsx
> fix(Table): preserve columnState when deselecting

- packages/form/src/components/Slider/index.tsx
fix https://github.com/ant-design/pro-components/issues/4665
> fix(ProFormSlider): range props not working because of SliderSingleProps

- packages/table/src/utils/cellRenderToFromItem.tsx
> fix(table):  fix no `fieldProps` injected error

- packages/form/src/layouts/StepsForm/StepForm.tsx
- packages/form/src/layouts/StepsForm/index.tsx
> fix(Form): switching current on `onFinish` has no effect

- packages/form/src/components/SchemaForm/demos/schema.tsx
- packages/form/src/components/SchemaForm/index.tsx
- packages/form/src/components/SchemaForm/layoutType/Embed.tsx
- packages/form/src/components/SchemaForm/layoutType/StepsForm.tsx
- packages/form/src/components/SchemaForm/layoutType/index.ts
- packages/form/src/components/SchemaForm/typing.ts
- packages/form/src/components/SchemaForm/valueType/field.tsx
1. 抹平不同的layoutType 组件统一渲染，减少if/else
2. 优化类型提示StepsForm columns是个二维数组其他组件为一维数组
- 易读
- 易维护
- 易于拓展新的layoutType组件
- ...
> feat(form):  improve SchemaForm achieve

- packages/form/src/components/List/index.tsx
- tests/form/formList.test.tsx
> fix(form): avoid executing setState after unmount

- packages/table/src/utils/columnRender.tsx
> fix(EditableTable):  mode=edit causes action column not to show

- packages/table/src/Table.tsx
- packages/table/src/components/EditableTable/demos/basic.tsx
fix: #4809
沿用ProTable的loading类型
> feat(EditableTable): support custom loading

- packages/form/src/components/StepsForm/demos/steps-form-vertical.tsx
- packages/form/src/components/StepsForm/index.md
- packages/form/src/layouts/StepsForm/index.less
- packages/form/src/layouts/StepsForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
close: #4843
这个布局不知道能不能接受
https://user-images.githubusercontent.com/29533304/158136487-278f4a1d-390b-4feb-b027-3f7885fa2dc0.mp4
> feat(form): StepsForm support vertical direction

- packages/table/src/components/EditableTable/demos/basic.tsx
- packages/table/src/components/EditableTable/demos/children.tsx
- packages/table/src/components/EditableTable/demos/custom.tsx
- packages/table/src/components/EditableTable/demos/form-item.tsx
- packages/table/src/components/EditableTable/demos/form-linkage.tsx
- packages/table/src/components/EditableTable/demos/real-time-editing.tsx
> docs: set scroll support for mobile preview

- packages/form/src/components/QueryFilter/demos/light-filter-test.tsx
- packages/form/src/components/QueryFilter/demos/light-filter.tsx
> docs(slider): remove wrong prop

- packages/list/src/index.less
> fix(list): avatar shrink when card width is not enough

- packages/card/src/card.md
Card 文档增加 headStyle 和 bodyStyle。
原本能力就在，但是文档没有说明
> docs(card): card docs add head & body style

- packages/form/src/components/Dependency/index.tsx
> fix(form): field will be ignored when value=0

- packages/field/src/components/Select/index.tsx
说明：
为 `ProFormSelect` 组件，添加 `style` 和 `className` 属性支持
> feat(form): Select add style and className prop

- packages/utils/src/conversionMomentValue/index.ts
- tests/utils/index.test.tsx
> fix(utils): add missing backslash in moment format

- packages/provider/src/index.tsx
- tests/layout/index.test.tsx
> fix(form): `LoginForm` login button i18n invalid

- packages/form/src/BaseForm/BaseForm.tsx
- tests/form/base.test.tsx
> fix(form): ConfigProvider setting componentSize dosen't work when using BaseForm

- packages/table/src/table.en-US.md
- packages/table/src/table.md
> docs: fix columnsState docs typo

- packages/form/src/components/SchemaForm/index.tsx
- tests/form/schemaForm.test.tsx
> fix(form): do not re-execute fieldProps when onValuesChange is set

- packages/table/src/container.tsx
- packages/table/src/demos/single.tsx
- tests/table/columnSetting.test.tsx
> fix(table): columnsState use index as state name

- packages/utils/src/isDeepEqualReact/index.ts
- tests/utils/index.test.tsx
> fix(utils): empty prototype property causes comparison error

- packages/table/src/components/Form/index.less
fix: https://github.com/ant-design/ant-design-pro/issues/9706#issue-1181925418
> fix: table search styles overridden

- packages/table/src/utils/cellRenderToFromItem.tsx
> fix(table): onSave cannot get after editing data

- packages/layout/src/components/SettingDrawer/index.less
> fix(layout): color variables

- packages/card/src/card.md
> add collapsibleIconRender's description in API doc

- packages/layout/src/components/SettingDrawer/index.tsx
> 🐛 fix(compiler): fix use DarkReader

- packages/form/src/components/FormItem/index.tsx
- packages/form/src/components/List/ListItem.tsx
- tests/form/formList.test.tsx
> fix(form): Invalid use of DatePicker format in ProFormList

- packages/field/src/components/Select/index.tsx
- packages/form/src/BaseForm/createField.tsx
fix: https://github.com/ant-design/pro-components/issues/4770#issuecomment-1081691290
> fix(form): cacheForSwr not work

- packages/table/src/demos/dateFormatter.tsx
- tests/table/__snapshots__/demo.test.ts.snap
Table Demo 增加margin
之前的样式：
现在的：
> docs(table): table demo margin add

- packages/table/src/Table.tsx
- packages/table/src/components/ToolBar/index.tsx
- packages/table/src/typing.ts
- tests/table/index.test.tsx
> fix(table):  解决修改轻量筛选条件时覆盖了table自带keywords过滤的值的问题

- packages/form/src/demos/form-layout-grid.tsx
> docs: layout demo fixed

- packages/table/src/utils/cellRenderToFromItem.tsx
> fix(form): new row uses previous data

- packages/table/src/components/EditableTable/demos/basic.tsx
readonly不填写数据，有个rules导致validateFields过不去
> docs: remove readonly rules

- packages/field/src/components/Select/LightSelect/index.tsx
> fix(form): ProSelect not cleared keywords when closing option

- packages/form/src/components/List/ListContainer.tsx
- packages/form/src/components/List/ListItem.tsx
- packages/form/src/components/List/index.tsx
- tests/form/formList.test.tsx
Added a fieldExtraRender Prop to proformlist
> feat(form): Render Extra Content inside Pro Form List

- packages/form/src/layouts/QueryFilter/index.tsx
close https://github.com/ant-design/pro-components/issues/5024
> fix(form): fix document is null, will error

- packages/field/src/components/Cascader/index.tsx
- packages/field/src/components/TreeSelect/index.tsx
- packages/form/src/components/Cascader/index.tsx
- packages/form/src/components/QueryFilter/demos/light-filter.tsx
- packages/form/src/components/TreeSelect/index.tsx
- tests/field/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
close https://github.com/ant-design/pro-components/issues/5012
close https://github.com/ant-design/pro-components/issues/5021
> fix(form): fix ProFormTreeSelect and ProFormCascader no work when LightFilter

- packages/layout/src/BasicLayout.tsx
- packages/layout/src/WrapContent.tsx
fix https://github.com/ant-design/pro-components/issues/5043
> feat(layout): update swr cache clear solution

- packages/form/src/components/LoginForm/index.md
LoginForm api md排版问题
每次使用vscode进行md格式化有概率出现这个问题，帮我们多加了 --- ｜
> docs(form): Loginform api 文档修改

- packages/form/src/components/Group/index.md
- packages/form/src/components/List/ListItem.tsx
> chore: ProFormList RenderProps 透传总行数count参数

- packages/utils/src/useEditableArray/index.tsx
> fix: key does not exist causing error

- packages/table/src/typing.ts
> fix(table): missing headerBordered type

- packages/table/src/useFetchData.tsx
fix: https://github.com/ant-design/pro-components/issues/5084
> feat(table): reinitialize umountRef for react@18 strict mode

- packages/table/src/table.en-US.md
the URL hash is not missing a hyphen, so MD cannot link to there
> fix: SearchConfig md link not working

- tests/form/drawerForm.test.tsx
- tests/form/modalForm.test.tsx
> feat(form): fix test case

- packages/form/src/layouts/LoginForm/index.less
- packages/form/src/layouts/LoginForm/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
fix https://github.com/ant-design/pro-components/issues/5069
> fix(form) 验证码获取 按钮导致登录框宽度动态变化

- packages/card/src/components/CheckCard/index.less
为单选卡片增加角标，fix https://github.com/ant-design/pro-components/issues/5055
> feat(CheckCard): Displays a corner label

- tests/layout/__snapshots__/pageContainer.test.tsx.snap
- tests/layout/index.test.tsx
- tests/layout/pageContainer.test.tsx
- tests/layout/settingDrawer.test.tsx
> docs(layout): layout test fixed

- packages/form/src/components/ModalForm/index.en-US.md
> fix(form): Supplementary English Documents

- packages/layout/src/layout.en-US.md
- packages/layout/src/layout.md
> docs: update ProLayout API

- packages/form/src/layouts/StepsForm/StepForm.tsx
- packages/form/src/layouts/StepsForm/index.tsx
fix ts error
fix unRegForm incorrectly
> fix: unRegForm not work when use step

- packages/table/src/table.md
> chore: add TechUI Studio link

- packages/table/src/Table.tsx
> 🐛 fix(table): fix List pagination.current error

- packages/form/src/components/Group/demos/horizontal-layout.tsx
- packages/form/src/components/Group/index.md
> docs(form): proformlist horizontal demo

- packages/form/src/components/Group/demos/base-use.tsx
- tests/form/__snapshots__/demo.test.ts.snap
> 📝 docs(Form): fix ProFormList demos error

- packages/form/src/BaseForm/BaseForm.tsx
- packages/form/src/FieldContext.tsx
- packages/form/src/components/Checkbox/index.tsx
- packages/form/src/components/Radio/index.tsx
- packages/form/src/components/Select/index.tsx
- packages/form/src/components/Slider/index.tsx
- packages/form/src/components/Switch/index.tsx
- packages/form/src/components/Text/index.tsx
- packages/form/src/components/TextArea/index.tsx
- packages/form/src/components/TreeSelect/index.tsx
- packages/form/src/components/UploadButton/index.tsx
- packages/form/src/interface.ts
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/base.test.tsx
close [#5198](https://github.com/ant-design/pro-components/issues/5198).
> feat(form): `FieldProps` add `ref` type

- packages/form/src/helpers/grid.tsx
> fix(form): When grid is enabled, input will be blur after setState

- packages/card/package.json
- packages/descriptions/package.json
- packages/field/package.json
- packages/form/package.json
- packages/layout/package.json
- packages/list/package.json
- packages/provider/package.json
- packages/skeleton/package.json
- packages/utils/package.json
> fix: #5273 for all components

- packages/form/src/BaseForm/BaseForm.tsx
- packages/form/src/components/SchemaForm/demos/schema.tsx
- packages/form/src/helpers/grid.tsx
- tests/form/__snapshots__/demo.test.ts.snap
> fix(form): setting colProps in the Form dose not work

- packages/form/src/layouts/QueryFilter/index.tsx
- tests/form/queryFilter.test.tsx
close https://github.com/ant-design/pro-components/issues/5328
> fix(form):  defaultColsNumber did not meet expect

- packages/field/src/components/Select/SearchSelect/index.tsx
- packages/form/src/components/Select/index.tsx
- tests/form/base.test.tsx
Resolves https://github.com/ant-design/pro-components/issues/2527
> fix(form): SearchSelect component support fetchDataOnSearch

- packages/form/src/layouts/QueryFilter/index.tsx
- packages/list/src/demos/ToolBar.tsx
- packages/list/src/list.md
> docs(List): 带工具栏的列表

- packages/field/src/components/Cascader/index.tsx
- packages/table/src/Table.tsx
fix https://github.com/ant-design/pro-components/issues/5362
> fix(form): fix cascader clear no work error-n

- docs/schema.md
解决官方文档白屏 https://github.com/ant-design/pro-components/issues/5400
> docs: fix document white screen issue

- packages/form/src/components/FormItem/index.tsx
- packages/form/src/components/List/ListContainer.tsx
- packages/form/src/components/List/ListItem.tsx
> fix(form): fix FormItems in FormList umount unexpectedly (#5413)

- packages/layout/src/components/AppsLogoComponents/css.ts
- packages/layout/src/components/AppsLogoComponents/index.tsx
- packages/layout/src/demos/_defaultProps.tsx
- packages/layout/src/layout.md
-  appList add url target
- optimize appList card style
- remove trigger：hover
- fix：stopPropagation when the AppsLogo is clicked
> feat(layout) : app list target

- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/components/ToolBar/index.tsx
- packages/table/src/demos/single.tsx
- packages/table/src/table.md
- feat(table): Make ColumnSetting heights editable
- Merge branch master into Andreybest/master
> feat(table): Make ColumnSetting heights editable

- packages/layout/src/components/WaterMark/demos/textRows.tsx
- packages/layout/src/components/WaterMark/index.md
- packages/layout/src/components/WaterMark/index.tsx
> feat: 支持多行文字水印

- packages/table/src/table.md
- packages/table/src/typing.ts
- packages/table/src/utils/columnRender.tsx
- packages/utils/src/components/LabelIconTip/index.tsx
- tests/table/columnSetting.test.tsx
ProTable columns的ellipsis支持showTitle
> feat: ProTable columns的ellipsis支持showTitle

- packages/table/src/Table.tsx
- packages/table/src/components/EditableTable/demos/children.tsx
- packages/table/src/useFetchData.tsx
- tests/table/polling.test.tsx
- tests/table/protableSpin.test.tsx
- tests/utils/index.test.tsx
需求：需要使用request请求数据的时候，可以传一个loading,也可以传delay等其他属性，如果delay期间 接口返回数据，那我将不在加载loading，如果delay期间接口没有返回数据,我在加载loading，但是目前不支持。
备注: 目前proTable组件 loading只能是一个boolean值，如果传入对象，request 将不会去请求数据，我现在需要它支持Spin的所有属性，所以提交pr
> feat(ProTable):loading属性支持对象类型(SpinProps)

- packages/table/src/Table.tsx
close  https://github.com/ant-design/pro-components/issues/5662
> fix(table): 表格批量操作没有默认值报错

- packages/table/src/Table.tsx
> fix(Table): fix the document

- packages/field/src/components/Money/index.tsx
- packages/form/src/demos/money.tsx
- tests/field/field.test.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/proFormMoney.test.tsx.snap
- tests/form/proFormMoney.test.tsx
- fix(#5707): 修复金额输入框因正则问题导致格式化异常的问题
> fix(field,form): 修复金额输入框因正则问题导致格式化异常的问题

- packages/form/src/components/QueryFilter/demos/query-filter-defaultColsNumber.tsx
- packages/form/src/layouts/QueryFilter/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/queryFilter.test.tsx
> fix(form): 修复查询表单传入的 defaultColsNumber 与表单项数量相同时未显示展开按钮的问题

- packages/card/src/components/StatisticCard/style.ts
> fix(card): card style fixed

- packages/field/src/demos/select-request.tsx
- packages/field/src/field.md
- packages/form/src/BaseForm/BaseForm.tsx
- packages/form/src/BaseForm/createField.tsx
- packages/form/src/FieldContext.tsx
- tests/field/__snapshots__/demo.test.ts.snap
- tests/form/base.test.tsx
> fix(form): 两个ProForm表单下存在相同name的ProFormSelect时，request得到的结果会造成覆盖问题

- packages/form/src/demos/base.tsx
- packages/utils/src/transformKeySubmitValue/index.ts
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/formList.test.tsx
> fix(form): 解决 ProFormList 下的表单组件未调用 transform 方法问题

- packages/form/src/components/List/ListContainer.tsx
- packages/form/src/components/List/ListItem.tsx
> fix(form): 增加FormList样式

- packages/form/src/components/ModalForm/demos/drawer-form.tsx
- packages/form/src/components/ModalForm/demos/modal-form.tsx
- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/drawerForm.test.tsx
> fix(form): 修复ModalForm和DrawerForm指定form和destroyOnClose时关闭时未重置表单问题

- packages/field/package.json
- packages/field/src/components/Digit/index.tsx
- yarn.lock
> fix: 修复 lodash 全部打包错误

- packages/form/src/components/Group/index.md
- packages/form/src/components/List/ListContainer.tsx
- packages/form/src/components/List/ListItem.tsx
- packages/form/src/components/List/index.tsx
- tests/form/formList.test.tsx
- ProFormList 增加 onAfterAdd 和 onAfterRemove 钩子
> feat(form): ProFormList 增加 onAfterAdd 和 onAfterRemove 钩子

- packages/field/src/components/Digit/index.tsx
- tests/field/field.test.tsx
> fix(field): ProFormDigit 设置 stringMode 时修改报错异常修复

- packages/layout/src/components/PageHeader/demo/actions.en-US.md
- packages/layout/src/components/PageHeader/demo/basic.en-US.md
- packages/layout/src/components/PageHeader/demo/breadcrumb.en-US.md
- packages/layout/src/components/PageHeader/demo/content.en-US.md
- packages/layout/src/components/PageHeader/demo/ghost.en-US.md
- packages/layout/src/components/PageHeader/demo/responsive.en-US.md
> fix(layout): 拆分多语言文档解决官网首页搜索异常问题

- packages/card/src/components/CheckCard/Group.tsx
- packages/card/src/components/CheckCard/style.ts
- packages/card/src/components/Loading/style.ts
- packages/layout/src/components/PageContainer/style/index.ts
- tests/card/__snapshots__/demo.test.ts.snap
解决card 和 checkcard loading显示为空的问题
> fix(Card): slove card & checkcard loading problem

- packages/table/src/utils/index.ts
这里应该要加上 await，不然会丢失 promise 状态
https://github.com/ant-design/pro-components/issues/5845
> fix(table): await action?.reload();

- packages/layout/src/utils/getBreadcrumbProps.tsx
> fix(layout): 面包屑最后一个默认禁止点击

- packages/list/src/index.tsx
> feat(list): 优化 ProList 类型描述,支持用户字段提示

- packages/field/src/components/Checkbox/index.tsx
fix https://github.com/ant-design/pro-components/issues/5869 https://github.com/ant-design/pro-components/issues/5838 ?
> fix(form): fix ProFormRadio layout class

- packages/layout/src/style/index.ts
fix: https://github.com/ant-design/ant-design-pro/issues/10220 https://github.com/ant-design/pro-components/issues/5910
> fix(layout): fix colorBgPageContainer

- packages/field/src/components/Radio/index.tsx
> fix(compiler): 修复 ProFormRadio.Group layout 作用反了

- packages/field/src/components/Segmented/index.tsx
- packages/field/src/index.tsx
- packages/form/src/components/FieldSet/demos/components-other.tsx
- packages/form/src/components/FieldSet/index.md
- packages/form/src/components/Segmented/index.tsx
- packages/form/src/components/index.ts
- packages/utils/src/types/index.ts
- tests/field/field.test.tsx
- tests/form/__snapshots__/demo.test.ts.snap
与 [Segmented](https://ant.design/components/segmented-cn/) 相同。支持了 request 和 valueEnum 两种方式来生成 options。
```tsx | pure
<>
<ProFormSegmented
name="segmented"
label="segmented"
valueEnum={{
open: '未解决',
closed: '已解决',
}}
rules={[{ required: true, message: 'Please select your country!' }]}
/>
<ProFormSegmented
name="segmented"
label="segmented"
request={async () => [
{ label: '全部', value: 'all' },
{ label: '未解决', value: 'open' },
{ label: '已解决', value: 'closed' },
{ label: '解决中', value: 'processing' },
]}
rules={[{ required: true, message: 'Please select your country!' }]}
/>
</>
```
antd 版本 >= antd@4.20.0
> feat(form): add ProFormSegmented

- packages/form/src/index.tsx
> feat(pro-form): export FormListContext #5808

- packages/card/src/components/Card/index.tsx
Issues:  https://github.com/ant-design/pro-components/issues/5928
> fix(card): card key props warning

- packages/field/src/components/Segmented/index.tsx
> fix(field): fix ProFormSegmented style

- packages/form/src/layouts/DrawerForm/index.tsx
- packages/form/src/layouts/ModalForm/index.tsx
- tests/form/drawerForm.test.tsx
> feat(form): 修复 ModalForm 和 DrawerForm 关闭过程中表单内容闪现初始值的问题

- packages/table/src/components/EditableTable/demos/basic.tsx
- packages/table/src/components/EditableTable/demos/children.tsx
> docs(docs):修改文档错误单词

- packages/descriptions/src/demos/columns.tsx
- packages/field/src/components/Money/index.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/field/__snapshots__/field.test.tsx.snap
- tests/field/field.test.tsx
> fix(field): 解决 moneySymbol 设置为 false 时金额格式化异常问题

- packages/card/src/components/Card/index.tsx
- packages/card/src/components/TabPane/index.tsx
- packages/card/src/type.ts
- tests/card/__snapshots__/demo.test.ts.snap
- tests/card/index.test.tsx
- tests/descriptions/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
> fix(Card): Support Card.TabPane render as null

- packages/form/src/components/FieldSet/index.md
> docs: 修改文档错别字(#6046)

- packages/provider/src/index.tsx
> fix: 修复pro-provider的ConfigProviderWrap组件导致子组件重新渲染

- packages/table/src/components/ListToolBar/style.ts
> fix(table): toolbar list style fixed

- packages/utils/src/components/FilterDropdown/index.tsx
修复 LightFilter 下确认按钮无法关闭下拉框的问题
> fix(form): fix filter dropdown not close

- packages/table/src/Table.tsx
- packages/table/src/components/Form/FormRender.tsx
- tests/__snapshots__/doc.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/list/__snapshots__/demo.test.ts.snap
- tests/list/__snapshots__/index.test.tsx.snap
- tests/table/__snapshots__/column.test.tsx.snap
- tests/table/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/editor-table-two.test.tsx.snap
- tests/table/__snapshots__/editor-table.test.tsx.snap
- tests/table/__snapshots__/index.test.tsx.snap
- tests/table/__snapshots__/valueEnum.test.tsx.snap
- tests/table/__snapshots__/valueType.test.tsx.snap
> fix(table): table search style fixed

- packages/table/src/components/ListToolBar/HeaderMenu.tsx
- packages/table/src/components/ListToolBar/index.tsx
- packages/table/src/table.md
> fix(table): 修复 inline 类型样式丢失问题

- packages/card/src/components/Operation/index.tsx
- packages/card/src/components/Statistic/index.tsx
- packages/card/src/components/Statistic/style.ts
> fix(card): StaticCard style fixed

- packages/table/src/components/ColumnSetting/index.tsx
> fix(table): column drag order error when move upward

- packages/field/src/components/Digit/index.tsx
- tests/form/base.test.tsx
Link: https://github.com/ant-design/pro-components/pull/6101/files
> fix(form): ProFormDigit value will fixed when not set precision 

- packages/card/src/components/CheckCard/style.ts
- packages/card/src/components/Loading/style.ts
- packages/card/src/components/Statistic/index.tsx
- packages/layout/src/components/SiderMenu/style/index.ts
- packages/list/src/style/index.ts
- packages/table/src/style/index.ts
> fix(layout): 修复 CSS-in-js 中的 animation 警告

- packages/layout/src/components/SiderMenu/style/index.ts
- packages/layout/src/demos/theme.tsx
- packages/layout/src/layout.md
- packages/provider/src/typing/layoutToken.ts
fix: https://github.com/ant-design/pro-components/issues/5985
> fix(layout): layout sider menu add text hover color

- docs/intro.en-US.md
- docs/intro.md
> docs(docs): 修正语法格式

- packages/layout/src/components/PageContainer/index.tsx
- packages/layout/src/components/PageHeader/index.tsx
- packages/layout/src/components/PageHeader/style/index.ts
- packages/layout/src/components/TopNavHeader/style.ts
- tests/layout/__snapshots__/demo.test.ts.snap
> fix(Layout):  在内容定宽下，TopNavHeader 的样式问题

- packages/descriptions/src/descriptions.en-US.md
- packages/descriptions/src/descriptions.md
> doc(descriptions): descriptions doc link empty

- packages/form/src/components/Cascader/index.tsx
[feat(form): support auto getPopupContainer](https://github.com/ant-design/pro-components/commit/896c11363f5a3d8043bf3e029bd75496d06ce83d)
此feature覆盖范围补充
> fix(form): add ProFormCascader auto getPopupContainer

- packages/table/src/components/DragSortTable/demos/drag-sort-table.tsx
- packages/table/src/components/DragSortTable/index.tsx
- fix: 修复拖拽排序表格使用数据源时数据源改变后未更新数据问题
- feat: 优化可拖拽排序表格 request 方式获取数据源时的 demo
> fix: 修复拖拽排序表格使用数据源时数据源改变后未更新数据问题

- packages/field/src/components/Checkbox/index.tsx
close  https://github.com/ant-design/pro-components/issues/6212
>  fix(compiler): 修复 checkbox 在 ant design 5 vertical 布局失效问题

- packages/form/src/BaseForm/BaseForm.tsx
> fix(form): formRef repeats the assignment

- packages/table/src/Table.tsx
- tests/table/__snapshots__/demo.test.ts.snap
> fix(table):  table extra classname wrong

- packages/provider/package.json
> fix: slove ghost dep problem

- packages/form/src/components/List/ListItem.tsx
- packages/form/src/components/List/style.ts
- tests/form/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/index.test.tsx.snap
fixes [#6392](https://github.com/ant-design/pro-components/issues/6392).
> fix: `ProFormList`  style does not work

- packages/card/src/components/CheckCard/style.ts
修复checkcard 在 disable 和 选中态一起存在时候角标样式错误问题
> fix(card): checkcard disable & checked style fixed

- packages/utils/src/components/DropdownFooter/style.ts
https://github.com/ant-design/pro-components/issues/6421
> 轻量筛选替换查询表单，将 padding 调为 8px 更为统一美观

- packages/provider/src/useStyle/token.ts
- tests/layout/__snapshots__/index.test.tsx.snap
> fix(provider): remove illegal space in style token

- packages/field/src/components/Select/SearchSelect/index.tsx
- packages/field/src/demos/search-value-autoClearSearchValue.tsx
- packages/field/src/field.md
- tests/field/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/index.test.tsx.snap
> fix(Select): SearchSelect optimization

- packages/layout/src/ProLayout.tsx
- packages/layout/src/demos/base.tsx
- packages/provider/src/index.tsx
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/layout/pageContainer.test.tsx
修复 prolayout 传入自定义 prefixCls 时样式异常
> feat(layout): 修复 prolayout 传入自定义 prefixCls 时样式异常

- packages/layout/src/components/SiderMenu/index.tsx
Problem
Layout sider should open from right on rtl direction
Change log 
fix(layout): set sider placement to right if direction is rtl
> fix(layout): open sider from right on rtl direction

- packages/form/src/components/QueryFilter/demos/light-filter-test.tsx
- packages/form/src/components/QueryFilter/demos/light-filter.tsx
- packages/form/src/components/QueryFilter/demos/query-filter.tsx
移除query-filter的demo中不必要的company 字段定义
> fix: query filter ts error

- packages/utils/src/components/FieldLabel/index.tsx
> fix(form): `FieldLabel` support i18n

- .dumirc.ts
> fix(descriptions): 修复官网跳转

- packages/provider/src/intl.ts
- packages/table/src/index.tsx
This is a hotfix to https://github.com/ant-design/pro-components/issues/6529#issuecomment-1425049644.
> fix: Thai translation in ProTable

- packages/field/src/components/Digit/index.tsx
- packages/utils/src/isNil/index.ts
- tests/form/__snapshots__/base.test.tsx.snap
- tests/form/base.test.tsx
Fix #5743
看了下之前的 pr，应该确实是修复了这个问题，但后续重构的时候又把逻辑改回去了
> fix(form): inconsistent digit value when precision=0

- packages/layout/src/components/SiderMenu/BaseMenu.tsx
- tests/layout/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/index.test.tsx.snap
> fix(layout): remove `title` attribute

- packages/form/src/components/form.en-US.md
- packages/form/src/components/form.md
update site docs about proform #6612
> docs: update site docs about proform #6612

- packages/field/src/components/Select/LightSelect/index.tsx
- packages/utils/src/components/FieldLabel/style.ts
- tests/form/lightFilter.test.tsx
> fix(field): `optionFilterProp` doesn't work with LightFilter

- docs/docs/intro.md
> docs: 修改文档中的错词

- packages/card/package.json
- packages/field/package.json
- packages/form/package.json
- packages/layout/package.json
- packages/list/package.json
- packages/table/package.json
> Feat update icons

- packages/utils/src/useEditableArray/index.tsx
fix https://github.com/ant-design/pro-components/issues/6652
> fix(EditableTable): editableKeys maybe undefined

- packages/table/src/Table.tsx
> fix(table): selectedRows拿不到最新的值

- .dumi/theme/store/useSiteStore.ts
- packages/card/src/components/CheckCard/index.tsx
- packages/card/src/components/Statistic/index.tsx
- packages/descriptions/src/useFetchData.tsx
- packages/field/src/components/Image/index.tsx
- packages/form/src/components/DigitRange/index.tsx
- packages/form/src/layouts/QueryFilter/index.tsx
- packages/table/src/utils/index.ts
- packages/utils/src/compareVersions/openVisibleCompatible.ts
- packages/utils/src/typing.ts
- packages/utils/src/useEditableArray/index.tsx
- packages/utils/src/useEditableMap/index.tsx
- tests/form/lightFilter.test.tsx
- tests/layout/defaultSettings.ts
- tests/table/demo.tsx
> fix: optimized type

- packages/table/src/utils/index.ts
Reverts ant-design/pro-components#6690
> Revert "fix: remove useless code"

- packages/table/src/components/EditableTable/index.tsx
> fix: 修复maxLength选项配置为0时逻辑不符合预期的问题

- .dumi/theme/plugin.ts
The `ssrCssFileName` should respect `publicPath` config
> fix(dumi): fix ssrCssFileName path issue

- package.json
read more: https://nodejs.org/api/packages.html#packagemanager
> chore: add packageManager field

- packages/table/src/components/ListToolBar/HeaderMenu.tsx
- packages/table/src/components/ListToolBar/index.tsx
> feat: ProTable的toolbar.tabs和toolbar.menu配置下增加defaultActiveKey选项

- packages/provider/src/locale/ko_KR.tsx
Want to modified languages some places korean locale code file.
I have tried setting up Ant Design protable using the toolbar, and I think some languages are miss translate chinese to korean.
So, Please Can you guys modified the languages to correct translate in korean with toolbarrender in order to using more comfortable for korean user?
> style: modified languages in Ko_KR (#6953, #6877)

- package.json
- packages/field/src/index.tsx
Fixes `tsc` error at `packages/field/src/index.tsx`.
> fix: tsc error

- packages/layout/src/components/FooterToolbar/index.tsx
- packages/layout/src/components/Header/index.tsx
- packages/layout/src/components/Header/style/header.ts
- packages/layout/src/defaultSettings.ts
- packages/layout/src/demos/base.tsx
- packages/provider/src/typing/layoutToken.ts
- tests/layout/__snapshots__/demo.test.ts.snap
- fix: update snapshot
- fix: update snapshot
- fix: update snapshot
- fix(layout): support fix header scroll use new color
> fix(layout): support fix header scroll use new color

- docs/components/schema.en-US.md
- docs/components/schema.md
- docs/components/valueEnum-map.tsx
- packages/field/src/components/Checkbox/index.tsx
- packages/field/src/components/Radio/index.tsx
- packages/field/src/components/Segmented/index.tsx
- packages/provider/src/index.tsx
- packages/utils/src/typing.ts
- tests/__snapshots__/doc.test.ts.snap
> feat: ProSchemaValueEnumMap类型key增加对boolean的支持

- packages/form/src/components/form.md
> fix_delete useless navigation bars

- packages/layout/src/components/SiderMenu/style/menu.ts
> fix(layout): 修复 collapsedShowTitle 样式错误问题 

- packages/utils/src/components/FieldLabel/style.ts
> fix(form): close icon style

- packages/utils/src/useEditableArray/index.tsx
component EditableProTable actionDeleteRef function Single row status Locked
问题一
组件 EditableProTable 在多条数据数据实时编辑与form配合 ，进行删除操作，然后进行静态数据set 删除行始终处于不可编辑状态
如下代码 删除最后一条，然后点击设置数据，未修改前状态是不可编辑的
```js
import type { ProColumns } from '@ant-design/pro-components';
import {
EditableProTable,
ProCard,
ProFormField,
} from '@ant-design/pro-components';
import { Button, Form } from 'antd';
import React, { useState } from 'react';
type DataSourceType = {
id: React.Key;
title?: string;
decs?: string;
state?: string;
created_at?: string;
children?: DataSourceType[];
};
const defaultData: DataSourceType[] = new Array(20).fill(1).map((_, index) => {
return {
id: (Date.now() + index).toString(),
title: `活动名称${index}`,
decs: '这个活动真好玩',
state: 'open',
created_at: '1590486176000',
};
});
export default () => { …
```
> fix(table): component EditableProTable actionDeleteRef function 

- packages/layout/src/components/AppsLogoComponents/index.tsx
- packages/layout/src/components/SiderMenu/SiderMenu.tsx
> feat(layout): 添加appListRender api

- tsconfig.json
Review it now , This is a bug, right
> fix: 去除重复引入

- packages/form/src/layouts/LightFilter/index.tsx
> fix(form): 修复当LightFilter折叠模式icon样式问题

- packages/form/src/layouts/DrawerForm/index.tsx
> fix: remove console.log

- packages/table/src/utils/columnRender.tsx
调整了一下这样看代码逻辑更好懂。 或者也可以改一下函数里面的逻辑
> 调整ProTable中的函数名，增加可读性

- packages/provider/src/intl.ts
- packages/provider/src/locale/he_IL.tsx
Hi!
I want to use your pro table but it seems there is no support in Hebrew, so I added a new Hebrew locale file.
I would really appreciate it if you could merge it to your master so I could use it.
thank you!
> hebrew support

- packages/form/src/layouts/StepsForm/index.tsx
佈局應該是可定制的。
The layout should be customizable.
Not tested.
https://github.com/ant-design/pro-components/issues/7429
> feat(form): StepForm added layoutRender props

- packages/form/src/components/Group/index.en-US.md
- packages/form/src/components/Group/index.md
- packages/form/src/components/List/ListItem.tsx
> docs(ProFormList): 完善 `defaultActionDom` 描述 (#7420)

- packages/form/src/BaseForm/BaseForm.tsx
fix form field support moblie width best
> fix(form): form field support moblie width best

- packages/table/src/utils/useDragSort.tsx
fix: https://github.com/ant-design/pro-components/issues/7335
> fix(table): DragSortTable 每次 render 执行时 Table DOM 会销毁重建新的 DOM

- packages/form/src/components/form.md
- packages/utils/package.json
- packages/utils/src/transformKeySubmitValue/index.ts
- pnpm-lock.yaml
fix: https://github.com/ant-design/pro-components/issues/7463
> feat(form): transform 支持深合并

- packages/field/src/components/ColorPicker/index.tsx
- packages/utils/src/typing.ts
- tests/field/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/layout/__snapshots__/demo.test.ts.snap
> feat(field): 修复 field color style width:100% 导致的样式不美观问题 & ts 定义

- docs/components/schema.en-US.md
- docs/components/schema.md
- docs/components/valueType.tsx
- packages/field/src/components/Code/index.tsx
fix  https://github.com/ant-design/pro-components/issues/5444
> fix: jsoncode 编辑态没有格式问题

- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/components/ToolBar/index.tsx
- packages/table/src/components/table.en-US.md
- packages/table/src/components/table.md
> feat(table): custom `toolbar` icon

- packages/table/src/components/ColumnSetting/index.tsx
- packages/table/src/components/ToolBar/index.tsx
由于项目中的table需要将列不能固定，所以就增加了fixable的配置项。
> feat: table columns setting add fixable config

- packages/table/src/components/table.en-US.md
- packages/table/src/components/table.md
column setting option type in the table document add "showListItemOption" props
> column setting option type in the table document add "showListItemOption" props

- packages/form/src/components/ModalForm/index.en-US.md
- packages/form/src/components/ModalForm/index.md
- packages/form/src/layouts/DrawerForm/index.tsx
fix  https://github.com/ant-design/pro-components/issues/7614
> fix(form):更新 DrawerForm resize参数默认值&文档描述

- packages/field/src/components/DatePicker/index.tsx
- tests/field/datePick.test.tsx
> Fix datepicker format

- packages/layout/src/components/layout.md
> docs: add appListRender api description

- packages/layout/src/components/PageContainer/demos/token.tsx
- packages/layout/src/components/PageContainer/index.tsx
- packages/layout/src/components/PageContainer/style/index.ts
- packages/provider/src/typing/layoutToken.ts
> feat(layout): 更新 PageContainer Token 样式和计算规则

- packages/table/README.md
- packages/table/src/components/EditableTable/index.en-US.md
- packages/table/src/components/table.en-US.md
Maintaining the integrity of the document as well as some minor modifications to the English document.
> docs: Consistent with Chinese documentation

- packages/layout/src/components/Header/index.tsx
- packages/layout/src/components/TopNavHeader/index.tsx
> fix(layout): deprecated warning

- packages/table/src/demos/pollinga.tsx
- packages/table/src/typing.ts
> docs: clarify the use of polling, 0 means to disable polling

- packages/form/src/components/LoginForm/demos/login-form-page.tsx
- packages/form/src/layouts/LoginFormPage/index.tsx
- packages/form/src/layouts/LoginFormPage/style.ts
- tests/form/__snapshots__/demo.test.ts.snap
- feat(form): login page new style
- 修复类型错误
> feat(form): new LoginFormPage style

- packages/form/src/components/UploadButton/index.tsx
- tests/form/upload.test.tsx
> fix(form): the `onChange` event in `ProFormUploadButton`  has been triggered multiple times

- packages/list/src/demos/ToolBar.tsx
- tests/list/__snapshots__/demo.test.ts.snap
修复ProList content文本颜色被固定,导致更换主题无法改变
> docs(List) :fix content text color being fixed

- packages/layout/src/ProLayout.tsx
- packages/layout/src/components/PageContainer/index.tsx
> fix(types): breadcrumbProps

- packages/utils/src/pickProFormItemProps/index.tsx
- tests/form/__snapshots__/demo.test.ts.snap
- tests/list/__snapshots__/demo.test.ts.snap
- tests/table/__snapshots__/demo.test.ts.snap
revert https://github.com/ant-design/pro-components/pull/7769
> fix(revert): 回滚 FormField 的 style 和 ClassName 透传

- packages/table/src/components/DragSortTable/demos/drag.tsx
- packages/table/src/components/DragSortTable/index.en-US.md
- packages/table/src/components/DragSortTable/index.md
- packages/table/src/components/DragSortTable/index.tsx
- packages/table/src/utils/useDragSort.tsx
> feat(table): expose `index` in `onDragSortEnd`

- packages/card/src/components/Card/index.tsx
fix: https://github.com/ant-design/pro-components/issues/7730
> fix(card): 移除stopPropagation，让事件继续冒泡

- packages/table/src/components/table.md
> fix: update table.md

- packages/card/src/components/CheckCard/style.ts
fix: https://github.com/ant-design/pro-components/issues/7832
> style(list): 样式修复

- packages/field/src/components/Select/LightSelect/index.tsx
- packages/utils/src/components/FieldLabel/index.tsx
#7845
[需求]希望FieldLabel的普通表单回显的最大长度VALUE_MAX_LENGTH可以通过参数传入
> feat(utils) FieldLabel的VALUE_MAX_LENGTH可以通过参数传入 (#7845)

- docs/components.md
- docs/components/schema.md
- packages/descriptions/src/components/descriptions.md
- packages/form/src/components/ModalForm/index.md
- packages/form/src/components/StepsForm/index.md
- packages/form/src/components/form.md
- packages/layout/src/components/layout.md
- packages/table/src/components/table.md
> docs: fix errors and improve readability in docs

- packages/table/src/components/ToolBar/DensityIcon.tsx
- packages/table/src/components/ToolBar/index.tsx
fixd: https://github.com/ant-design/pro-components/issues/7933
之前的 feat 密度icon那个没改好 https://github.com/ant-design/pro-components/issues/7509
> fix(settings): slove DensityIcon setting not work

- packages/card/src/components/CheckCard/index.en-US.md
- packages/card/src/components/StatisticCard/index.en-US.md
- packages/layout/src/components/WaterMark/index.en-US.md
links: https://github.com/ant-design/pro-components/issues/7992
> docs: update Components en-US docs

- packages/form/src/layouts/DrawerForm/index.tsx
> fix(form): remove extra `div`

- packages/form/src/components/Submitter/index.tsx
- tests/form/__snapshots__/base.test.tsx.snap
- tests/form/__snapshots__/demo.test.ts.snap
- tests/form/__snapshots__/proFormMoney.test.tsx.snap
- tests/form/__snapshots__/schemaForm.test.tsx.snap
- tests/form/loginForm.test.tsx
> chore(form): adjust `submitter` dom order

- packages/form/src/components/form.en-US.md
- packages/form/src/components/form.md
修改[#7988](https://github.com/ant-design/pro-components/pull/7988)中ProForm的submitter属性关于render第二个参数的文档说明
> docs: 修改ProForm的submitter属性关于render第二个参数的说明

- packages/field/src/components/Segmented/index.tsx
- pnpm-lock.yaml
- tests/form/proFormSegmented.test.tsx
> fix(field): fieldProps.options not effective in ProFormSegmented

- README.md
- README.zh-CN.md
> feat: add star history

- pnpm-lock.yaml
- tests/layout/__snapshots__/waterMark.test.tsx.snap
- tests/layout/waterMark.test.tsx
> feat: add watermark test code

- packages/provider/src/locale/zh_CN.tsx
- packages/provider/src/locale/zh_TW.tsx
- packages/table/src/components/ToolBar/DensityIcon.tsx
> fix: densityLarger中文简体和繁体国际化，文案问题修改

- packages/table/src/useFetchData.tsx
> Fix typo in useFetchData.tsx

- packages/table/src/typing.ts
see https://github.com/ant-design/pro-components/issues/8274
> chore(table): update column search ts type

- packages/descriptions/src/index.tsx
fix https://github.com/ant-design/pro-components/issues/8266
> fix(descriptions): Customized contentStyle

- packages/table/src/utils/useDragSort.tsx
fix：https://github.com/ant-design/pro-components/issues/8239
> fix(table): Custom components.body no work error

- packages/layout/src/ProLayout.tsx
links: https://github.com/ant-design/pro-components/issues/8173
> fix(layout): 解决FooterRender的类型错误

- packages/form/src/components/form.en-US.md
- packages/form/src/components/form.md
fix: https://github.com/ant-design/pro-components/issues/8289
> docs(ProForm): autoFocusFirstInput default value

- packages/utils/src/components/FieldLabel/index.tsx
fix: https://github.com/ant-design/pro-components/issues/8237
复现栗子：https://pro-components.antdigital.dev/components/query-filter#%E8%BD%BB%E9%87%8F%E7%AD%9B%E9%80%89
https://github.com/ant-design/pro-components/assets/84793349/43b1197d-8dbe-4b99-80e4-eab531c8f06d
> fix(form): Fix the problem of FieldLabel activating style

- packages/form/src/BaseForm/LightWrapper/index.tsx
修改了LightWrapper的清除功能
close: https://github.com/ant-design/pro-components/issues/8262
close: https://github.com/ant-design/pro-components/issues/8303
测试了 https://github.com/ant-design/pro-components/pull/6450 符合预期
> fix(Form): FilterDropdown onClear setTempValue null

- package.json
- pnpm-lock.yaml
close: https://github.com/ant-design/pro-components/issues/8279
见: https://dumi-theme-antd-style.arvinx.com/changelog#version0262
> build: update dumi-theme-antd-style

- packages/form/src/components/LoginForm/demos/login-form-page.tsx
- packages/form/src/components/LoginForm/demos/login-form.tsx
- tests/form/__snapshots__/demo.test.ts.snap
> fix: replace login url

- packages/field/src/components/Select/LightSelect/index.tsx
将LightSelect组件中，popupMatchSelectWidth={false}注释掉，变成灵活多变的动态配置，供用户自行配置。
否则，popupMatchSelectWidth写死false会关闭虚拟滚动，数量量过大时，影响组件性能
> fix: 提升LightSelect组件性能

- packages/field/src/components/Select/SearchSelect/index.tsx
- tests/form/base.test.tsx
close: https://github.com/ant-design/pro-components/issues/8313
> fix(form): SearchSelect scrolling error in grouping

- packages/form/src/components/index.ts
- packages/form/src/index.tsx
close: https://github.com/ant-design/pro-components/issues/8370
> chore: :hammer: export ProFormCheckboxProps type

- packages/form/src/components/FieldSet/index.md
close: https://github.com/ant-design/pro-components/issues/8324
> docs(form): FieldSet filedProps Corrected to fieldProps

- packages/descriptions/src/index.tsx
- tests/card/__snapshots__/demo.test.ts.snap
- tests/form/base.test.tsx
- tests/table/__snapshots__/demo.test.ts.snap
close: https://github.com/ant-design/pro-components/issues/8391
> chore(descriptions): Reveal the key to prevent errors

- README.md
> doc: Star History Chart changed

- packages/form/src/components/FormItem/index.tsx
related: https://github.com/ant-design/ant-design/discussions/48001
I want to use help props as guide message for the input. (always visible)
so i use help props, I cant't see the validate error when after validation.
i want to use help and validate together.
So I added a render type that passes errors to params.
code 
```
<ProFormText
label="name"
name="name"
help={"You can also input emojis and special character"}
rules={[Validations.required()]}
/>
```
before validate
after validate
After validation, help is displayed instead of the required error message.
code 
```
<ProFormText
label="name"
name="name"
help={({errors}) => errors.length ? errors[0] : "You can also input emojis and special character"}
rules={[Validations.required()]}
/>
```
before validate
after validate
After …
> feat: add form item help render type

- packages/table/src/demos/single.tsx
- packages/table/src/demos/theme.tsx
- packages/table/src/typing.ts
修复了ProTable的transform参数的注释，以及文档中Table demo中的注释
> docs(table): correct transform props comments and demo comments

- packages/field/src/components/TextArea/readonly.tsx
> fix: don't pass antd textarea property to span

- packages/layout/src/components/PageContainer/index.md
- packages/layout/src/components/layout.en-US.$tab-api.md
link: [https://github.com/umijs/dumi/issues/2168](https://github.com/umijs/dumi/issues/2168)
> fix: PageContainer's document has Scrollbar

- .github/workflows/preview-build.yml
fix preview-build workflow run failure
about: https://github.com/pnpm/action-setup/issues/136#issuecomment-2211039766
> chore(ci): upgrade pnpm/action-setup to v2.4.1

- packages/form/src/components/List/style.ts
> fix: correct line height in list action

- packages/field/src/index.tsx
refs: https://github.com/ant-design/pro-components/issues/7348
> feat(field): add localizedFormat plugin to dayjs

- packages/table/src/Table.tsx
**问题**
当 hideToolbar 属性为 true 时，Toolbar 被隐藏，但是 toolbarDom 并不是 null，导致 Card 的 padding 有问题
> fix: card padding when hideToolbar

- packages/table/src/Table.tsx
> fix: defaultCurrent 搭配 defaultData 一直为 1 的问题修复

- packages/form/src/layouts/QueryFilter/index.tsx
> docs(typo): 修正 QueryFilter span 示例配置8

- packages/provider/src/intl.ts
- packages/provider/src/locale/nl_NL.tsx
- packages/provider/src/locale/ro_RO.tsx
- packages/provider/src/locale/sv_SE.tsx
背景：业务场景需要多语言：nl_NL ro_RO sv_SE
> [feat]: add locales nl_NL ro_RO sv_SE

- packages/provider/src/useStyle/index.ts
> fix(provider): support antd csp

- packages/form/src/BaseForm/createField.tsx
- packages/form/src/components/FieldSet/index.md
补充相关使用文档
相关 issue：https://github.com/ant-design/pro-components/issues/8876
> docs: add ProFormTreeSelect docs

- packages/form/src/BaseForm/LightWrapper/index.tsx
- packages/form/src/components/SchemaForm/demos/schema.tsx
添加日期类型，修复官网报错
> https://github.com/ant-design/pro-components/issues/8850
> fix: add dateRange type && typo in word

- .github/workflows/pkg.pr.new.yml
同 antd 一样：https://github.com/ant-design/ant-design/blob/master/.github/workflows/pkg.pr.new.yml
> ci: add publish ci

- packages/layout/src/components/SettingDrawer/index.tsx
- tests/layout/settingDrawer.test.tsx
Add drawerExtra Props makes SettingDrawer support extra
> feat(layout): Add drawerProps for SettingDrawer

- packages/layout/src/components/FooterToolbar/index.tsx
- packages/layout/src/components/SettingDrawer/index.tsx
这里的作者之前有个笔误，导致FooterToolbar不支持SSR，请合并后帮忙发个新版本，谢谢🙏
> fix: FooterToolbar supports SSR

- packages/table/src/Table.tsx
- packages/table/src/utils/genProColumnToColumn.tsx
> fix: remove Table deadCode

- packages/form/src/components/SchemaForm/valueType/field.tsx
fix(SchemaForm): 修复SchemaForm renderFormItem 警告
> fix(SchemaForm): 修复SchemaForm renderFormItem 警告

- packages/table/src/components/table.en-US.md
- packages/table/src/components/table.md
新增ignoreRules 描述，同时英文文档新增disable使用描述
> Update documentation for ProTable

- packages/provider/src/index.tsx
> fix(Provider):修复dark黑色主题无效的问题

- packages/table/src/utils/genProColumnToColumn.tsx
Fix issue [#9002](https://github.com/ant-design/pro-components/issues/9002)
> fix(table): ensure valueType has higher priority than valueEnum

- packages/provider/src/useStyle/index.ts
fix #8955
background & solution: https://github.com/ant-design/pro-components/issues/8955#issuecomment-2603539698
more:
CC @zombieJ
> fix:layer dependency causing definition order issue
